#!/usr/bin/env python3
"""EduClaw schema — 46 tables, 117 indexes.

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to add table-level UNIQUE/CHECK constraints and fix
prerequisite_course_id FK (generator limitation with same-table double refs).

The docstring said "32 tables, 88 indexes, 419 columns" and the closing print
said 46. Both were stale: 32/88 counted only the DSL-generated block and missed
the six domains appended later (cafeteria, transportation, professional
development, online fee payment, student activities, library, housing), while 46
still counted `educlaw_meal_plan`, dropped 2026-07-22 (WS4/D5, M33b §5). The
installer creates 45 tables; corrected here rather than carried.

The 32 shared tables are owned by the sibling `educlaw_base_schema.py`,
which five educlaw sub-verticals call so the base exists when a sub-vertical is
installed before its parent. This file imports them (`BASE_METADATA`,
`ensure_educlaw_base_tables`) and declares only core's own tables here; this file
converts educlaw CORE only and leaves the shared file untouched.

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw (standalone — no parent product)
Run: python3 init_db.py [db_path]

ADR-0034 phase 2 bulk-39. Schema declared as metadata and provisioned through
`erpclaw_lib.seam`, which emits dialect-correct DDL, replacing a hand-written
``CREATE TABLE`` block opened with ``sqlite3.connect`` that could not run on
PostgreSQL at all. Conversion rules are the pilot's (`erpclaw-esign`): seam
vocabulary only, money and IDs stay TEXT, and ``primary_key=True,
nullable=True`` reproduces SQLite's ``id TEXT PRIMARY KEY`` without adding a
NOT NULL that never shipped. The 15 ``DEFAULT (datetime('now'))`` columns in the
later domains use ``now_default()``, which renders that expression byte-for-byte
on SQLite and ``CURRENT_TIMESTAMP`` on PostgreSQL — the SQLite-only spelling was
what stopped this module provisioning there.
"""
import importlib.util
import os
import sys

# Bootstrap the shared lib only when it is not already reachable — an
# unconditional insert at position 0 overrides a caller that deliberately bound a
# different tree (ADR-0034 phase 2 step 2d).
if importlib.util.find_spec("erpclaw_lib") is None:
    sys.path.insert(0, os.path.join(os.path.expanduser(
        os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "lib"))

from erpclaw_lib.seam import (  # noqa: E402
    CheckConstraint, Column, ForeignKey, Index, Integer, MetaData, Table, Text,
    UniqueConstraint, now_default, provision, reference_table, table_exists,
    text,
)

DEFAULT_DB_PATH = os.path.join(os.path.expanduser(os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "data.sqlite")
DISPLAY_NAME = "EduClaw"

# The pre-conversion probe asked for `company` alone. Transcribed, not widened.
REQUIRED_FOUNDATION = ["company"]

# educlaw_base_schema sits one level up, beside the vertical directories — the
# same resolution the five sub-verticals already use.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# The shared 32 live in educlaw_base_schema (ONE OWNER, 2026-08-16). Core
# provisions them via ensure_educlaw_base_tables and declares only its own 13
# here, so a CHECK widened in one place can never again be stale in the other.
from educlaw_base_schema import (  # noqa: E402
    BASE_METADATA, ensure_educlaw_base_tables,
)

METADATA = MetaData()

# Foundation tables this module points at but does not own — declared so the
# foreign keys resolve, never created here.
reference_table("company", METADATA)
reference_table("account", METADATA)
reference_table("customer", METADATA)
reference_table("department", METADATA)

# Shared base tables that core's own 13 point at. Declared as references so the
# foreign keys resolve; they are CREATED by ensure_educlaw_base_tables, never here.
reference_table("educlaw_student", METADATA)
reference_table("educlaw_instructor", METADATA)
reference_table("educlaw_guardian", METADATA)
reference_table("educlaw_fee_structure", METADATA)

# ==========================================================
# EduClaw Domain Tables
# Generated by ERPForge Schema DSL
# ==========================================================

# ---------------------------------------------------------------------------
# 1. educlaw_academic_year
# ---------------------------------------------------------------------------
DAILY_MEAL_COUNT = Table(
    "educlaw_daily_meal_count", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("school_id", Text, nullable=False),
    Column("count_date", Text, nullable=False),
    Column("free_breakfast", Integer, server_default=text("0")),
    Column("reduced_breakfast", Integer, server_default=text("0")),
    Column("regular_breakfast", Integer, server_default=text("0")),
    Column("free_lunch", Integer, server_default=text("0")),
    Column("reduced_lunch", Integer, server_default=text("0")),
    Column("regular_lunch", Integer, server_default=text("0")),
    Column("adult_meals", Integer, server_default=text("0")),
    Column("snack_count", Integer, server_default=text("0")),
    Column("counted_by", Text),
    Column("notes", Text),
    Column("created_at", Text, server_default=now_default()),
    UniqueConstraint("school_id", "count_date"),
)

Index("idx_educlaw_meal_count_date", DAILY_MEAL_COUNT.c.count_date)

STUDENT_MEAL_RECORD = Table(
    "educlaw_student_meal_record", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text, ForeignKey("educlaw_student.id"),
           nullable=False),
    Column("meal_date", Text, nullable=False),
    Column("meal_type", Text, nullable=False),
    Column("eligibility", Text, nullable=False),
    Column("allergen_alert", Integer, server_default=text("0")),
    Column("served_by", Text),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint("meal_type IN ('breakfast','lunch','snack')",
                    name="ck_educlaw_student_meal_record_meal_type"),
    CheckConstraint("eligibility IN ('free','reduced','paid')",
                    name="ck_educlaw_student_meal_record_eligibility"),
)

Index("idx_educlaw_meal_record_student", STUDENT_MEAL_RECORD.c.student_id)
Index("idx_educlaw_meal_record_date", STUDENT_MEAL_RECORD.c.meal_date)

# ==========================================================
# DOMAIN: TRANSPORTATION / BUS MANAGEMENT
# ==========================================================

BUS_ROUTE = Table(
    "educlaw_bus_route", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("school_id", Text, nullable=False),
    Column("route_number", Text, nullable=False),
    Column("route_name", Text),
    Column("driver_name", Text),
    Column("driver_phone", Text),
    Column("vehicle_id", Text),
    Column("vehicle_number", Text),
    Column("capacity", Integer),
    Column("am_start_time", Text),
    Column("pm_start_time", Text),
    Column("status", Text, nullable=False, server_default=text("'active'")),
    Column("notes", Text),
    Column("created_at", Text, server_default=now_default()),
    Column("updated_at", Text, server_default=now_default()),
    CheckConstraint("status IN ('active','inactive','suspended')",
                    name="ck_educlaw_bus_route_status"),
)

Index("idx_educlaw_bus_route_school", BUS_ROUTE.c.school_id)

BUS_STOP = Table(
    "educlaw_bus_stop", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("route_id", Text, ForeignKey("educlaw_bus_route.id"),
           nullable=False),
    Column("stop_order", Integer, nullable=False),
    Column("stop_name", Text, nullable=False),
    Column("address", Text),
    Column("am_pickup_time", Text),
    Column("pm_dropoff_time", Text),
    Column("created_at", Text, server_default=now_default()),
)

Index("idx_educlaw_bus_stop_route", BUS_STOP.c.route_id)

STUDENT_TRANSPORT = Table(
    "educlaw_student_transport", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text, ForeignKey("educlaw_student.id"),
           nullable=False),
    Column("route_id", Text, ForeignKey("educlaw_bus_route.id"),
           nullable=False),
    Column("bus_stop_id", Text, ForeignKey("educlaw_bus_stop.id")),
    Column("transport_type", Text, nullable=False,
           server_default=text("'both'")),
    Column("special_needs_notes", Text),
    Column("effective_date", Text),
    Column("end_date", Text),
    Column("status", Text, nullable=False, server_default=text("'active'")),
    Column("created_at", Text, server_default=now_default()),
    Column("updated_at", Text, server_default=now_default()),
    CheckConstraint(
        "transport_type IN ('both','am_only','pm_only','none')",
        name="ck_educlaw_student_transport_transport_type"),
    CheckConstraint("status IN ('active','inactive')",
                    name="ck_educlaw_student_transport_status"),
)

Index("idx_educlaw_transport_student", STUDENT_TRANSPORT.c.student_id)
Index("idx_educlaw_transport_route", STUDENT_TRANSPORT.c.route_id)

# ==========================================================
# DOMAIN: PROFESSIONAL DEVELOPMENT (PD Credits)
# ==========================================================

PD_CREDIT = Table(
    "educlaw_pd_credit", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("teacher_id", Text, ForeignKey("educlaw_instructor.id"),
           nullable=False),
    Column("course_name", Text, nullable=False),
    Column("provider", Text),
    Column("credit_hours", Text, nullable=False, server_default=text("'0'")),
    Column("credit_type", Text, server_default=text("'general'")),
    Column("completion_date", Text, nullable=False),
    Column("expiration_date", Text),
    Column("certificate_number", Text),
    Column("status", Text, server_default=text("'approved'")),
    # No foreign key on `company_id` in this domain, unlike the DSL-generated
    # tables above. Preserved as it ships.
    Column("company_id", Text, nullable=False),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint(
        "credit_type IN ('general','content_area','leadership','technology',"
        "'special_education')",
        name="ck_educlaw_pd_credit_credit_type"),
    CheckConstraint("status IN ('pending','approved','rejected')",
                    name="ck_educlaw_pd_credit_status"),
)

Index("idx_educlaw_pd_teacher", PD_CREDIT.c.teacher_id)
Index("idx_educlaw_pd_company", PD_CREDIT.c.company_id)
Index("idx_educlaw_pd_status", PD_CREDIT.c.status)

# ==========================================================
# DOMAIN: ONLINE FEE PAYMENT (Payment Methods)
# ==========================================================

PAYMENT_METHOD = Table(
    "educlaw_payment_method", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("guardian_id", Text, ForeignKey("educlaw_guardian.id"),
           nullable=False),
    Column("method_type", Text, nullable=False),
    Column("last_four", Text),
    Column("is_default", Integer, server_default=text("0")),
    Column("autopay_enabled", Integer, server_default=text("0")),
    Column("external_token", Text),
    Column("status", Text, server_default=text("'active'")),
    Column("company_id", Text, nullable=False),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint("method_type IN ('ach','credit_card','debit_card')",
                    name="ck_educlaw_payment_method_method_type"),
    CheckConstraint("status IN ('active','inactive')",
                    name="ck_educlaw_payment_method_status"),
)

Index("idx_educlaw_payment_method_guardian", PAYMENT_METHOD.c.guardian_id)
Index("idx_educlaw_payment_method_company", PAYMENT_METHOD.c.company_id)

# ==========================================================
# DOMAIN: STUDENT ACTIVITIES (Clubs, Sports, etc.)
# ==========================================================

ACTIVITY = Table(
    "educlaw_activity", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("school_id", Text),
    Column("name", Text, nullable=False),
    Column("activity_type", Text),
    Column("advisor_id", Text),
    Column("description", Text),
    Column("min_gpa", Text),
    Column("max_enrollment", Integer),
    Column("season", Text),
    Column("status", Text, server_default=text("'active'")),
    Column("company_id", Text, nullable=False),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint(
        "activity_type IN ('club','sport','music','art','academic',"
        "'volunteer','other')",
        name="ck_educlaw_activity_activity_type"),
    CheckConstraint("status IN ('active','inactive')",
                    name="ck_educlaw_activity_status"),
)

Index("idx_educlaw_activity_company", ACTIVITY.c.company_id)
Index("idx_educlaw_activity_type", ACTIVITY.c.activity_type)

ACTIVITY_ENROLLMENT = Table(
    "educlaw_activity_enrollment", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("activity_id", Text, ForeignKey("educlaw_activity.id"),
           nullable=False),
    Column("student_id", Text, ForeignKey("educlaw_student.id"),
           nullable=False),
    Column("enrollment_date", Text, nullable=False),
    Column("status", Text, server_default=text("'active'")),
    Column("eligibility_checked", Integer, server_default=text("0")),
    Column("gpa_at_enrollment", Text),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint("status IN ('active','inactive','ineligible')",
                    name="ck_educlaw_activity_enrollment_status"),
)

Index("idx_educlaw_activity_enroll_activity", ACTIVITY_ENROLLMENT.c.activity_id)
Index("idx_educlaw_activity_enroll_student", ACTIVITY_ENROLLMENT.c.student_id)

# ==========================================================
# DOMAIN: LIBRARY MANAGEMENT
# ==========================================================

LIBRARY_ITEM = Table(
    "educlaw_library_item", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("title", Text, nullable=False),
    Column("author", Text),
    Column("isbn", Text),
    Column("item_type", Text),
    Column("category", Text),
    Column("location", Text),
    Column("copy_count", Integer, server_default=text("1")),
    Column("available_copies", Integer, server_default=text("1")),
    Column("status", Text, server_default=text("'available'")),
    Column("company_id", Text, nullable=False),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint(
        "item_type IN ('book','periodical','dvd','digital','equipment','other')",
        name="ck_educlaw_library_item_item_type"),
    CheckConstraint(
        "status IN ('available','checked_out','reserved','lost','damaged')",
        name="ck_educlaw_library_item_status"),
)

Index("idx_educlaw_library_item_company", LIBRARY_ITEM.c.company_id)
Index("idx_educlaw_library_item_isbn", LIBRARY_ITEM.c.isbn)
Index("idx_educlaw_library_item_status", LIBRARY_ITEM.c.status)

# `student_id` has no foreign key here while `library_item_id` does. As it ships.
CIRCULATION = Table(
    "educlaw_circulation", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("library_item_id", Text, ForeignKey("educlaw_library_item.id"),
           nullable=False),
    Column("student_id", Text),
    Column("checkout_date", Text, nullable=False),
    Column("due_date", Text, nullable=False),
    Column("return_date", Text),
    Column("renewed", Integer, server_default=text("0")),
    Column("fine_amount", Text, server_default=text("'0'")),
    Column("status", Text, server_default=text("'checked_out'")),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint(
        "status IN ('checked_out','returned','overdue','lost')",
        name="ck_educlaw_circulation_status"),
)

Index("idx_educlaw_circulation_item", CIRCULATION.c.library_item_id)
Index("idx_educlaw_circulation_student", CIRCULATION.c.student_id)
Index("idx_educlaw_circulation_status", CIRCULATION.c.status)
Index("idx_educlaw_circulation_due", CIRCULATION.c.due_date)

# ==========================================================
# DOMAIN: DORMITORY / HOUSING
# ==========================================================

HOUSING_UNIT = Table(
    "educlaw_housing_unit", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("building_name", Text, nullable=False),
    Column("floor", Text),
    Column("room_number", Text, nullable=False),
    Column("capacity", Integer, server_default=text("1")),
    Column("unit_type", Text),
    Column("amenities", Text),
    Column("monthly_rate", Text, server_default=text("'0'")),
    Column("status", Text, server_default=text("'available'")),
    Column("company_id", Text, nullable=False),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint(
        "unit_type IN ('single','double','triple','suite','apartment')",
        name="ck_educlaw_housing_unit_unit_type"),
    CheckConstraint(
        "status IN ('available','occupied','maintenance','closed')",
        name="ck_educlaw_housing_unit_status"),
)

Index("idx_educlaw_housing_unit_company", HOUSING_UNIT.c.company_id)
Index("idx_educlaw_housing_unit_status", HOUSING_UNIT.c.status)
Index("idx_educlaw_housing_unit_building", HOUSING_UNIT.c.building_name)

HOUSING_ASSIGNMENT = Table(
    "educlaw_housing_assignment", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text, ForeignKey("educlaw_student.id"),
           nullable=False),
    Column("housing_unit_id", Text, ForeignKey("educlaw_housing_unit.id"),
           nullable=False),
    Column("academic_year", Text, nullable=False),
    Column("semester", Text),
    Column("move_in_date", Text),
    Column("move_out_date", Text),
    Column("meal_plan", Text),
    Column("status", Text, server_default=text("'active'")),
    Column("created_at", Text, server_default=now_default()),
    CheckConstraint("status IN ('active','completed','cancelled')",
                    name="ck_educlaw_housing_assignment_status"),
)

Index("idx_educlaw_housing_assign_student", HOUSING_ASSIGNMENT.c.student_id)
Index("idx_educlaw_housing_assign_unit", HOUSING_ASSIGNMENT.c.housing_unit_id)
Index("idx_educlaw_housing_assign_year", HOUSING_ASSIGNMENT.c.academic_year)

# ==========================================================
# DOMAIN: FEE INVOICING (link to the selling module)
# ==========================================================

# A fee invoice IS a sales invoice owned by the foundation: educlaw never
# writes that row. This table is the link on educlaw's own side, one row per
# billed structure per student (`fee`) or per late fee (`late_fee`). No
# foreign key reaches `sales_invoice` itself, which belongs to the foundation.
FEE_INVOICE = Table(
    "educlaw_fee_invoice", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text, ForeignKey("educlaw_student.id"),
           nullable=False),
    Column("invoice_kind", Text, nullable=False),
    Column("fee_structure_id", Text,
           ForeignKey("educlaw_fee_structure.id")),
    Column("fee_category_id", Text),
    Column("academic_term_id", Text),
    Column("sales_invoice_id", Text, nullable=False, unique=True),
    Column("late_fee_for_sales_invoice_id", Text, unique=True),
    Column("amount", Text, nullable=False),
    Column("company_id", Text, ForeignKey("company.id"),
           nullable=False),
    Column("created_at", Text, server_default=now_default()),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    UniqueConstraint("student_id", "fee_structure_id"),
    CheckConstraint("invoice_kind IN ('fee','late_fee')",
                    name="ck_educlaw_fee_invoice_invoice_kind"),
    CheckConstraint("CAST(amount AS NUMERIC) >= 0",
                    name="ck_educlaw_fee_invoice_amount"),
)

Index("idx_educlaw_fee_invoice_student", FEE_INVOICE.c.student_id)
Index("idx_educlaw_fee_invoice_company", FEE_INVOICE.c.company_id)


def _require_foundation(db_path):
    """Refuse to install onto a database with no ERPClaw foundation.

    Same check and same message as before the conversion; the pre-conversion
    version read `sqlite_master` directly, which is a hard error on PostgreSQL
    rather than a false, so it is asked through the seam instead.
    """
    missing = [t for t in REQUIRED_FOUNDATION if not table_exists(t, db_path)]
    if missing:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)


def create_educlaw_tables(db_path):
    """Create EduClaw tables and indexes on whichever backend is configured.

    Same contract as before the ADR-0034 conversion: idempotent, and the returned
    counts are what was ACTUALLY created rather than what was declared.
    """
    _require_foundation(db_path)
    base = ensure_educlaw_base_tables(db_path)
    result = provision(METADATA, db_path)
    return {
        "database": db_path,
        "tables": base["tables"] + result["tables"],
        "indexes": base["indexes"] + result["indexes"],
    }


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    result = create_educlaw_tables(db_path)
    print(f"{DISPLAY_NAME} schema created in {result['database']}")
    print(f"  Tables: {result['tables']}")
    print(f"  Indexes: {result['indexes']}")
