#!/usr/bin/env python3
"""EduClaw Financial Aid schema — 22 owned tables, 443 columns, 59 owned indexes.

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to upgrade multi-column uniqueness constraints to CREATE UNIQUE INDEX.

Parent: educlaw | Tables: 22 owned | Indexes: 59 owned

New domains: financial_aid (15 tables), scholarships (3 tables),
             work_study (3 tables), loan_tracking (1 table)

Append-only tables (no updated_at): finaid_disbursement, finaid_professional_judgment

Installing this module also materialises the 32 shared educlaw base tables via
`ensure_educlaw_base_tables`, because a sub-vertical may be installed before its
parent. Those tables are owned by educlaw CORE and are deliberately NOT declared
in this module's metadata — five sub-verticals call the same helper, and each
declaring them would be five claims of ownership on one schema.

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-finaid (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]

ADR-0034 phase 2 bulk-39. This module's own schema is declared as metadata and
provisioned through `erpclaw_lib.seam`, which emits dialect-correct DDL, instead
of a hand-written ``CREATE TABLE`` block opened with ``sqlite3.connect``. The old
shape could not run on PostgreSQL at all. Conversion rules are the pilot's
(`erpclaw-esign`): seam vocabulary only, money and IDs stay TEXT, and
``primary_key=True, nullable=True`` reproduces SQLite's ``id TEXT PRIMARY KEY``
without adding a NOT NULL that never shipped. Every aid, disbursement, cost-of-
attendance and timesheet amount stays TEXT holding an exact Decimal string
(ADR-0034 dec. 1).

The pre-conversion header claimed "54 tables (32 parent + 22 new) ... 147
indexes". Both totals mixed educlaw core's base tables into this module's
counts and neither reconciled: the base schema carries 93 index statements, not
88, so the true total was 152. Counts here are this module's OWN, which is what
it creates and owns.
"""
import importlib.util
import os
import sys

# The shared educlaw base schema is a sibling of this module's directory.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Bootstrap the shared lib only when it is not already reachable — an
# unconditional insert at position 0 overrides a caller that deliberately bound a
# different tree (ADR-0034 phase 2 step 2d).
if importlib.util.find_spec("erpclaw_lib") is None:
    sys.path.insert(0, os.path.join(os.path.expanduser(
        os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "lib"))

from educlaw_base_schema import ensure_educlaw_base_tables  # noqa: E402
from erpclaw_lib.db import get_connection  # noqa: E402
from erpclaw_lib.seam import (  # noqa: E402
    CheckConstraint, Column, ForeignKey, Index, Integer, MetaData, Table, Text,
    provision, reference_table, table_exists, text,
)

DEFAULT_DB_PATH = os.path.join(os.path.expanduser(os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "data.sqlite")
DISPLAY_NAME = "EduClaw Financial Aid"

# The pre-conversion probe asked for `company` alone. Transcribed, not widened.
REQUIRED_FOUNDATION = ["company"]

METADATA = MetaData()

# Tables this module points at but does not own — the ERPClaw foundation's
# `company` and four of educlaw core's base tables. Declared for foreign key
# resolution only and never created here; `ensure_educlaw_base_tables` below is
# what actually creates the educlaw ones. See `seam.reference_table`.
reference_table("company", METADATA)
reference_table("educlaw_academic_term", METADATA)
reference_table("educlaw_program", METADATA)
reference_table("educlaw_program_enrollment", METADATA)
reference_table("educlaw_student", METADATA)

# ---------------------------------------------------------------------------
# 1. finaid_aid_year (owned by financial_aid)
# ---------------------------------------------------------------------------
AID_YEAR = Table(
    "finaid_aid_year", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("aid_year_code", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("start_date", Text, nullable=False, server_default=text("''")),
    Column("end_date", Text, nullable=False, server_default=text("''")),
    Column("pell_max_award", Text, nullable=False, server_default=text("'0'")),
    Column("is_active", Integer, nullable=False, server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
)

# One aid year per code per company: the code is the key every ISIR, award and
# disbursement is filed under, so a duplicate would split one year's books.
Index("idx_finaid_aid_year_company_code", AID_YEAR.c.company_id,
      AID_YEAR.c.aid_year_code, unique=True)
Index("idx_finaid_aid_year_company_active", AID_YEAR.c.company_id,
      AID_YEAR.c.is_active)

# ---------------------------------------------------------------------------
# 2. finaid_cost_of_attendance (owned by financial_aid)
# ---------------------------------------------------------------------------
COST_OF_ATTENDANCE = Table(
    "finaid_cost_of_attendance", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("program_id", Text,
           ForeignKey("educlaw_program.id", ondelete="RESTRICT")),
    Column("enrollment_status", Text, nullable=False, server_default=text("''")),
    Column("living_arrangement", Text, nullable=False,
           server_default=text("''")),
    Column("tuition_fees", Text, nullable=False, server_default=text("'0'")),
    Column("books_supplies", Text, nullable=False, server_default=text("'0'")),
    Column("room_board", Text, nullable=False, server_default=text("'0'")),
    Column("transportation", Text, nullable=False, server_default=text("'0'")),
    Column("personal_expenses", Text, nullable=False,
           server_default=text("'0'")),
    Column("loan_fees", Text, nullable=False, server_default=text("'0'")),
    Column("total_coa", Text, nullable=False, server_default=text("'0'")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "enrollment_status IN ('full_time','three_quarter','half_time','less_than_half')",
        name="ck_finaid_cost_of_attendance_enrollment_status"),
    CheckConstraint(
        "living_arrangement IN ('on_campus','off_campus','with_parent','')",
        name="ck_finaid_cost_of_attendance_living_arrangement"),
)

Index("idx_finaid_coa_year_program_status_living",
      COST_OF_ATTENDANCE.c.aid_year_id, COST_OF_ATTENDANCE.c.program_id,
      COST_OF_ATTENDANCE.c.enrollment_status,
      COST_OF_ATTENDANCE.c.living_arrangement, unique=True)
Index("idx_finaid_coa_company_year", COST_OF_ATTENDANCE.c.company_id,
      COST_OF_ATTENDANCE.c.aid_year_id)

# ---------------------------------------------------------------------------
# 3. finaid_fund_allocation (owned by financial_aid)
# ---------------------------------------------------------------------------
FUND_ALLOCATION = Table(
    "finaid_fund_allocation", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("fund_type", Text, nullable=False, server_default=text("''")),
    Column("fund_name", Text, nullable=False, server_default=text("''")),
    Column("total_allocation", Text, nullable=False,
           server_default=text("'0'")),
    Column("committed_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("disbursed_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("available_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "fund_type IN ('fseog','fws','institutional_grant','departmental')",
        name="ck_finaid_fund_allocation_fund_type"),
)

Index("idx_finaid_fund_alloc_year_type_name", FUND_ALLOCATION.c.aid_year_id,
      FUND_ALLOCATION.c.fund_type, FUND_ALLOCATION.c.fund_name, unique=True)
Index("idx_finaid_fund_alloc_company_year", FUND_ALLOCATION.c.company_id,
      FUND_ALLOCATION.c.aid_year_id)

# ---------------------------------------------------------------------------
# 4. finaid_isir (owned by financial_aid)
# ---------------------------------------------------------------------------
ISIR = Table(
    "finaid_isir", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("transaction_number", Integer, nullable=False,
           server_default=text("1")),
    Column("is_active_transaction", Integer, nullable=False,
           server_default=text("0")),
    Column("fafsa_submission_id", Text, nullable=False,
           server_default=text("''")),
    Column("receipt_date", Text, nullable=False, server_default=text("''")),
    Column("sai", Text, nullable=False, server_default=text("'0'")),
    Column("sai_is_negative", Integer, nullable=False,
           server_default=text("0")),
    Column("dependency_status", Text, nullable=False,
           server_default=text("''")),
    Column("dependency_override", Integer, nullable=False,
           server_default=text("0")),
    # TEXT here, INTEGER on `finaid_pell_schedule.pell_index`. The asymmetry
    # shipped that way and is transcribed, not tidied.
    Column("pell_index", Text, nullable=False, server_default=text("''")),
    Column("pell_scheduled_award", Text, nullable=False,
           server_default=text("'0'")),
    Column("pell_lifetime_eligibility_used", Text, nullable=False,
           server_default=text("'0'")),
    Column("verification_flag", Integer, nullable=False,
           server_default=text("0")),
    Column("verification_group", Text, nullable=False,
           server_default=text("''")),
    Column("has_unresolved_cflags", Integer, nullable=False,
           server_default=text("0")),
    Column("nslds_default_flag", Integer, nullable=False,
           server_default=text("0")),
    Column("nslds_overpayment_flag", Integer, nullable=False,
           server_default=text("0")),
    Column("selective_service_flag", Integer, nullable=False,
           server_default=text("0")),
    Column("citizenship_flag", Integer, nullable=False,
           server_default=text("0")),
    Column("agi", Text, nullable=False, server_default=text("'0'")),
    Column("household_size", Integer, nullable=False, server_default=text("0")),
    Column("family_members_in_college", Integer, nullable=False,
           server_default=text("0")),
    Column("aggregate_loan_borrowed", Text, nullable=False,
           server_default=text("'0'")),
    Column("aggregate_sub_loan_borrowed", Text, nullable=False,
           server_default=text("'0'")),
    Column("status", Text, nullable=False, server_default=text("'received'")),
    Column("reviewed_by", Text, nullable=False, server_default=text("''")),
    Column("reviewed_at", Text, nullable=False, server_default=text("''")),
    Column("raw_isir_data", Text, nullable=False, server_default=text("'{}'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "dependency_status IN ('dependent','independent','')",
        name="ck_finaid_isir_dependency_status"),
    CheckConstraint(
        "verification_group IN ('V1','V4','V5','')",
        name="ck_finaid_isir_verification_group"),
    CheckConstraint(
        "status IN ('received','under_review','reviewed','packaged','archived')",
        name="ck_finaid_isir_status"),
)

# One ISIR transaction number per student per aid year: transactions are the
# federal record of a FAFSA correction and a duplicate would double-count aid.
Index("idx_finaid_isir_student_year_txn", ISIR.c.student_id,
      ISIR.c.aid_year_id, ISIR.c.transaction_number, unique=True)
Index("idx_finaid_isir_student_year_active", ISIR.c.student_id,
      ISIR.c.aid_year_id, ISIR.c.is_active_transaction)
Index("idx_finaid_isir_company_status", ISIR.c.company_id, ISIR.c.status)

# ---------------------------------------------------------------------------
# 5. finaid_award_package (owned by financial_aid)
# ---------------------------------------------------------------------------
AWARD_PACKAGE = Table(
    "finaid_award_package", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("program_enrollment_id", Text,
           ForeignKey("educlaw_program_enrollment.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("isir_id", Text, ForeignKey("finaid_isir.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("cost_of_attendance_id", Text,
           ForeignKey("finaid_cost_of_attendance.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("enrollment_status", Text, nullable=False, server_default=text("''")),
    Column("financial_need", Text, nullable=False, server_default=text("'0'")),
    Column("total_grants", Text, nullable=False, server_default=text("'0'")),
    Column("total_loans", Text, nullable=False, server_default=text("'0'")),
    Column("total_work_study", Text, nullable=False, server_default=text("'0'")),
    Column("total_aid", Text, nullable=False, server_default=text("'0'")),
    Column("status", Text, nullable=False, server_default=text("'draft'")),
    Column("offered_date", Text, nullable=False, server_default=text("''")),
    Column("accepted_date", Text, nullable=False, server_default=text("''")),
    Column("acceptance_deadline", Text, nullable=False,
           server_default=text("''")),
    Column("packaged_by", Text, nullable=False, server_default=text("''")),
    Column("packaged_at", Text, nullable=False, server_default=text("''")),
    Column("approved_by", Text, nullable=False, server_default=text("''")),
    Column("approved_at", Text, nullable=False, server_default=text("''")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "enrollment_status IN ('full_time','three_quarter','half_time','less_than_half')",
        name="ck_finaid_award_package_enrollment_status"),
    CheckConstraint(
        "status IN ('draft','offered','accepted','partially_accepted','cancelled','disbursed')",
        name="ck_finaid_award_package_status"),
)

Index("idx_finaid_award_pkg_student_year_term", AWARD_PACKAGE.c.student_id,
      AWARD_PACKAGE.c.aid_year_id, AWARD_PACKAGE.c.academic_term_id)
Index("idx_finaid_award_pkg_company_status", AWARD_PACKAGE.c.company_id,
      AWARD_PACKAGE.c.status)
Index("idx_finaid_award_pkg_year_status", AWARD_PACKAGE.c.aid_year_id,
      AWARD_PACKAGE.c.status)
Index("idx_finaid_award_pkg_naming_series", AWARD_PACKAGE.c.naming_series)

# ---------------------------------------------------------------------------
# 6. finaid_award (owned by financial_aid)
# ---------------------------------------------------------------------------
AWARD = Table(
    "finaid_award", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("award_package_id", Text,
           ForeignKey("finaid_award_package.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_type", Text, nullable=False, server_default=text("''")),
    Column("aid_source", Text, nullable=False, server_default=text("''")),
    # No foreign key: the fund source is a scholarship program, a fund
    # allocation or an external sponsor depending on `aid_source`, so the
    # column cannot point at one table. Transcribed as it shipped.
    Column("fund_source_id", Text, nullable=False, server_default=text("''")),
    Column("offered_amount", Text, nullable=False, server_default=text("'0'")),
    Column("accepted_amount", Text, nullable=False, server_default=text("'0'")),
    Column("disbursed_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("acceptance_status", Text, nullable=False,
           server_default=text("'pending'")),
    Column("acceptance_date", Text, nullable=False, server_default=text("''")),
    Column("disbursement_holds", Text, nullable=False,
           server_default=text("'[]'")),
    Column("is_locked", Integer, nullable=False, server_default=text("0")),
    Column("gl_account_id", Text, nullable=False, server_default=text("''")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "aid_type IN ('pell','fseog','subsidized_loan','unsubsidized_loan','plus_loan','parent_plus_loan','fws','institutional_grant','institutional_scholarship','state_grant','external_scholarship','tuition_waiver','teach_grant')",
        name="ck_finaid_award_aid_type"),
    CheckConstraint(
        "aid_source IN ('federal','state','institutional','external')",
        name="ck_finaid_award_aid_source"),
    CheckConstraint(
        "acceptance_status IN ('pending','accepted','declined','partial')",
        name="ck_finaid_award_acceptance_status"),
)

Index("idx_finaid_award_pkg_type", AWARD.c.award_package_id, AWARD.c.aid_type)
Index("idx_finaid_award_student_year_type", AWARD.c.student_id,
      AWARD.c.aid_year_id, AWARD.c.aid_type)
Index("idx_finaid_award_company_type_status", AWARD.c.company_id,
      AWARD.c.aid_type, AWARD.c.acceptance_status)

# ---------------------------------------------------------------------------
# 7. finaid_disbursement (owned by financial_aid) — append-only, no updated_at
# ---------------------------------------------------------------------------
DISBURSEMENT = Table(
    "finaid_disbursement", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("award_id", Text, ForeignKey("finaid_award.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("award_package_id", Text,
           ForeignKey("finaid_award_package.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("disbursement_type", Text, nullable=False,
           server_default=text("'disbursement'")),
    Column("disbursement_number", Integer, nullable=False,
           server_default=text("1")),
    Column("amount", Text, nullable=False, server_default=text("'0'")),
    Column("disbursement_date", Text, nullable=False,
           server_default=text("''")),
    Column("gl_journal_id", Text, nullable=False, server_default=text("''")),
    Column("sales_invoice_id", Text, nullable=False, server_default=text("''")),
    Column("cod_origination_id", Text, nullable=False,
           server_default=text("''")),
    Column("cod_disbursement_id", Text, nullable=False,
           server_default=text("''")),
    Column("cod_status", Text, nullable=False, server_default=text("''")),
    Column("cod_response_date", Text, nullable=False,
           server_default=text("''")),
    Column("is_credit_balance", Integer, nullable=False,
           server_default=text("0")),
    Column("credit_balance_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("credit_balance_date", Text, nullable=False,
           server_default=text("''")),
    Column("credit_balance_returned_date", Text, nullable=False,
           server_default=text("''")),
    Column("disbursed_by", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "disbursement_type IN ('disbursement','reversal','return','post_withdrawal')",
        name="ck_finaid_disbursement_disbursement_type"),
    CheckConstraint(
        "cod_status IN ('pending','reported','acknowledged','rejected','')",
        name="ck_finaid_disbursement_cod_status"),
)

Index("idx_finaid_disbursement_award_num_type", DISBURSEMENT.c.award_id,
      DISBURSEMENT.c.disbursement_number, DISBURSEMENT.c.disbursement_type)
Index("idx_finaid_disbursement_student_date", DISBURSEMENT.c.student_id,
      DISBURSEMENT.c.disbursement_date)
Index("idx_finaid_disbursement_company_cod", DISBURSEMENT.c.company_id,
      DISBURSEMENT.c.cod_status)
Index("idx_finaid_disbursement_company_credit_balance",
      DISBURSEMENT.c.company_id, DISBURSEMENT.c.is_credit_balance,
      DISBURSEMENT.c.credit_balance_returned_date)

# ---------------------------------------------------------------------------
# 8. finaid_isir_cflag (owned by financial_aid)
# ---------------------------------------------------------------------------
ISIR_CFLAG = Table(
    "finaid_isir_cflag", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("isir_id", Text, ForeignKey("finaid_isir.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("cflag_code", Text, nullable=False, server_default=text("''")),
    Column("cflag_description", Text, nullable=False,
           server_default=text("''")),
    Column("blocks_disbursement", Integer, nullable=False,
           server_default=text("1")),
    Column("resolution_status", Text, nullable=False,
           server_default=text("'pending'")),
    Column("resolution_date", Text, nullable=False, server_default=text("''")),
    Column("resolved_by", Text, nullable=False, server_default=text("''")),
    Column("resolution_notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "resolution_status IN ('pending','resolved','waived')",
        name="ck_finaid_isir_cflag_resolution_status"),
)

# One row per C-code per ISIR: a duplicate would let one resolution clear a flag
# that another row still holds against disbursement.
Index("idx_finaid_isir_cflag_isir_code", ISIR_CFLAG.c.isir_id,
      ISIR_CFLAG.c.cflag_code, unique=True)
Index("idx_finaid_isir_cflag_student_status", ISIR_CFLAG.c.student_id,
      ISIR_CFLAG.c.resolution_status)
Index("idx_finaid_isir_cflag_company_status", ISIR_CFLAG.c.company_id,
      ISIR_CFLAG.c.resolution_status)

# ---------------------------------------------------------------------------
# 9. finaid_loan (owned by loan_tracking)
# ---------------------------------------------------------------------------
LOAN = Table(
    "finaid_loan", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("award_id", Text, ForeignKey("finaid_award.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("loan_type", Text, nullable=False, server_default=text("''")),
    Column("loan_period_start", Text, nullable=False,
           server_default=text("''")),
    Column("loan_period_end", Text, nullable=False, server_default=text("''")),
    Column("loan_amount", Text, nullable=False, server_default=text("'0'")),
    Column("first_disbursement_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("second_disbursement_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("origination_fee", Text, nullable=False, server_default=text("'0'")),
    Column("interest_rate", Text, nullable=False, server_default=text("'0'")),
    Column("cod_loan_id", Text, nullable=False, server_default=text("''")),
    Column("cod_origination_status", Text, nullable=False,
           server_default=text("''")),
    Column("cod_origination_date", Text, nullable=False,
           server_default=text("''")),
    Column("mpn_required", Integer, nullable=False, server_default=text("1")),
    Column("mpn_signed", Integer, nullable=False, server_default=text("0")),
    Column("mpn_signed_date", Text, nullable=False, server_default=text("''")),
    Column("entrance_counseling_required", Integer, nullable=False,
           server_default=text("0")),
    Column("entrance_counseling_complete", Integer, nullable=False,
           server_default=text("0")),
    Column("entrance_counseling_date", Text, nullable=False,
           server_default=text("''")),
    Column("exit_counseling_required", Integer, nullable=False,
           server_default=text("0")),
    Column("exit_counseling_complete", Integer, nullable=False,
           server_default=text("0")),
    Column("exit_counseling_date", Text, nullable=False,
           server_default=text("''")),
    Column("borrower_id", Text, nullable=False, server_default=text("''")),
    Column("borrower_type", Text, nullable=False,
           server_default=text("'student'")),
    Column("status", Text, nullable=False, server_default=text("'originated'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "loan_type IN ('subsidized','unsubsidized','graduate_plus','parent_plus','teach')",
        name="ck_finaid_loan_loan_type"),
    CheckConstraint(
        "cod_origination_status IN ('pending','accepted','rejected','')",
        name="ck_finaid_loan_cod_origination_status"),
    CheckConstraint(
        "borrower_type IN ('student','parent')",
        name="ck_finaid_loan_borrower_type"),
    CheckConstraint(
        "status IN ('originated','active','repayment','deferred','defaulted','paid_off','cancelled')",
        name="ck_finaid_loan_status"),
)

Index("idx_finaid_loan_student_year_type", LOAN.c.student_id,
      LOAN.c.aid_year_id, LOAN.c.loan_type)
Index("idx_finaid_loan_company_cod_status", LOAN.c.company_id,
      LOAN.c.cod_origination_status)
Index("idx_finaid_loan_company_mpn_counseling", LOAN.c.company_id,
      LOAN.c.mpn_signed, LOAN.c.entrance_counseling_complete)

# ---------------------------------------------------------------------------
# 10. finaid_pell_schedule (owned by financial_aid)
# ---------------------------------------------------------------------------
PELL_SCHEDULE = Table(
    "finaid_pell_schedule", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    # INTEGER here, TEXT on `finaid_isir.pell_index`. Preserved as it shipped.
    Column("pell_index", Integer, nullable=False, server_default=text("0")),
    Column("full_time_annual", Text, nullable=False, server_default=text("'0'")),
    Column("three_quarter_time", Text, nullable=False,
           server_default=text("'0'")),
    Column("half_time", Text, nullable=False, server_default=text("'0'")),
    Column("less_than_half_time", Text, nullable=False,
           server_default=text("'0'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
)

# One scheduled award row per Pell index per aid year: two rows would make the
# scheduled award ambiguous for every student at that index.
Index("idx_finaid_pell_schedule_year_index", PELL_SCHEDULE.c.aid_year_id,
      PELL_SCHEDULE.c.pell_index, unique=True)

# ---------------------------------------------------------------------------
# 11. finaid_professional_judgment (owned by financial_aid)
#     append-only, no updated_at
# ---------------------------------------------------------------------------
PROFESSIONAL_JUDGMENT = Table(
    "finaid_professional_judgment", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("award_package_id", Text,
           ForeignKey("finaid_award_package.id", ondelete="RESTRICT")),
    Column("pj_type", Text, nullable=False, server_default=text("''")),
    Column("pj_reason", Text, nullable=False, server_default=text("''")),
    Column("reason_narrative", Text, nullable=False, server_default=text("''")),
    Column("data_element_changed", Text, nullable=False,
           server_default=text("''")),
    Column("original_value", Text, nullable=False, server_default=text("''")),
    Column("adjusted_value", Text, nullable=False, server_default=text("''")),
    Column("effective_date", Text, nullable=False, server_default=text("''")),
    Column("supporting_documentation", Text, nullable=False,
           server_default=text("'[]'")),
    Column("authorized_by", Text, nullable=False, server_default=text("''")),
    Column("authorization_date", Text, nullable=False,
           server_default=text("''")),
    Column("supervisor_review_required", Integer, nullable=False,
           server_default=text("0")),
    Column("supervisor_reviewed_by", Text, nullable=False,
           server_default=text("''")),
    Column("supervisor_review_date", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "pj_type IN ('sai_adjustment','coa_adjustment','dependency_override','enrollment_status_override','other')",
        name="ck_finaid_professional_judgment_pj_type"),
    CheckConstraint(
        "pj_reason IN ('job_loss','death_family','illness_injury','divorce_separation','unusual_expenses','natural_disaster','other')",
        name="ck_finaid_professional_judgment_pj_reason"),
)

Index("idx_finaid_pj_student_year_type", PROFESSIONAL_JUDGMENT.c.student_id,
      PROFESSIONAL_JUDGMENT.c.aid_year_id, PROFESSIONAL_JUDGMENT.c.pj_type)
Index("idx_finaid_pj_company_auth_date", PROFESSIONAL_JUDGMENT.c.company_id,
      PROFESSIONAL_JUDGMENT.c.authorization_date)

# ---------------------------------------------------------------------------
# 12. finaid_r2t4_calculation (owned by financial_aid)
# ---------------------------------------------------------------------------
R2T4_CALCULATION = Table(
    "finaid_r2t4_calculation", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("award_package_id", Text,
           ForeignKey("finaid_award_package.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("withdrawal_type", Text, nullable=False, server_default=text("''")),
    Column("withdrawal_date", Text, nullable=False, server_default=text("''")),
    Column("last_date_of_attendance", Text, nullable=False,
           server_default=text("''")),
    Column("determination_date", Text, nullable=False,
           server_default=text("''")),
    Column("payment_period_start", Text, nullable=False,
           server_default=text("''")),
    Column("payment_period_end", Text, nullable=False,
           server_default=text("''")),
    Column("payment_period_days", Integer, nullable=False,
           server_default=text("0")),
    Column("days_attended", Integer, nullable=False, server_default=text("0")),
    Column("percent_completed", Text, nullable=False,
           server_default=text("'0'")),
    Column("earned_percent", Text, nullable=False, server_default=text("'0'")),
    Column("total_aid_disbursed", Text, nullable=False,
           server_default=text("'0'")),
    Column("total_aid_scheduleable", Text, nullable=False,
           server_default=text("'0'")),
    Column("earned_aid", Text, nullable=False, server_default=text("'0'")),
    Column("unearned_aid", Text, nullable=False, server_default=text("'0'")),
    Column("institution_return_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("student_return_amount", Text, nullable=False,
           server_default=text("'0'")),
    Column("post_withdrawal_disbursement", Text, nullable=False,
           server_default=text("'0'")),
    Column("pwd_offered_date", Text, nullable=False, server_default=text("''")),
    Column("pwd_accepted", Integer, nullable=False, server_default=text("0")),
    Column("pwd_disbursed_date", Text, nullable=False,
           server_default=text("''")),
    Column("institution_return_due_date", Text, nullable=False,
           server_default=text("''")),
    Column("institution_return_date", Text, nullable=False,
           server_default=text("''")),
    Column("return_detail", Text, nullable=False, server_default=text("'{}'")),
    Column("status", Text, nullable=False, server_default=text("'calculated'")),
    Column("calculated_by", Text, nullable=False, server_default=text("''")),
    Column("approved_by", Text, nullable=False, server_default=text("''")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "withdrawal_type IN ('official','unofficial')",
        name="ck_finaid_r2t4_calculation_withdrawal_type"),
    CheckConstraint(
        "status IN ('calculated','approved','returned','complete')",
        name="ck_finaid_r2t4_calculation_status"),
)

Index("idx_finaid_r2t4_student_term", R2T4_CALCULATION.c.student_id,
      R2T4_CALCULATION.c.academic_term_id)
Index("idx_finaid_r2t4_company_status", R2T4_CALCULATION.c.company_id,
      R2T4_CALCULATION.c.status)
Index("idx_finaid_r2t4_company_due_date_status", R2T4_CALCULATION.c.company_id,
      R2T4_CALCULATION.c.institution_return_due_date,
      R2T4_CALCULATION.c.status)

# ---------------------------------------------------------------------------
# 13. finaid_sap_evaluation (owned by financial_aid)
# ---------------------------------------------------------------------------
SAP_EVALUATION = Table(
    "finaid_sap_evaluation", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("evaluation_date", Text, nullable=False, server_default=text("''")),
    Column("evaluation_type", Text, nullable=False,
           server_default=text("'automatic'")),
    Column("gpa_earned", Text, nullable=False, server_default=text("'0'")),
    Column("gpa_threshold", Text, nullable=False, server_default=text("'2.00'")),
    Column("gpa_meets_standard", Integer, nullable=False,
           server_default=text("0")),
    Column("credits_attempted", Text, nullable=False,
           server_default=text("'0'")),
    Column("credits_completed", Text, nullable=False,
           server_default=text("'0'")),
    Column("completion_rate", Text, nullable=False, server_default=text("'0'")),
    Column("completion_threshold", Text, nullable=False,
           server_default=text("'0.67'")),
    Column("completion_meets_standard", Integer, nullable=False,
           server_default=text("0")),
    Column("max_timeframe_credits", Text, nullable=False,
           server_default=text("'0'")),
    Column("projected_credits_remaining", Text, nullable=False,
           server_default=text("'0'")),
    Column("max_timeframe_met", Integer, nullable=False,
           server_default=text("0")),
    Column("transfer_credits_attempted", Text, nullable=False,
           server_default=text("'0'")),
    Column("transfer_credits_completed", Text, nullable=False,
           server_default=text("'0'")),
    Column("sap_status", Text, nullable=False, server_default=text("'SAT'")),
    Column("prior_sap_status", Text, nullable=False, server_default=text("''")),
    Column("holds_placed", Integer, nullable=False, server_default=text("0")),
    Column("evaluated_by", Text, nullable=False, server_default=text("''")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "evaluation_type IN ('automatic','manual','appeal')",
        name="ck_finaid_sap_evaluation_evaluation_type"),
    CheckConstraint(
        "sap_status IN ('SAT','FAW','FSP','FAP')",
        name="ck_finaid_sap_evaluation_sap_status"),
)

Index("idx_finaid_sap_eval_student_term", SAP_EVALUATION.c.student_id,
      SAP_EVALUATION.c.academic_term_id)
Index("idx_finaid_sap_eval_company_status", SAP_EVALUATION.c.company_id,
      SAP_EVALUATION.c.sap_status)
Index("idx_finaid_sap_eval_term_status", SAP_EVALUATION.c.academic_term_id,
      SAP_EVALUATION.c.sap_status)

# ---------------------------------------------------------------------------
# 14. finaid_sap_appeal (owned by financial_aid)
# ---------------------------------------------------------------------------
SAP_APPEAL = Table(
    "finaid_sap_appeal", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("sap_evaluation_id", Text,
           ForeignKey("finaid_sap_evaluation.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("submitted_date", Text, nullable=False, server_default=text("''")),
    Column("appeal_reason", Text, nullable=False, server_default=text("''")),
    Column("reason_narrative", Text, nullable=False, server_default=text("''")),
    Column("academic_plan", Text, nullable=False, server_default=text("''")),
    Column("supporting_documents", Text, nullable=False,
           server_default=text("'[]'")),
    Column("status", Text, nullable=False, server_default=text("'submitted'")),
    Column("reviewed_by", Text, nullable=False, server_default=text("''")),
    Column("reviewed_date", Text, nullable=False, server_default=text("''")),
    Column("decision_rationale", Text, nullable=False,
           server_default=text("''")),
    Column("probation_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT")),
    Column("probation_conditions", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "appeal_reason IN ('death_family','illness','injury','divorce_separation','natural_disaster','other')",
        name="ck_finaid_sap_appeal_appeal_reason"),
    CheckConstraint(
        "status IN ('submitted','under_review','granted','denied')",
        name="ck_finaid_sap_appeal_status"),
)

Index("idx_finaid_sap_appeal_student_status", SAP_APPEAL.c.student_id,
      SAP_APPEAL.c.status)
Index("idx_finaid_sap_appeal_evaluation", SAP_APPEAL.c.sap_evaluation_id)
Index("idx_finaid_sap_appeal_company_status", SAP_APPEAL.c.company_id,
      SAP_APPEAL.c.status)

# ---------------------------------------------------------------------------
# 15. finaid_scholarship_program (owned by scholarships)
# ---------------------------------------------------------------------------
SCHOLARSHIP_PROGRAM = Table(
    "finaid_scholarship_program", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("code", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("scholarship_type", Text, nullable=False,
           server_default=text("''")),
    Column("funding_source", Text, nullable=False, server_default=text("''")),
    Column("award_method", Text, nullable=False, server_default=text("''")),
    Column("award_amount_type", Text, nullable=False,
           server_default=text("''")),
    Column("award_amount", Text, nullable=False, server_default=text("'0'")),
    Column("min_award", Text, nullable=False, server_default=text("'0'")),
    Column("max_award", Text, nullable=False, server_default=text("'0'")),
    Column("annual_budget", Text, nullable=False, server_default=text("'0'")),
    Column("budget_remaining", Text, nullable=False,
           server_default=text("'0'")),
    Column("max_recipients", Integer, nullable=False, server_default=text("0")),
    Column("renewal_eligible", Integer, nullable=False,
           server_default=text("0")),
    Column("renewal_gpa_minimum", Text, nullable=False,
           server_default=text("'0'")),
    Column("renewal_credits_minimum", Text, nullable=False,
           server_default=text("'0'")),
    Column("eligibility_criteria", Text, nullable=False,
           server_default=text("'{}'")),
    Column("application_deadline", Text, nullable=False,
           server_default=text("''")),
    Column("award_period", Text, nullable=False, server_default=text("''")),
    Column("applies_to_aid_type", Text, nullable=False,
           server_default=text("''")),
    Column("gl_account_id", Text, nullable=False, server_default=text("''")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "scholarship_type IN ('merit','need_based','merit_need','athletic','departmental','endowed','external','tuition_waiver')",
        name="ck_finaid_scholarship_program_scholarship_type"),
    CheckConstraint(
        "funding_source IN ('endowment','budget','departmental','donor','external')",
        name="ck_finaid_scholarship_program_funding_source"),
    CheckConstraint(
        "award_method IN ('auto_match','application_required','fao_discretion')",
        name="ck_finaid_scholarship_program_award_method"),
    CheckConstraint(
        "award_amount_type IN ('fixed','percentage_coa','percentage_tuition','variable')",
        name="ck_finaid_scholarship_program_award_amount_type"),
    CheckConstraint(
        "award_period IN ('annual','per_term','one_time')",
        name="ck_finaid_scholarship_program_award_period"),
    CheckConstraint(
        "applies_to_aid_type IN ('institutional_grant','institutional_scholarship','tuition_waiver')",
        name="ck_finaid_scholarship_program_applies_to_aid_type"),
)

Index("idx_finaid_schol_prog_company_code", SCHOLARSHIP_PROGRAM.c.company_id,
      SCHOLARSHIP_PROGRAM.c.code)
Index("idx_finaid_schol_prog_company_type_active",
      SCHOLARSHIP_PROGRAM.c.company_id,
      SCHOLARSHIP_PROGRAM.c.scholarship_type, SCHOLARSHIP_PROGRAM.c.is_active)

# ---------------------------------------------------------------------------
# 16. finaid_scholarship_application (owned by scholarships)
# ---------------------------------------------------------------------------
SCHOLARSHIP_APPLICATION = Table(
    "finaid_scholarship_application", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("scholarship_program_id", Text,
           ForeignKey("finaid_scholarship_program.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("submission_date", Text, nullable=False, server_default=text("''")),
    Column("status", Text, nullable=False, server_default=text("'draft'")),
    Column("essay_response", Text, nullable=False, server_default=text("''")),
    Column("gpa_at_application", Text, nullable=False,
           server_default=text("'0'")),
    Column("reviewer_id", Text, nullable=False, server_default=text("''")),
    Column("review_date", Text, nullable=False, server_default=text("''")),
    Column("review_notes", Text, nullable=False, server_default=text("''")),
    Column("award_amount", Text, nullable=False, server_default=text("'0'")),
    Column("award_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT")),
    Column("denial_reason", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "status IN ('draft','submitted','under_review','awarded','waitlisted','denied','withdrawn')",
        name="ck_finaid_scholarship_application_status"),
)

Index("idx_finaid_schol_app_prog_student_year",
      SCHOLARSHIP_APPLICATION.c.scholarship_program_id,
      SCHOLARSHIP_APPLICATION.c.student_id,
      SCHOLARSHIP_APPLICATION.c.aid_year_id)
Index("idx_finaid_schol_app_company_status",
      SCHOLARSHIP_APPLICATION.c.company_id, SCHOLARSHIP_APPLICATION.c.status)
Index("idx_finaid_schol_app_student_status",
      SCHOLARSHIP_APPLICATION.c.student_id, SCHOLARSHIP_APPLICATION.c.status)

# ---------------------------------------------------------------------------
# 17. finaid_scholarship_renewal (owned by scholarships)
# ---------------------------------------------------------------------------
SCHOLARSHIP_RENEWAL = Table(
    "finaid_scholarship_renewal", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("scholarship_application_id", Text,
           ForeignKey("finaid_scholarship_application.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("scholarship_program_id", Text,
           ForeignKey("finaid_scholarship_program.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("renewal_status", Text, nullable=False,
           server_default=text("'renewed'")),
    Column("gpa_at_evaluation", Text, nullable=False,
           server_default=text("'0'")),
    # INTEGER here, TEXT on `finaid_sap_evaluation.credits_attempted`. Both
    # shipped that way; transcribed rather than reconciled.
    Column("credits_attempted", Integer, nullable=False,
           server_default=text("0")),
    Column("meets_criteria", Integer, nullable=False, server_default=text("0")),
    Column("reason", Text, nullable=False, server_default=text("''")),
    Column("evaluated_by", Text, nullable=False, server_default=text("''")),
    Column("evaluation_date", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "renewal_status IN ('renewed','suspended','revoked','exhausted')",
        name="ck_finaid_scholarship_renewal_renewal_status"),
)

Index("idx_finaid_schol_renewal_app_term",
      SCHOLARSHIP_RENEWAL.c.scholarship_application_id,
      SCHOLARSHIP_RENEWAL.c.academic_term_id)
Index("idx_finaid_schol_renewal_student_status",
      SCHOLARSHIP_RENEWAL.c.student_id, SCHOLARSHIP_RENEWAL.c.renewal_status)

# ---------------------------------------------------------------------------
# 18. finaid_verification_request (owned by financial_aid)
# ---------------------------------------------------------------------------
VERIFICATION_REQUEST = Table(
    "finaid_verification_request", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("isir_id", Text, ForeignKey("finaid_isir.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("verification_group", Text, nullable=False,
           server_default=text("''")),
    Column("status", Text, nullable=False, server_default=text("'initiated'")),
    Column("requested_date", Text, nullable=False, server_default=text("''")),
    Column("deadline_date", Text, nullable=False, server_default=text("''")),
    Column("completed_date", Text, nullable=False, server_default=text("''")),
    Column("discrepancy_found", Integer, nullable=False,
           server_default=text("0")),
    Column("discrepancy_notes", Text, nullable=False,
           server_default=text("''")),
    Column("assigned_to", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "verification_group IN ('V1','V4','V5')",
        name="ck_finaid_verification_request_verification_group"),
    CheckConstraint(
        "status IN ('initiated','documents_requested','in_review','discrepancy','complete','withdrawn')",
        name="ck_finaid_verification_request_status"),
)

# One verification request per ISIR — the request IS the ISIR's verification
# state, and a second row would let one be completed while the other blocks.
Index("idx_finaid_verif_req_isir", VERIFICATION_REQUEST.c.isir_id, unique=True)
Index("idx_finaid_verif_req_student_status", VERIFICATION_REQUEST.c.student_id,
      VERIFICATION_REQUEST.c.status)
Index("idx_finaid_verif_req_company_status", VERIFICATION_REQUEST.c.company_id,
      VERIFICATION_REQUEST.c.status)

# ---------------------------------------------------------------------------
# 19. finaid_verification_document (owned by financial_aid)
# ---------------------------------------------------------------------------
VERIFICATION_DOCUMENT = Table(
    "finaid_verification_document", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("verification_request_id", Text,
           ForeignKey("finaid_verification_request.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("document_type", Text, nullable=False, server_default=text("''")),
    Column("document_description", Text, nullable=False,
           server_default=text("''")),
    Column("is_required", Integer, nullable=False, server_default=text("1")),
    Column("submission_status", Text, nullable=False,
           server_default=text("'not_submitted'")),
    Column("submitted_date", Text, nullable=False, server_default=text("''")),
    Column("reviewed_by", Text, nullable=False, server_default=text("''")),
    Column("reviewed_date", Text, nullable=False, server_default=text("''")),
    Column("rejection_reason", Text, nullable=False, server_default=text("''")),
    Column("document_reference", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "document_type IN ('tax_transcript','w2','household_verification','identity','statement_of_purpose','snap_verification','child_support','hs_completion','other')",
        name="ck_finaid_verification_document_document_type"),
    CheckConstraint(
        "submission_status IN ('not_submitted','submitted','accepted','rejected','waived')",
        name="ck_finaid_verification_document_submission_status"),
)

# One document of a given type per request: duplicates would let a rejected
# copy and an accepted copy of the same tax transcript coexist.
Index("idx_finaid_verif_doc_req_type",
      VERIFICATION_DOCUMENT.c.verification_request_id,
      VERIFICATION_DOCUMENT.c.document_type, unique=True)
Index("idx_finaid_verif_doc_student_status", VERIFICATION_DOCUMENT.c.student_id,
      VERIFICATION_DOCUMENT.c.submission_status)
Index("idx_finaid_verif_doc_company_status", VERIFICATION_DOCUMENT.c.company_id,
      VERIFICATION_DOCUMENT.c.submission_status)

# ---------------------------------------------------------------------------
# 20. finaid_work_study_job (owned by work_study)
# ---------------------------------------------------------------------------
WORK_STUDY_JOB = Table(
    "finaid_work_study_job", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("job_title", Text, nullable=False, server_default=text("''")),
    # No foreign key on either party: the shipped DDL leaves department and
    # supervisor as free identifiers. Preserved, not tightened.
    Column("department_id", Text, nullable=False, server_default=text("''")),
    Column("supervisor_id", Text, nullable=False, server_default=text("''")),
    Column("job_type", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("pay_rate", Text, nullable=False, server_default=text("'0'")),
    Column("hours_per_week", Text, nullable=False, server_default=text("'0'")),
    Column("total_positions", Integer, nullable=False,
           server_default=text("1")),
    Column("filled_positions", Integer, nullable=False,
           server_default=text("0")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("status", Text, nullable=False, server_default=text("'open'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "job_type IN ('on_campus','off_campus_community','off_campus_other')",
        name="ck_finaid_work_study_job_job_type"),
    CheckConstraint(
        "status IN ('open','filled','closed')",
        name="ck_finaid_work_study_job_status"),
)

Index("idx_finaid_ws_job_company_year_status", WORK_STUDY_JOB.c.company_id,
      WORK_STUDY_JOB.c.aid_year_id, WORK_STUDY_JOB.c.status)
Index("idx_finaid_ws_job_company_type", WORK_STUDY_JOB.c.company_id,
      WORK_STUDY_JOB.c.job_type)

# ---------------------------------------------------------------------------
# 21. finaid_work_study_assignment (owned by work_study)
# ---------------------------------------------------------------------------
WORK_STUDY_ASSIGNMENT = Table(
    "finaid_work_study_assignment", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("award_id", Text, ForeignKey("finaid_award.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("job_id", Text,
           ForeignKey("finaid_work_study_job.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("aid_year_id", Text,
           ForeignKey("finaid_aid_year.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("start_date", Text, nullable=False, server_default=text("''")),
    Column("end_date", Text, nullable=False, server_default=text("''")),
    Column("award_limit", Text, nullable=False, server_default=text("'0'")),
    Column("earned_to_date", Text, nullable=False, server_default=text("'0'")),
    Column("status", Text, nullable=False, server_default=text("'active'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "status IN ('active','completed','terminated')",
        name="ck_finaid_work_study_assignment_status"),
)

Index("idx_finaid_ws_assign_student_year_status",
      WORK_STUDY_ASSIGNMENT.c.student_id, WORK_STUDY_ASSIGNMENT.c.aid_year_id,
      WORK_STUDY_ASSIGNMENT.c.status)
Index("idx_finaid_ws_assign_job_status", WORK_STUDY_ASSIGNMENT.c.job_id,
      WORK_STUDY_ASSIGNMENT.c.status)
Index("idx_finaid_ws_assign_company_term_status",
      WORK_STUDY_ASSIGNMENT.c.company_id,
      WORK_STUDY_ASSIGNMENT.c.academic_term_id, WORK_STUDY_ASSIGNMENT.c.status)

# ---------------------------------------------------------------------------
# 22. finaid_work_study_timesheet (owned by work_study)
# ---------------------------------------------------------------------------
WORK_STUDY_TIMESHEET = Table(
    "finaid_work_study_timesheet", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("assignment_id", Text,
           ForeignKey("finaid_work_study_assignment.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("pay_period_start", Text, nullable=False, server_default=text("''")),
    Column("pay_period_end", Text, nullable=False, server_default=text("''")),
    Column("hours_worked", Text, nullable=False, server_default=text("'0'")),
    Column("earnings", Text, nullable=False, server_default=text("'0'")),
    Column("cumulative_earnings", Text, nullable=False,
           server_default=text("'0'")),
    Column("submission_date", Text, nullable=False, server_default=text("''")),
    Column("supervisor_approval_status", Text, nullable=False,
           server_default=text("'pending'")),
    Column("supervisor_approved_by", Text, nullable=False,
           server_default=text("''")),
    Column("supervisor_approved_date", Text, nullable=False,
           server_default=text("''")),
    Column("rejection_reason", Text, nullable=False, server_default=text("''")),
    Column("payroll_exported", Integer, nullable=False,
           server_default=text("0")),
    Column("payroll_export_date", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "supervisor_approval_status IN ('pending','approved','rejected')",
        name="ck_finaid_work_study_timesheet_supervisor_approval_status"),
)

Index("idx_finaid_ws_timesheet_assign_period",
      WORK_STUDY_TIMESHEET.c.assignment_id,
      WORK_STUDY_TIMESHEET.c.pay_period_start)
Index("idx_finaid_ws_timesheet_student_period",
      WORK_STUDY_TIMESHEET.c.student_id,
      WORK_STUDY_TIMESHEET.c.pay_period_start)
Index("idx_finaid_ws_timesheet_company_approval",
      WORK_STUDY_TIMESHEET.c.company_id,
      WORK_STUDY_TIMESHEET.c.supervisor_approval_status)


def _require_foundation(db_path):
    """Refuse to install onto a database with no ERPClaw foundation.

    Same check and same message as before the conversion; the pre-conversion
    version read `sqlite_master` directly, which is a hard error on PostgreSQL
    rather than a false, so it is asked through the seam instead.
    """
    missing = [t for t in REQUIRED_FOUNDATION if not table_exists(t, db_path)]
    if missing:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)


def create_educlaw_finaid_tables(db_path):
    """Create the financial aid tables and indexes on whichever backend is configured.

    Same contract as before the ADR-0034 conversion: the shared educlaw base
    tables are ensured first, then this module's own 22. Idempotent, and the
    returned counts are what was ACTUALLY created rather than what was declared —
    so they count the 22 owned tables, never educlaw core's 32.
    """
    _require_foundation(db_path)

    # educlaw core's base schema, created here because a sub-vertical can be
    # installed before its parent. Another module's installer is not this
    # conversion's to rewrite, so it keeps running exactly as it does today.
    conn = get_connection(db_path)
    try:
        ensure_educlaw_base_tables(conn)
        conn.commit()
    finally:
        conn.close()

    result = provision(METADATA, db_path)
    return {
        "database": db_path,
        "tables": result["tables"],
        "indexes": result["indexes"],
    }


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    result = create_educlaw_finaid_tables(db_path)
    print(f"{DISPLAY_NAME} schema created in {result['database']}")
    print(f"  Tables: {result['tables']}")
    print(f"  Indexes: {result['indexes']}")
