#!/usr/bin/env python3
"""EduClaw Advanced Scheduling schema — 41 tables (32 parent + 9 new), 121 indexes.

Sub-vertical of educlaw | New tables: 9 | Domains: schedule_patterns,
master_schedule, conflict_resolution, room_assignment

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to restore section_meeting_id_b FK
(generator limitation with same-table double refs — same pattern as educlaw
 prerequisite_course_id fix).
Parent: educlaw | Tables: 41 | Indexes: 121

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-scheduling (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]
"""
import os
import sqlite3
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from educlaw_base_schema import ensure_educlaw_base_tables


DEFAULT_DB_PATH = os.path.expanduser("~/.openclaw/erpclaw/data.sqlite")


def create_educlaw_scheduling_tables(db_path):
    conn = sqlite3.connect(db_path)
    from erpclaw_lib.db import setup_pragmas
    setup_pragmas(conn)

    # Verify foundation exists
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()]
    if "company" not in tables:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)

    # Ensure parent schema (educlaw base tables) exists
    ensure_educlaw_base_tables(conn)


    conn.executescript("""
        -- ==========================================================
        -- EduClaw Domain Tables
        -- Generated by ERPForge Schema DSL
        -- Tables: 9 | Columns: 142
        -- ==========================================================

        -- educlaw_course_request (owned by master_schedule)
        CREATE TABLE IF NOT EXISTS educlaw_course_request (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL DEFAULT '' UNIQUE,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            academic_term_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            course_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            request_priority INTEGER NOT NULL DEFAULT 1,
            is_alternate INTEGER NOT NULL DEFAULT 0 CHECK(is_alternate IN (0, 1)),
            alternate_for_course_id TEXT REFERENCES educlaw_course(id) ON DELETE RESTRICT,
            request_status TEXT NOT NULL DEFAULT 'submitted' CHECK(request_status IN ('draft','submitted','approved','scheduled','alternate_used','unfulfilled','withdrawn')),
            fulfilled_section_id TEXT REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            prerequisite_override INTEGER NOT NULL DEFAULT 0 CHECK(prerequisite_override IN (0, 1)),
            prerequisite_override_by TEXT NOT NULL DEFAULT '',
            prerequisite_override_note TEXT NOT NULL DEFAULT '',
            has_iep_flag INTEGER NOT NULL DEFAULT 0 CHECK(has_iep_flag IN (0, 1)),
            submitted_by TEXT NOT NULL DEFAULT '',
            approved_by TEXT NOT NULL DEFAULT '',
            approved_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_course_request_student_term_course UNIQUE (student_id, academic_term_id, course_id)
        );

        -- educlaw_schedule_pattern (owned by schedule_patterns)
        CREATE TABLE IF NOT EXISTS educlaw_schedule_pattern (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            pattern_type TEXT NOT NULL DEFAULT '' CHECK(pattern_type IN ('traditional','block_4x4','block_ab','trimester','rotating_drop','semester','custom')),
            cycle_days INTEGER NOT NULL DEFAULT 1 CHECK(cycle_days >= 1),
            total_periods_per_cycle INTEGER NOT NULL DEFAULT 0,
            notes TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_bell_period (owned by schedule_patterns)
        CREATE TABLE IF NOT EXISTS educlaw_bell_period (
            id TEXT PRIMARY KEY,
            schedule_pattern_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_schedule_pattern(id) ON DELETE RESTRICT,
            period_number TEXT NOT NULL DEFAULT '',
            period_name TEXT NOT NULL DEFAULT '',
            start_time TEXT NOT NULL DEFAULT '',
            end_time TEXT NOT NULL DEFAULT '',
            duration_minutes INTEGER NOT NULL DEFAULT 0 CHECK(duration_minutes > 0),
            period_type TEXT NOT NULL DEFAULT 'class' CHECK(period_type IN ('class','break','lunch','homeroom','advisory','flex','passing')),
            applies_to_day_types TEXT NOT NULL DEFAULT '[]',
            sort_order INTEGER NOT NULL DEFAULT 0,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_bell_period_pattern_number UNIQUE (schedule_pattern_id, period_number)
        );

        -- educlaw_day_type (owned by schedule_patterns)
        CREATE TABLE IF NOT EXISTS educlaw_day_type (
            id TEXT PRIMARY KEY,
            schedule_pattern_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_schedule_pattern(id) ON DELETE RESTRICT,
            code TEXT NOT NULL DEFAULT '',
            name TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 0 CHECK(sort_order >= 0),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_day_type_pattern_code UNIQUE (schedule_pattern_id, code)
        );

        -- educlaw_instructor_constraint (owned by room_assignment)
        CREATE TABLE IF NOT EXISTS educlaw_instructor_constraint (
            id TEXT PRIMARY KEY,
            instructor_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_instructor(id) ON DELETE RESTRICT,
            academic_term_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            constraint_type TEXT NOT NULL DEFAULT '' CHECK(constraint_type IN ('unavailable','preferred','max_periods_per_day','max_consecutive_periods','requires_prep_period','preferred_building')),
            day_type_id TEXT REFERENCES educlaw_day_type(id) ON DELETE RESTRICT,
            bell_period_id TEXT REFERENCES educlaw_bell_period(id) ON DELETE RESTRICT,
            constraint_value INTEGER NOT NULL DEFAULT 0,
            constraint_notes TEXT NOT NULL DEFAULT '',
            priority TEXT NOT NULL DEFAULT 'preference' CHECK(priority IN ('hard','soft','preference')),
            is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_master_schedule (owned by master_schedule)
        CREATE TABLE IF NOT EXISTS educlaw_master_schedule (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL DEFAULT '' UNIQUE,
            name TEXT NOT NULL DEFAULT '',
            academic_term_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT UNIQUE,
            schedule_pattern_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_schedule_pattern(id) ON DELETE RESTRICT,
            build_notes TEXT NOT NULL DEFAULT '',
            total_sections INTEGER NOT NULL DEFAULT 0,
            sections_placed INTEGER NOT NULL DEFAULT 0,
            sections_with_room INTEGER NOT NULL DEFAULT 0,
            open_conflicts INTEGER NOT NULL DEFAULT 0,
            fulfillment_rate TEXT NOT NULL DEFAULT '',
            schedule_status TEXT NOT NULL DEFAULT 'draft' CHECK(schedule_status IN ('draft','building','review','published','locked','archived')),
            published_at TEXT NOT NULL DEFAULT '',
            published_by TEXT NOT NULL DEFAULT '',
            locked_at TEXT NOT NULL DEFAULT '',
            locked_by TEXT NOT NULL DEFAULT '',
            cloned_from_id TEXT REFERENCES educlaw_master_schedule(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_section_meeting (owned by master_schedule)
        CREATE TABLE IF NOT EXISTS educlaw_section_meeting (
            id TEXT PRIMARY KEY,
            section_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            master_schedule_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_master_schedule(id) ON DELETE RESTRICT,
            day_type_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_day_type(id) ON DELETE RESTRICT,
            bell_period_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_bell_period(id) ON DELETE RESTRICT,
            room_id TEXT REFERENCES educlaw_room(id) ON DELETE RESTRICT,
            instructor_id TEXT REFERENCES educlaw_instructor(id) ON DELETE RESTRICT,
            meeting_type TEXT NOT NULL DEFAULT 'regular' CHECK(meeting_type IN ('regular','lab','exam','field_trip','make_up')),
            meeting_mode TEXT NOT NULL DEFAULT 'in_person' CHECK(meeting_mode IN ('in_person','hybrid','online')),
            is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
            notes TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_section_meeting_slot UNIQUE (section_id, day_type_id, bell_period_id)
        );

        -- educlaw_room_booking (owned by room_assignment)
        CREATE TABLE IF NOT EXISTS educlaw_room_booking (
            id TEXT PRIMARY KEY,
            room_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_room(id) ON DELETE RESTRICT,
            master_schedule_id TEXT REFERENCES educlaw_master_schedule(id) ON DELETE RESTRICT,
            section_meeting_id TEXT REFERENCES educlaw_section_meeting(id) ON DELETE RESTRICT,
            day_type_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_day_type(id) ON DELETE RESTRICT,
            bell_period_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_bell_period(id) ON DELETE RESTRICT,
            booking_type TEXT NOT NULL DEFAULT 'class' CHECK(booking_type IN ('class','exam','event','maintenance','admin','other')),
            booking_title TEXT NOT NULL DEFAULT '',
            booked_by TEXT NOT NULL DEFAULT '',
            booking_status TEXT NOT NULL DEFAULT 'confirmed' CHECK(booking_status IN ('confirmed','tentative','cancelled')),
            cancellation_reason TEXT NOT NULL DEFAULT '',
            accessibility_required INTEGER NOT NULL DEFAULT 0 CHECK(accessibility_required IN (0, 1)),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_schedule_conflict (owned by conflict_resolution)
        CREATE TABLE IF NOT EXISTS educlaw_schedule_conflict (
            id TEXT PRIMARY KEY,
            master_schedule_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_master_schedule(id) ON DELETE RESTRICT,
            conflict_type TEXT NOT NULL DEFAULT '' CHECK(conflict_type IN ('instructor_double_booking','room_double_booking','student_conflict','instructor_overload','instructor_contract_violation','capacity_exceeded','room_type_mismatch','credential_mismatch','singleton_overlap','contact_hours_deficit','room_shortage')),
            severity TEXT NOT NULL DEFAULT 'high' CHECK(severity IN ('critical','high','medium','low')),
            section_meeting_id_a TEXT REFERENCES educlaw_section_meeting(id) ON DELETE RESTRICT,
            section_meeting_id_b TEXT REFERENCES educlaw_section_meeting(id) ON DELETE RESTRICT,
            instructor_id TEXT REFERENCES educlaw_instructor(id) ON DELETE RESTRICT,
            room_id TEXT REFERENCES educlaw_room(id) ON DELETE RESTRICT,
            student_id TEXT REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            description TEXT NOT NULL DEFAULT '',
            conflict_status TEXT NOT NULL DEFAULT 'open' CHECK(conflict_status IN ('open','resolving','resolved','accepted','superseded')),
            resolution_notes TEXT NOT NULL DEFAULT '',
            resolved_by TEXT NOT NULL DEFAULT '',
            resolved_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- ==========================================================
        -- Indexes
        -- ==========================================================

        CREATE INDEX IF NOT EXISTS idx_course_request_student_term_course ON educlaw_course_request(student_id, academic_term_id, course_id);
        CREATE INDEX IF NOT EXISTS idx_course_request_term_course_status ON educlaw_course_request(academic_term_id, course_id, request_status);
        CREATE INDEX IF NOT EXISTS idx_course_request_student_term ON educlaw_course_request(student_id, academic_term_id, request_status);
        CREATE INDEX IF NOT EXISTS idx_course_request_term_status ON educlaw_course_request(academic_term_id, request_status);
        CREATE INDEX IF NOT EXISTS idx_course_request_series ON educlaw_course_request(naming_series);
        CREATE INDEX IF NOT EXISTS idx_schedule_pattern_company_type ON educlaw_schedule_pattern(company_id, pattern_type);
        CREATE INDEX IF NOT EXISTS idx_schedule_pattern_company_active ON educlaw_schedule_pattern(company_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_bell_period_pattern_sort ON educlaw_bell_period(schedule_pattern_id, sort_order);
        CREATE INDEX IF NOT EXISTS idx_bell_period_pattern_type ON educlaw_bell_period(schedule_pattern_id, period_type);
        CREATE INDEX IF NOT EXISTS idx_day_type_pattern_sort ON educlaw_day_type(schedule_pattern_id, sort_order);
        CREATE INDEX IF NOT EXISTS idx_instructor_constraint_inst_term ON educlaw_instructor_constraint(instructor_id, academic_term_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_instructor_constraint_inst_type ON educlaw_instructor_constraint(instructor_id, academic_term_id, constraint_type);
        CREATE INDEX IF NOT EXISTS idx_instructor_constraint_term_type ON educlaw_instructor_constraint(academic_term_id, constraint_type);
        CREATE INDEX IF NOT EXISTS idx_master_schedule_term ON educlaw_master_schedule(academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_master_schedule_company_status ON educlaw_master_schedule(company_id, schedule_status);
        CREATE INDEX IF NOT EXISTS idx_master_schedule_series ON educlaw_master_schedule(naming_series);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_section_slot ON educlaw_section_meeting(section_id, day_type_id, bell_period_id);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_master_slot ON educlaw_section_meeting(master_schedule_id, day_type_id, bell_period_id);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_instructor_slot ON educlaw_section_meeting(instructor_id, day_type_id, bell_period_id);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_room_slot ON educlaw_section_meeting(room_id, day_type_id, bell_period_id);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_master_section ON educlaw_section_meeting(master_schedule_id, section_id);
        CREATE INDEX IF NOT EXISTS idx_section_meeting_active ON educlaw_section_meeting(master_schedule_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_room_booking_room_slot_status ON educlaw_room_booking(room_id, day_type_id, bell_period_id, booking_status);
        CREATE INDEX IF NOT EXISTS idx_room_booking_meeting ON educlaw_room_booking(section_meeting_id);
        CREATE INDEX IF NOT EXISTS idx_room_booking_master_room ON educlaw_room_booking(master_schedule_id, room_id);
        CREATE INDEX IF NOT EXISTS idx_room_booking_company_type ON educlaw_room_booking(company_id, booking_type);
        CREATE INDEX IF NOT EXISTS idx_room_booking_status ON educlaw_room_booking(company_id, booking_status);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_master_status_sev ON educlaw_schedule_conflict(master_schedule_id, conflict_status, severity);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_master_type ON educlaw_schedule_conflict(master_schedule_id, conflict_type);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_instructor ON educlaw_schedule_conflict(instructor_id, conflict_status);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_room ON educlaw_schedule_conflict(room_id, conflict_status);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_meeting_a ON educlaw_schedule_conflict(section_meeting_id_a);
        CREATE INDEX IF NOT EXISTS idx_schedule_conflict_company_status ON educlaw_schedule_conflict(company_id, conflict_status);
    """)

    conn.commit()
    conn.close()

    print(f"EduClaw schema created: 41 tables")
    print(f"Database: {db_path}")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    create_educlaw_scheduling_tables(db_path)
