#!/usr/bin/env python3
"""EduClaw Advanced Scheduling schema — 9 owned tables on top of the educlaw base.

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to restore section_meeting_id_b FK
(generator limitation with same-table double refs — same pattern as educlaw
 prerequisite_course_id fix).

Parent: educlaw | Tables: 9 owned | Indexes: 33 owned
Domains: schedule_patterns, master_schedule, conflict_resolution, room_assignment

New tables (9):
  schedule_patterns    : educlaw_schedule_pattern, educlaw_bell_period,
                         educlaw_day_type
  master_schedule      : educlaw_course_request, educlaw_master_schedule,
                         educlaw_section_meeting
  room_assignment      : educlaw_instructor_constraint, educlaw_room_booking
  conflict_resolution  : educlaw_schedule_conflict

Installing this module also materialises the 32 shared educlaw base tables via
`ensure_educlaw_base_tables`, because a sub-vertical may be installed before its
parent. Those tables are owned by educlaw CORE and are deliberately NOT declared
in this module's metadata — five sub-verticals call the same helper, and each
declaring them would be five claims of ownership on one schema. (The docstring
before the ADR-0034 conversion counted those 32 as this module's own and claimed
"41 tables, 121 indexes"; the honest owned figures are 9 and 33.)

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-scheduling (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]

ADR-0034 phase 2 bulk-39. This module's own schema is declared as metadata and
provisioned through `erpclaw_lib.seam`, which emits dialect-correct DDL, instead
of a hand-written ``CREATE TABLE`` block opened with ``sqlite3.connect``. The old
shape could not run on PostgreSQL at all. Conversion rules are the pilot's
(`erpclaw-esign`): seam vocabulary only, money and IDs stay TEXT, and
``primary_key=True, nullable=True`` reproduces SQLite's ``id TEXT PRIMARY KEY``
without adding a NOT NULL that never shipped.
"""
import importlib.util
import os
import sys

# The shared educlaw base schema is a sibling of this module's directory.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Bootstrap the shared lib only when it is not already reachable — an
# unconditional insert at position 0 overrides a caller that deliberately bound a
# different tree (ADR-0034 phase 2 step 2d).
if importlib.util.find_spec("erpclaw_lib") is None:
    sys.path.insert(0, os.path.join(os.path.expanduser(
        os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "lib"))

from educlaw_base_schema import ensure_educlaw_base_tables  # noqa: E402
from erpclaw_lib.db import get_connection  # noqa: E402
from erpclaw_lib.seam import (  # noqa: E402
    CheckConstraint, Column, ForeignKey, Index, Integer, MetaData, Table, Text,
    UniqueConstraint, provision, reference_table, table_exists, text,
)

DEFAULT_DB_PATH = os.path.join(os.path.expanduser(os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "data.sqlite")

# The pre-conversion probe asked for `company` alone. Transcribed, not widened.
REQUIRED_FOUNDATION = ["company"]

METADATA = MetaData()

# Tables this module points at but does not own — the ERPClaw foundation's
# `company` and six of educlaw core's base tables. Declared for foreign key
# resolution only and never created here; `ensure_educlaw_base_tables` below is
# what actually creates the educlaw ones. See `seam.reference_table`.
reference_table("company", METADATA)
reference_table("educlaw_academic_term", METADATA)
reference_table("educlaw_course", METADATA)
reference_table("educlaw_instructor", METADATA)
reference_table("educlaw_room", METADATA)
reference_table("educlaw_section", METADATA)
reference_table("educlaw_student", METADATA)

# ---------------------------------------------------------------------------
# 1. educlaw_course_request (owned by master_schedule)
# ---------------------------------------------------------------------------
COURSE_REQUEST = Table(
    "educlaw_course_request", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("course_id", Text,
           ForeignKey("educlaw_course.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("request_priority", Integer, nullable=False, server_default=text("1")),
    Column("is_alternate", Integer, nullable=False, server_default=text("0")),
    # Second reference to educlaw_course from the same table — the alternate a
    # request falls back to. Nullable and defaultless, unlike course_id.
    Column("alternate_for_course_id", Text,
           ForeignKey("educlaw_course.id", ondelete="RESTRICT")),
    Column("request_status", Text, nullable=False,
           server_default=text("'submitted'")),
    Column("fulfilled_section_id", Text,
           ForeignKey("educlaw_section.id", ondelete="RESTRICT")),
    Column("prerequisite_override", Integer, nullable=False,
           server_default=text("0")),
    Column("prerequisite_override_by", Text, nullable=False,
           server_default=text("''")),
    Column("prerequisite_override_note", Text, nullable=False,
           server_default=text("''")),
    Column("has_iep_flag", Integer, nullable=False, server_default=text("0")),
    Column("submitted_by", Text, nullable=False, server_default=text("''")),
    Column("approved_by", Text, nullable=False, server_default=text("''")),
    Column("approved_at", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "is_alternate IN (0, 1)",
        name="ck_educlaw_course_request_is_alternate"),
    CheckConstraint(
        "request_status IN ('draft','submitted','approved','scheduled',"
        "'alternate_used','unfulfilled','withdrawn')",
        name="ck_educlaw_course_request_request_status"),
    CheckConstraint(
        "prerequisite_override IN (0, 1)",
        name="ck_educlaw_course_request_prerequisite_override"),
    CheckConstraint(
        "has_iep_flag IN (0, 1)",
        name="ck_educlaw_course_request_has_iep_flag"),
    UniqueConstraint("student_id", "academic_term_id", "course_id",
                     name="uq_course_request_student_term_course"),
)

Index("idx_course_request_student_term_course", COURSE_REQUEST.c.student_id,
      COURSE_REQUEST.c.academic_term_id, COURSE_REQUEST.c.course_id)
Index("idx_course_request_term_course_status",
      COURSE_REQUEST.c.academic_term_id, COURSE_REQUEST.c.course_id,
      COURSE_REQUEST.c.request_status)
Index("idx_course_request_student_term", COURSE_REQUEST.c.student_id,
      COURSE_REQUEST.c.academic_term_id, COURSE_REQUEST.c.request_status)
Index("idx_course_request_term_status", COURSE_REQUEST.c.academic_term_id,
      COURSE_REQUEST.c.request_status)
Index("idx_course_request_series", COURSE_REQUEST.c.naming_series)

# ---------------------------------------------------------------------------
# 2. educlaw_schedule_pattern (owned by schedule_patterns)
# ---------------------------------------------------------------------------
SCHEDULE_PATTERN = Table(
    "educlaw_schedule_pattern", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("pattern_type", Text, nullable=False, server_default=text("''")),
    Column("cycle_days", Integer, nullable=False, server_default=text("1")),
    Column("total_periods_per_cycle", Integer, nullable=False,
           server_default=text("0")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "pattern_type IN ('traditional','block_4x4','block_ab','trimester',"
        "'rotating_drop','semester','custom')",
        name="ck_educlaw_schedule_pattern_pattern_type"),
    CheckConstraint(
        "cycle_days >= 1",
        name="ck_educlaw_schedule_pattern_cycle_days"),
    CheckConstraint(
        "is_active IN (0, 1)",
        name="ck_educlaw_schedule_pattern_is_active"),
)

Index("idx_schedule_pattern_company_type", SCHEDULE_PATTERN.c.company_id,
      SCHEDULE_PATTERN.c.pattern_type)
Index("idx_schedule_pattern_company_active", SCHEDULE_PATTERN.c.company_id,
      SCHEDULE_PATTERN.c.is_active)

# ---------------------------------------------------------------------------
# 3. educlaw_bell_period (owned by schedule_patterns)
# ---------------------------------------------------------------------------
BELL_PERIOD = Table(
    "educlaw_bell_period", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("schedule_pattern_id", Text,
           ForeignKey("educlaw_schedule_pattern.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("period_number", Text, nullable=False, server_default=text("''")),
    Column("period_name", Text, nullable=False, server_default=text("''")),
    Column("start_time", Text, nullable=False, server_default=text("''")),
    Column("end_time", Text, nullable=False, server_default=text("''")),
    Column("duration_minutes", Integer, nullable=False, server_default=text("0")),
    Column("period_type", Text, nullable=False, server_default=text("'class'")),
    Column("applies_to_day_types", Text, nullable=False,
           server_default=text("'[]'")),
    Column("sort_order", Integer, nullable=False, server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "duration_minutes > 0",
        name="ck_educlaw_bell_period_duration_minutes"),
    CheckConstraint(
        "period_type IN ('class','break','lunch','homeroom','advisory','flex',"
        "'passing')",
        name="ck_educlaw_bell_period_period_type"),
    UniqueConstraint("schedule_pattern_id", "period_number",
                     name="uq_bell_period_pattern_number"),
)

Index("idx_bell_period_pattern_sort", BELL_PERIOD.c.schedule_pattern_id,
      BELL_PERIOD.c.sort_order)
Index("idx_bell_period_pattern_type", BELL_PERIOD.c.schedule_pattern_id,
      BELL_PERIOD.c.period_type)

# ---------------------------------------------------------------------------
# 4. educlaw_day_type (owned by schedule_patterns)
# ---------------------------------------------------------------------------
DAY_TYPE = Table(
    "educlaw_day_type", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("schedule_pattern_id", Text,
           ForeignKey("educlaw_schedule_pattern.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("code", Text, nullable=False, server_default=text("''")),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("sort_order", Integer, nullable=False, server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "sort_order >= 0",
        name="ck_educlaw_day_type_sort_order"),
    UniqueConstraint("schedule_pattern_id", "code",
                     name="uq_day_type_pattern_code"),
)

Index("idx_day_type_pattern_sort", DAY_TYPE.c.schedule_pattern_id,
      DAY_TYPE.c.sort_order)

# ---------------------------------------------------------------------------
# 5. educlaw_instructor_constraint (owned by room_assignment)
# ---------------------------------------------------------------------------
INSTRUCTOR_CONSTRAINT = Table(
    "educlaw_instructor_constraint", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("instructor_id", Text,
           ForeignKey("educlaw_instructor.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("constraint_type", Text, nullable=False, server_default=text("''")),
    Column("day_type_id", Text,
           ForeignKey("educlaw_day_type.id", ondelete="RESTRICT")),
    Column("bell_period_id", Text,
           ForeignKey("educlaw_bell_period.id", ondelete="RESTRICT")),
    Column("constraint_value", Integer, nullable=False, server_default=text("0")),
    Column("constraint_notes", Text, nullable=False, server_default=text("''")),
    Column("priority", Text, nullable=False,
           server_default=text("'preference'")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "constraint_type IN ('unavailable','preferred','max_periods_per_day',"
        "'max_consecutive_periods','requires_prep_period','preferred_building')",
        name="ck_educlaw_instructor_constraint_constraint_type"),
    CheckConstraint(
        "priority IN ('hard','soft','preference')",
        name="ck_educlaw_instructor_constraint_priority"),
    CheckConstraint(
        "is_active IN (0, 1)",
        name="ck_educlaw_instructor_constraint_is_active"),
)

Index("idx_instructor_constraint_inst_term",
      INSTRUCTOR_CONSTRAINT.c.instructor_id,
      INSTRUCTOR_CONSTRAINT.c.academic_term_id,
      INSTRUCTOR_CONSTRAINT.c.is_active)
Index("idx_instructor_constraint_inst_type",
      INSTRUCTOR_CONSTRAINT.c.instructor_id,
      INSTRUCTOR_CONSTRAINT.c.academic_term_id,
      INSTRUCTOR_CONSTRAINT.c.constraint_type)
Index("idx_instructor_constraint_term_type",
      INSTRUCTOR_CONSTRAINT.c.academic_term_id,
      INSTRUCTOR_CONSTRAINT.c.constraint_type)

# ---------------------------------------------------------------------------
# 6. educlaw_master_schedule (owned by master_schedule)
# ---------------------------------------------------------------------------
MASTER_SCHEDULE = Table(
    "educlaw_master_schedule", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("name", Text, nullable=False, server_default=text("''")),
    # One master schedule per term: the UNIQUE rides on the same column as the
    # foreign key, exactly as the shipped DDL spells it.
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT"),
           nullable=False, unique=True, server_default=text("''")),
    Column("schedule_pattern_id", Text,
           ForeignKey("educlaw_schedule_pattern.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("build_notes", Text, nullable=False, server_default=text("''")),
    Column("total_sections", Integer, nullable=False, server_default=text("0")),
    Column("sections_placed", Integer, nullable=False, server_default=text("0")),
    Column("sections_with_room", Integer, nullable=False,
           server_default=text("0")),
    Column("open_conflicts", Integer, nullable=False, server_default=text("0")),
    Column("fulfillment_rate", Text, nullable=False, server_default=text("''")),
    Column("schedule_status", Text, nullable=False,
           server_default=text("'draft'")),
    Column("published_at", Text, nullable=False, server_default=text("''")),
    Column("published_by", Text, nullable=False, server_default=text("''")),
    Column("locked_at", Text, nullable=False, server_default=text("''")),
    Column("locked_by", Text, nullable=False, server_default=text("''")),
    # Self-referential: a schedule cloned from last term's points back at it.
    Column("cloned_from_id", Text,
           ForeignKey("educlaw_master_schedule.id", ondelete="RESTRICT")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "schedule_status IN ('draft','building','review','published','locked',"
        "'archived')",
        name="ck_educlaw_master_schedule_schedule_status"),
)

Index("idx_master_schedule_term", MASTER_SCHEDULE.c.academic_term_id)
Index("idx_master_schedule_company_status", MASTER_SCHEDULE.c.company_id,
      MASTER_SCHEDULE.c.schedule_status)
Index("idx_master_schedule_series", MASTER_SCHEDULE.c.naming_series)

# ---------------------------------------------------------------------------
# 7. educlaw_section_meeting (owned by master_schedule)
# ---------------------------------------------------------------------------
SECTION_MEETING = Table(
    "educlaw_section_meeting", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("section_id", Text,
           ForeignKey("educlaw_section.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("master_schedule_id", Text,
           ForeignKey("educlaw_master_schedule.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("day_type_id", Text,
           ForeignKey("educlaw_day_type.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("bell_period_id", Text,
           ForeignKey("educlaw_bell_period.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("room_id", Text,
           ForeignKey("educlaw_room.id", ondelete="RESTRICT")),
    Column("instructor_id", Text,
           ForeignKey("educlaw_instructor.id", ondelete="RESTRICT")),
    Column("meeting_type", Text, nullable=False,
           server_default=text("'regular'")),
    Column("meeting_mode", Text, nullable=False,
           server_default=text("'in_person'")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("notes", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "meeting_type IN ('regular','lab','exam','field_trip','make_up')",
        name="ck_educlaw_section_meeting_meeting_type"),
    CheckConstraint(
        "meeting_mode IN ('in_person','hybrid','online')",
        name="ck_educlaw_section_meeting_meeting_mode"),
    CheckConstraint(
        "is_active IN (0, 1)",
        name="ck_educlaw_section_meeting_is_active"),
    UniqueConstraint("section_id", "day_type_id", "bell_period_id",
                     name="uq_section_meeting_slot"),
)

Index("idx_section_meeting_section_slot", SECTION_MEETING.c.section_id,
      SECTION_MEETING.c.day_type_id, SECTION_MEETING.c.bell_period_id)
Index("idx_section_meeting_master_slot", SECTION_MEETING.c.master_schedule_id,
      SECTION_MEETING.c.day_type_id, SECTION_MEETING.c.bell_period_id)
Index("idx_section_meeting_instructor_slot", SECTION_MEETING.c.instructor_id,
      SECTION_MEETING.c.day_type_id, SECTION_MEETING.c.bell_period_id)
Index("idx_section_meeting_room_slot", SECTION_MEETING.c.room_id,
      SECTION_MEETING.c.day_type_id, SECTION_MEETING.c.bell_period_id)
Index("idx_section_meeting_master_section",
      SECTION_MEETING.c.master_schedule_id, SECTION_MEETING.c.section_id)
Index("idx_section_meeting_active", SECTION_MEETING.c.master_schedule_id,
      SECTION_MEETING.c.is_active)

# ---------------------------------------------------------------------------
# 8. educlaw_room_booking (owned by room_assignment)
# ---------------------------------------------------------------------------
ROOM_BOOKING = Table(
    "educlaw_room_booking", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("room_id", Text,
           ForeignKey("educlaw_room.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    # A booking need not belong to a master schedule or a section meeting — an
    # exam or a maintenance slot has neither. Nullable and defaultless, unlike
    # the day/period pair below.
    Column("master_schedule_id", Text,
           ForeignKey("educlaw_master_schedule.id", ondelete="RESTRICT")),
    Column("section_meeting_id", Text,
           ForeignKey("educlaw_section_meeting.id", ondelete="RESTRICT")),
    Column("day_type_id", Text,
           ForeignKey("educlaw_day_type.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("bell_period_id", Text,
           ForeignKey("educlaw_bell_period.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("booking_type", Text, nullable=False, server_default=text("'class'")),
    Column("booking_title", Text, nullable=False, server_default=text("''")),
    Column("booked_by", Text, nullable=False, server_default=text("''")),
    Column("booking_status", Text, nullable=False,
           server_default=text("'confirmed'")),
    Column("cancellation_reason", Text, nullable=False,
           server_default=text("''")),
    Column("accessibility_required", Integer, nullable=False,
           server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "booking_type IN ('class','exam','event','maintenance','admin','other')",
        name="ck_educlaw_room_booking_booking_type"),
    CheckConstraint(
        "booking_status IN ('confirmed','tentative','cancelled')",
        name="ck_educlaw_room_booking_booking_status"),
    CheckConstraint(
        "accessibility_required IN (0, 1)",
        name="ck_educlaw_room_booking_accessibility_required"),
)

Index("idx_room_booking_room_slot_status", ROOM_BOOKING.c.room_id,
      ROOM_BOOKING.c.day_type_id, ROOM_BOOKING.c.bell_period_id,
      ROOM_BOOKING.c.booking_status)
Index("idx_room_booking_meeting", ROOM_BOOKING.c.section_meeting_id)
Index("idx_room_booking_master_room", ROOM_BOOKING.c.master_schedule_id,
      ROOM_BOOKING.c.room_id)
Index("idx_room_booking_company_type", ROOM_BOOKING.c.company_id,
      ROOM_BOOKING.c.booking_type)
Index("idx_room_booking_status", ROOM_BOOKING.c.company_id,
      ROOM_BOOKING.c.booking_status)

# ---------------------------------------------------------------------------
# 9. educlaw_schedule_conflict (owned by conflict_resolution)
# ---------------------------------------------------------------------------
SCHEDULE_CONFLICT = Table(
    "educlaw_schedule_conflict", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("master_schedule_id", Text,
           ForeignKey("educlaw_master_schedule.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("conflict_type", Text, nullable=False, server_default=text("''")),
    Column("severity", Text, nullable=False, server_default=text("'high'")),
    # The two sides of a collision. Both point at educlaw_section_meeting; the
    # `_b` leg is the one the DSL generator dropped and the shipped file restored
    # by hand, so it is transcribed here deliberately rather than incidentally.
    Column("section_meeting_id_a", Text,
           ForeignKey("educlaw_section_meeting.id", ondelete="RESTRICT")),
    Column("section_meeting_id_b", Text,
           ForeignKey("educlaw_section_meeting.id", ondelete="RESTRICT")),
    Column("instructor_id", Text,
           ForeignKey("educlaw_instructor.id", ondelete="RESTRICT")),
    Column("room_id", Text,
           ForeignKey("educlaw_room.id", ondelete="RESTRICT")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("conflict_status", Text, nullable=False,
           server_default=text("'open'")),
    Column("resolution_notes", Text, nullable=False, server_default=text("''")),
    Column("resolved_by", Text, nullable=False, server_default=text("''")),
    Column("resolved_at", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "conflict_type IN ('instructor_double_booking','room_double_booking',"
        "'student_conflict','instructor_overload',"
        "'instructor_contract_violation','capacity_exceeded',"
        "'room_type_mismatch','credential_mismatch','singleton_overlap',"
        "'contact_hours_deficit','room_shortage')",
        name="ck_educlaw_schedule_conflict_conflict_type"),
    CheckConstraint(
        "severity IN ('critical','high','medium','low')",
        name="ck_educlaw_schedule_conflict_severity"),
    CheckConstraint(
        "conflict_status IN ('open','resolving','resolved','accepted',"
        "'superseded')",
        name="ck_educlaw_schedule_conflict_conflict_status"),
)

Index("idx_schedule_conflict_master_status_sev",
      SCHEDULE_CONFLICT.c.master_schedule_id,
      SCHEDULE_CONFLICT.c.conflict_status, SCHEDULE_CONFLICT.c.severity)
Index("idx_schedule_conflict_master_type",
      SCHEDULE_CONFLICT.c.master_schedule_id,
      SCHEDULE_CONFLICT.c.conflict_type)
Index("idx_schedule_conflict_instructor", SCHEDULE_CONFLICT.c.instructor_id,
      SCHEDULE_CONFLICT.c.conflict_status)
Index("idx_schedule_conflict_room", SCHEDULE_CONFLICT.c.room_id,
      SCHEDULE_CONFLICT.c.conflict_status)
Index("idx_schedule_conflict_meeting_a",
      SCHEDULE_CONFLICT.c.section_meeting_id_a)
Index("idx_schedule_conflict_company_status", SCHEDULE_CONFLICT.c.company_id,
      SCHEDULE_CONFLICT.c.conflict_status)


def _require_foundation(db_path):
    """Refuse to install onto a database with no ERPClaw foundation.

    Same check and same message as before the conversion; the pre-conversion
    version read `sqlite_master` directly, which is a hard error on PostgreSQL
    rather than a false, so it is asked through the seam instead.
    """
    missing = [t for t in REQUIRED_FOUNDATION if not table_exists(t, db_path)]
    if missing:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)


def create_educlaw_scheduling_tables(db_path):
    """Create the scheduling tables and indexes on whichever backend is configured.

    Same contract as before the ADR-0034 conversion: the shared educlaw base
    tables are ensured first, then this module's own nine. Idempotent, and the
    returned counts are what was ACTUALLY created rather than what was declared —
    so they count the nine owned tables, never educlaw core's 32.
    """
    _require_foundation(db_path)

    # educlaw core's base schema, created here because a sub-vertical can be
    # installed before its parent. Another module's installer is not this
    # conversion's to rewrite, so it keeps running exactly as it does today.
    conn = get_connection(db_path)
    try:
        ensure_educlaw_base_tables(conn)
        conn.commit()
    finally:
        conn.close()

    result = provision(METADATA, db_path)
    return {
        "database": db_path,
        "tables": result["tables"],
        "indexes": result["indexes"],
    }


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    result = create_educlaw_scheduling_tables(db_path)
    print(f"EduClaw Advanced Scheduling schema created in {result['database']}")
    print(f"  Tables: {result['tables']}")
    print(f"  Indexes: {result['indexes']}")
