#!/usr/bin/env python3
"""EduClaw schema — 55 tables (32 parent + 23 new).

Generated by ERPForge Schema DSL (generate_schema.py)
Parent: educlaw | Tables: 55 | Indexes: 169

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Run: python3 init_db.py [db_path]
"""
import os
import sqlite3
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from educlaw_base_schema import ensure_educlaw_base_tables


DEFAULT_DB_PATH = os.path.expanduser("~/.openclaw/erpclaw/data.sqlite")


def create_educlaw_k12_tables(db_path):
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA foreign_keys=ON")

    # Verify foundation exists
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()]
    if "company" not in tables:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)

    # Ensure parent schema (educlaw base tables) exists
    ensure_educlaw_base_tables(conn)


    conn.executescript("""
        -- ==========================================================
        -- EduClaw Domain Tables
        -- Generated by ERPForge Schema DSL
        -- Tables: 23 | Columns: 392
        -- ==========================================================

        -- educlaw_k12_504_plan (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_504_plan (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            meeting_date TEXT NOT NULL DEFAULT '',
            disability_description TEXT NOT NULL DEFAULT '',
            eligibility_basis TEXT NOT NULL DEFAULT '',
            plan_start_date TEXT NOT NULL DEFAULT '',
            plan_end_date TEXT NOT NULL DEFAULT '',
            review_date TEXT NOT NULL DEFAULT '',
            accommodations TEXT NOT NULL DEFAULT '[]',
            team_members TEXT NOT NULL DEFAULT '[]',
            parent_consent_date TEXT NOT NULL DEFAULT '',
            plan_status TEXT NOT NULL DEFAULT 'active' CHECK(plan_status IN ('active','expired','revised','discontinued')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_discipline_incident (owned by discipline)
        CREATE TABLE IF NOT EXISTS educlaw_k12_discipline_incident (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            incident_date TEXT NOT NULL DEFAULT '',
            incident_time TEXT NOT NULL DEFAULT '',
            location TEXT NOT NULL CHECK(location IN ('classroom','hallway','cafeteria','gym','bathroom','playground','bus','off_campus','online','other')),
            location_detail TEXT NOT NULL DEFAULT '',
            incident_type TEXT NOT NULL CHECK(incident_type IN ('tardy','dress_code','electronic_device','disruptive_behavior','disrespectful_language','classroom_disruption','bullying','harassment','physical_altercation_minor','theft','vandalism','cheating','truancy','insubordination','fighting','assault','weapons','drugs_alcohol','sexual_harassment','threats','extortion','arson','gang_activity','sexual_assault','serious_assault','bomb_threat','active_threat','other_minor','other_major')),
            severity TEXT NOT NULL CHECK(severity IN ('minor','moderate','major','emergency')),
            description TEXT NOT NULL DEFAULT '',
            is_reported_to_law_enforcement INTEGER NOT NULL DEFAULT 0,
            is_mandatory_report INTEGER NOT NULL DEFAULT 0,
            mandatory_report_date TEXT NOT NULL DEFAULT '',
            mandatory_report_agency TEXT NOT NULL DEFAULT '',
            is_title_ix INTEGER NOT NULL DEFAULT 0,
            incident_status TEXT NOT NULL DEFAULT 'open' CHECK(incident_status IN ('open','under_review','closed','appealed')),
            reviewed_by TEXT NOT NULL DEFAULT '',
            reviewed_at TEXT NOT NULL DEFAULT '',
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            academic_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_discipline_student (owned by discipline)
        CREATE TABLE IF NOT EXISTS educlaw_k12_discipline_student (
            id TEXT PRIMARY KEY,
            incident_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_discipline_incident(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            role TEXT NOT NULL CHECK(role IN ('offender','victim','witness','bystander')),
            is_idea_eligible INTEGER NOT NULL DEFAULT 0,
            cumulative_suspension_days_ytd TEXT NOT NULL DEFAULT '0',
            mdr_required INTEGER NOT NULL DEFAULT 0,
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_discipline_action (owned by discipline)
        CREATE TABLE IF NOT EXISTS educlaw_k12_discipline_action (
            id TEXT PRIMARY KEY,
            discipline_student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_discipline_student(id) ON DELETE RESTRICT,
            action_type TEXT NOT NULL CHECK(action_type IN ('verbal_warning','parent_contact','detention','in_school_suspension','out_of_school_suspension','expulsion_referral','counseling_referral','law_enforcement_referral','restorative_practice','community_service','loss_of_privilege','other')),
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            duration_days TEXT NOT NULL DEFAULT '0',
            administered_by TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_health_profile (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_health_profile (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            allergies TEXT NOT NULL DEFAULT '[]',
            chronic_conditions TEXT NOT NULL DEFAULT '[]',
            physician_name TEXT NOT NULL DEFAULT '',
            physician_phone TEXT NOT NULL DEFAULT '',
            physician_address TEXT NOT NULL DEFAULT '',
            health_insurance_carrier TEXT NOT NULL DEFAULT '',
            health_insurance_id TEXT NOT NULL DEFAULT '',
            blood_type TEXT NOT NULL DEFAULT 'unknown' CHECK(blood_type IN ('A+','A-','B+','B-','AB+','AB-','O+','O-','unknown')),
            height_cm TEXT NOT NULL DEFAULT '',
            weight_kg TEXT NOT NULL DEFAULT '',
            vision_screening_date TEXT NOT NULL DEFAULT '',
            hearing_screening_date TEXT NOT NULL DEFAULT '',
            dental_screening_date TEXT NOT NULL DEFAULT '',
            activity_restriction TEXT NOT NULL DEFAULT 'none' CHECK(activity_restriction IN ('none','limited','no_pe','no_contact_sports','custom')),
            activity_restriction_notes TEXT NOT NULL DEFAULT '',
            is_provisional_immunization INTEGER NOT NULL DEFAULT 0,
            provisional_enrollment_end_date TEXT NOT NULL DEFAULT '',
            is_mckinney_vento INTEGER NOT NULL DEFAULT 0,
            emergency_instructions TEXT NOT NULL DEFAULT '',
            profile_status TEXT NOT NULL DEFAULT 'incomplete' CHECK(profile_status IN ('active','incomplete','archived')),
            last_verified_date TEXT NOT NULL DEFAULT '',
            last_verified_by TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_health_visit (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_health_visit (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            visit_date TEXT NOT NULL DEFAULT '',
            visit_time TEXT NOT NULL DEFAULT '',
            chief_complaint TEXT NOT NULL CHECK(chief_complaint IN ('headache','stomachache','injury','fever','respiratory','mental_health','medication','vision','hearing','dental','skin','fatigue','other')),
            complaint_detail TEXT NOT NULL DEFAULT '',
            temperature TEXT NOT NULL DEFAULT '',
            pulse TEXT NOT NULL DEFAULT '',
            assessment TEXT NOT NULL DEFAULT '',
            treatment_provided TEXT NOT NULL DEFAULT '',
            disposition TEXT NOT NULL CHECK(disposition IN ('returned_to_class','sent_home','911_called','referred_to_physician','observation','no_action')),
            parent_contacted INTEGER NOT NULL DEFAULT 0,
            parent_contact_time TEXT NOT NULL DEFAULT '',
            parent_response TEXT NOT NULL DEFAULT '',
            is_emergency INTEGER NOT NULL DEFAULT 0,
            academic_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_immunization (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_immunization (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            vaccine_name TEXT NOT NULL DEFAULT '',
            cvx_code TEXT NOT NULL DEFAULT '',
            dose_number INTEGER NOT NULL DEFAULT 1,
            administration_date TEXT NOT NULL DEFAULT '',
            lot_number TEXT NOT NULL DEFAULT '',
            manufacturer TEXT NOT NULL DEFAULT '',
            provider_name TEXT NOT NULL DEFAULT '',
            provider_type TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual','iis_sync','provider_import')),
            iis_record_id TEXT NOT NULL DEFAULT '',
            corrects_record_id TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_immunization_waiver (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_immunization_waiver (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            vaccine_name TEXT NOT NULL DEFAULT '',
            cvx_code TEXT NOT NULL DEFAULT '',
            waiver_type TEXT NOT NULL CHECK(waiver_type IN ('medical','religious','philosophical')),
            waiver_basis TEXT NOT NULL DEFAULT '',
            issuing_physician TEXT NOT NULL DEFAULT '',
            issue_date TEXT NOT NULL DEFAULT '',
            expiry_date TEXT NOT NULL DEFAULT '',
            waiver_status TEXT NOT NULL DEFAULT 'active' CHECK(waiver_status IN ('active','expired','revoked')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_promotion_review (owned by grade_promotion)
        CREATE TABLE IF NOT EXISTS educlaw_k12_promotion_review (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            grade_level TEXT NOT NULL DEFAULT '',
            review_date TEXT NOT NULL DEFAULT '',
            gpa_ytd TEXT NOT NULL DEFAULT '',
            attendance_rate_ytd TEXT NOT NULL DEFAULT '',
            failing_subjects TEXT NOT NULL DEFAULT '[]',
            discipline_incident_count INTEGER NOT NULL DEFAULT 0,
            teacher_recommendation TEXT NOT NULL DEFAULT 'pending' CHECK(teacher_recommendation IN ('promote','retain','conditional','pending')),
            teacher_rationale TEXT NOT NULL DEFAULT '',
            counselor_recommendation TEXT NOT NULL DEFAULT 'pending' CHECK(counselor_recommendation IN ('promote','retain','conditional','pending')),
            counselor_notes TEXT NOT NULL DEFAULT '',
            is_idea_eligible INTEGER NOT NULL DEFAULT 0,
            prior_retention_count INTEGER NOT NULL DEFAULT 0,
            interventions_tried TEXT NOT NULL DEFAULT '[]',
            review_status TEXT NOT NULL DEFAULT 'pending' CHECK(review_status IN ('pending','in_review','decided','notified','appealed')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_intervention_plan (owned by grade_promotion)
        CREATE TABLE IF NOT EXISTS educlaw_k12_intervention_plan (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            promotion_review_id TEXT REFERENCES educlaw_k12_promotion_review(id) ON DELETE RESTRICT,
            trigger TEXT NOT NULL CHECK(trigger IN ('at_risk_mid_year','retention_decision','other')),
            intervention_types TEXT NOT NULL DEFAULT '[]',
            academic_targets TEXT NOT NULL DEFAULT '',
            attendance_target TEXT NOT NULL DEFAULT '',
            assigned_staff TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            review_date TEXT NOT NULL DEFAULT '',
            parent_notification_date TEXT NOT NULL DEFAULT '',
            plan_status TEXT NOT NULL DEFAULT 'active' CHECK(plan_status IN ('active','completed','abandoned')),
            outcome_notes TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_promotion_decision (owned by grade_promotion)
        CREATE TABLE IF NOT EXISTS educlaw_k12_promotion_decision (
            id TEXT PRIMARY KEY,
            promotion_review_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES educlaw_k12_promotion_review(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            academic_year_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            decision TEXT NOT NULL CHECK(decision IN ('promote','retain','conditional_promote')),
            decision_date TEXT NOT NULL DEFAULT '',
            decided_by TEXT NOT NULL DEFAULT '',
            rationale TEXT NOT NULL DEFAULT '',
            team_members TEXT NOT NULL DEFAULT '[]',
            conditions TEXT NOT NULL DEFAULT '',
            parent_notified_date TEXT NOT NULL DEFAULT '',
            parent_notified_by TEXT NOT NULL DEFAULT '',
            notification_method TEXT NOT NULL DEFAULT 'letter' CHECK(notification_method IN ('in_person','letter','email','phone')),
            appeal_deadline TEXT NOT NULL DEFAULT '',
            is_appealed INTEGER NOT NULL DEFAULT 0,
            appeal_filed_date TEXT NOT NULL DEFAULT '',
            appeal_outcome TEXT NOT NULL DEFAULT 'not_applicable' CHECK(appeal_outcome IN ('promote','retain','not_applicable')),
            appeal_decision_date TEXT NOT NULL DEFAULT '',
            next_grade_level TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_sped_referral (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_sped_referral (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            referral_date TEXT NOT NULL DEFAULT '',
            referral_source TEXT NOT NULL CHECK(referral_source IN ('teacher','parent','counselor','physician','self','administrator','other')),
            referral_reason TEXT NOT NULL DEFAULT '',
            areas_of_concern TEXT NOT NULL DEFAULT '[]',
            prior_interventions TEXT NOT NULL DEFAULT '',
            referral_status TEXT NOT NULL DEFAULT 'received' CHECK(referral_status IN ('received','consent_pending','consent_received','consent_denied','evaluation_in_progress','evaluation_complete','closed')),
            consent_request_date TEXT NOT NULL DEFAULT '',
            consent_received_date TEXT NOT NULL DEFAULT '',
            consent_denied_date TEXT NOT NULL DEFAULT '',
            evaluation_deadline TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_sped_eligibility (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_sped_eligibility (
            id TEXT PRIMARY KEY,
            referral_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES educlaw_k12_sped_referral(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            eligibility_meeting_date TEXT NOT NULL DEFAULT '',
            iep_deadline TEXT NOT NULL DEFAULT '',
            is_eligible INTEGER NOT NULL DEFAULT 0,
            disability_categories TEXT NOT NULL DEFAULT '[]',
            primary_disability TEXT NOT NULL DEFAULT '' CHECK(primary_disability IN ('specific_learning_disability','speech_language_impairment','other_health_impairment','autism_spectrum_disorder','intellectual_disability','emotional_disturbance','developmental_delay','multiple_disabilities','hearing_impairment','orthopedic_impairment','visual_impairment','traumatic_brain_injury','deaf_blindness','not_applicable')),
            adverse_educational_effect TEXT NOT NULL DEFAULT '',
            eligibility_status TEXT NOT NULL DEFAULT 'eligible' CHECK(eligibility_status IN ('eligible','ineligible','deferred')),
            ineligibility_reason TEXT NOT NULL DEFAULT '',
            team_members_present TEXT NOT NULL DEFAULT '[]',
            parent_consent_date TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            eligibility_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_sped_eligibility(id) ON DELETE RESTRICT,
            iep_version INTEGER NOT NULL DEFAULT 1,
            is_amendment INTEGER NOT NULL DEFAULT 0,
            parent_iep_id TEXT REFERENCES educlaw_k12_iep(id) ON DELETE RESTRICT,
            iep_meeting_date TEXT NOT NULL DEFAULT '',
            iep_start_date TEXT NOT NULL DEFAULT '',
            iep_end_date TEXT NOT NULL DEFAULT '',
            annual_review_due_date TEXT NOT NULL DEFAULT '',
            triennial_reevaluation_due_date TEXT NOT NULL DEFAULT '',
            plaafp_academic TEXT NOT NULL DEFAULT '',
            plaafp_functional TEXT NOT NULL DEFAULT '',
            lre_percentage_general_ed TEXT NOT NULL DEFAULT '',
            lre_justification TEXT NOT NULL DEFAULT '',
            supplementary_aids TEXT NOT NULL DEFAULT '',
            program_modifications TEXT NOT NULL DEFAULT '',
            state_assessment_participation TEXT NOT NULL DEFAULT 'with_accommodations' CHECK(state_assessment_participation IN ('standard','with_accommodations','alternate_assessment','exempt')),
            state_assessment_accommodations TEXT NOT NULL DEFAULT '',
            transition_plan_required INTEGER NOT NULL DEFAULT 0,
            transition_postsecondary_goal TEXT NOT NULL DEFAULT '',
            transition_employment_goal TEXT NOT NULL DEFAULT '',
            transition_independent_living_goal TEXT NOT NULL DEFAULT '',
            progress_report_frequency TEXT NOT NULL DEFAULT 'quarterly' CHECK(progress_report_frequency IN ('quarterly','semester','monthly','other')),
            iep_status TEXT NOT NULL DEFAULT 'draft' CHECK(iep_status IN ('draft','active','amended','expired','superseded')),
            parent_consent_date TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep_goal (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep_goal (
            id TEXT PRIMARY KEY,
            iep_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            goal_area TEXT NOT NULL CHECK(goal_area IN ('reading','writing','math','communication','social_emotional','behavioral','motor','vocational','adaptive','other')),
            goal_description TEXT NOT NULL DEFAULT '',
            baseline_performance TEXT NOT NULL DEFAULT '',
            target_performance TEXT NOT NULL DEFAULT '',
            measurement_method TEXT NOT NULL CHECK(measurement_method IN ('test_score','work_sample','observation','rubric','checklist','probe','other')),
            monitoring_frequency TEXT NOT NULL CHECK(monitoring_frequency IN ('weekly','biweekly','monthly','quarterly','per_marking_period')),
            responsible_provider TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_met INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep_progress (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep_progress (
            id TEXT PRIMARY KEY,
            iep_goal_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep_goal(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            reporting_period TEXT NOT NULL DEFAULT '',
            progress_date TEXT NOT NULL DEFAULT '',
            progress_rating TEXT NOT NULL CHECK(progress_rating IN ('met_goal','on_track','some_progress','insufficient_progress','not_started','regression')),
            current_performance TEXT NOT NULL DEFAULT '',
            evidence TEXT NOT NULL DEFAULT '',
            notes_for_parents TEXT NOT NULL DEFAULT '',
            documented_by TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep_service (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep_service (
            id TEXT PRIMARY KEY,
            iep_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            service_type TEXT NOT NULL CHECK(service_type IN ('special_education_instruction','speech_therapy','occupational_therapy','physical_therapy','counseling','transportation','assistive_technology','health_services','orientation_mobility','other')),
            service_setting TEXT NOT NULL CHECK(service_setting IN ('general_ed_classroom','resource_room','self_contained','separate_school','home','hospital','other')),
            frequency_minutes_per_week INTEGER NOT NULL DEFAULT 0,
            provider_name TEXT NOT NULL DEFAULT '',
            provider_role TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            total_minutes_delivered INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep_service_log (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep_service_log (
            id TEXT PRIMARY KEY,
            iep_service_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep_service(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            session_date TEXT NOT NULL DEFAULT '',
            minutes_delivered INTEGER NOT NULL DEFAULT 0,
            session_notes TEXT NOT NULL DEFAULT '',
            provider_name TEXT NOT NULL DEFAULT '',
            is_makeup_session INTEGER NOT NULL DEFAULT 0,
            was_session_missed INTEGER NOT NULL DEFAULT 0,
            missed_reason TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_iep_team_member (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_iep_team_member (
            id TEXT PRIMARY KEY,
            iep_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep(id) ON DELETE RESTRICT,
            member_type TEXT NOT NULL CHECK(member_type IN ('parent','student','general_ed_teacher','special_ed_teacher','administrator','school_psychologist','speech_pathologist','ot','pt','counselor','other_agency','other')),
            member_name TEXT NOT NULL DEFAULT '',
            member_role TEXT NOT NULL DEFAULT '',
            guardian_id TEXT REFERENCES educlaw_guardian(id) ON DELETE RESTRICT,
            instructor_id TEXT REFERENCES educlaw_instructor(id) ON DELETE RESTRICT,
            attended_meeting INTEGER NOT NULL DEFAULT 1,
            excused_absence INTEGER NOT NULL DEFAULT 0,
            excusal_notes TEXT NOT NULL DEFAULT '',
            signature_date TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_manifestation_review (owned by discipline)
        CREATE TABLE IF NOT EXISTS educlaw_k12_manifestation_review (
            id TEXT PRIMARY KEY,
            discipline_student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_discipline_student(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            iep_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_iep(id) ON DELETE RESTRICT,
            mdr_date TEXT NOT NULL DEFAULT '',
            question_1_result TEXT NOT NULL DEFAULT 'not_determined' CHECK(question_1_result IN ('yes','no','not_determined')),
            question_2_result TEXT NOT NULL DEFAULT 'not_determined' CHECK(question_2_result IN ('yes','no','not_determined')),
            determination TEXT NOT NULL DEFAULT 'pending' CHECK(determination IN ('manifestation','not_manifestation','pending')),
            outcome_action TEXT NOT NULL DEFAULT 'pending' CHECK(outcome_action IN ('return_to_placement','maintain_removal','interim_placement','pending')),
            fba_required INTEGER NOT NULL DEFAULT 0,
            bip_required INTEGER NOT NULL DEFAULT 0,
            fba_bip_notes TEXT NOT NULL DEFAULT '',
            parent_notified_date TEXT NOT NULL DEFAULT '',
            procedural_safeguards_sent INTEGER NOT NULL DEFAULT 0,
            notes TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_sped_evaluation (owned by special_education)
        CREATE TABLE IF NOT EXISTS educlaw_k12_sped_evaluation (
            id TEXT PRIMARY KEY,
            referral_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_sped_referral(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            evaluation_type TEXT NOT NULL CHECK(evaluation_type IN ('psychological','academic_achievement','speech_language','occupational_therapy','physical_therapy','hearing_screening','vision_screening','social_behavioral','classroom_observation','adaptive_behavior','other')),
            evaluator_name TEXT NOT NULL DEFAULT '',
            evaluator_role TEXT NOT NULL DEFAULT '',
            evaluation_date TEXT NOT NULL DEFAULT '',
            instrument_used TEXT NOT NULL DEFAULT '',
            findings_summary TEXT NOT NULL DEFAULT '',
            scores TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_student_medication (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_student_medication (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            medication_name TEXT NOT NULL DEFAULT '',
            dosage TEXT NOT NULL DEFAULT '',
            route TEXT NOT NULL CHECK(route IN ('oral','topical','inhalation','injection','nasal','eye_drops','ear_drops','other')),
            frequency TEXT NOT NULL CHECK(frequency IN ('once_daily','twice_daily','three_times_daily','as_needed','as_scheduled')),
            administration_times TEXT NOT NULL DEFAULT '[]',
            prescribing_physician TEXT NOT NULL DEFAULT '',
            physician_authorization_date TEXT NOT NULL DEFAULT '',
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            supply_count INTEGER NOT NULL DEFAULT 0,
            supply_low_threshold INTEGER NOT NULL DEFAULT 5,
            storage_instructions TEXT NOT NULL DEFAULT '',
            administration_instructions TEXT NOT NULL DEFAULT '',
            is_controlled_substance INTEGER NOT NULL DEFAULT 0,
            medication_status TEXT NOT NULL DEFAULT 'active' CHECK(medication_status IN ('active','expired','discontinued')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            updated_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_k12_medication_log (owned by health_records)
        CREATE TABLE IF NOT EXISTS educlaw_k12_medication_log (
            id TEXT PRIMARY KEY,
            student_medication_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_k12_student_medication(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            log_date TEXT NOT NULL DEFAULT '',
            log_time TEXT NOT NULL DEFAULT '',
            dose_given TEXT NOT NULL DEFAULT '',
            administered_by TEXT NOT NULL DEFAULT '',
            student_response TEXT NOT NULL DEFAULT '',
            is_refused INTEGER NOT NULL DEFAULT 0,
            refusal_reason TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- ==========================================================
        -- Indexes
        -- ==========================================================

        CREATE INDEX IF NOT EXISTS idx_k12_504_plan_student_status ON educlaw_k12_504_plan(student_id, plan_status);
        CREATE INDEX IF NOT EXISTS idx_k12_504_plan_review_status ON educlaw_k12_504_plan(review_date, plan_status);
        CREATE INDEX IF NOT EXISTS idx_k12_504_plan_company_status ON educlaw_k12_504_plan(company_id, plan_status);
        CREATE INDEX IF NOT EXISTS idx_k12_504_plan_naming_series ON educlaw_k12_504_plan(naming_series);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_company_date ON educlaw_k12_discipline_incident(company_id, incident_date);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_year_severity ON educlaw_k12_discipline_incident(academic_year_id, severity);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_status ON educlaw_k12_discipline_incident(incident_status);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_title_ix ON educlaw_k12_discipline_incident(is_title_ix);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_naming_series ON educlaw_k12_discipline_incident(naming_series);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_incident_term ON educlaw_k12_discipline_incident(academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_student_incident ON educlaw_k12_discipline_student(incident_id);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_student_student ON educlaw_k12_discipline_student(student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_student_idea ON educlaw_k12_discipline_student(student_id, is_idea_eligible);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_student_incident_role ON educlaw_k12_discipline_student(incident_id, role);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_action_student ON educlaw_k12_discipline_action(discipline_student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_disc_action_type_date ON educlaw_k12_discipline_action(action_type, start_date);
        CREATE INDEX IF NOT EXISTS idx_k12_health_profile_student ON educlaw_k12_health_profile(student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_health_profile_company_status ON educlaw_k12_health_profile(company_id, profile_status);
        CREATE INDEX IF NOT EXISTS idx_k12_health_profile_provisional ON educlaw_k12_health_profile(is_provisional_immunization, provisional_enrollment_end_date);
        CREATE INDEX IF NOT EXISTS idx_k12_health_profile_mckinney ON educlaw_k12_health_profile(is_mckinney_vento);
        CREATE INDEX IF NOT EXISTS idx_k12_health_visit_student_date ON educlaw_k12_health_visit(student_id, visit_date);
        CREATE INDEX IF NOT EXISTS idx_k12_health_visit_company_date ON educlaw_k12_health_visit(company_id, visit_date);
        CREATE INDEX IF NOT EXISTS idx_k12_health_visit_disposition ON educlaw_k12_health_visit(disposition);
        CREATE INDEX IF NOT EXISTS idx_k12_health_visit_emergency ON educlaw_k12_health_visit(is_emergency);
        CREATE INDEX IF NOT EXISTS idx_k12_health_visit_term ON educlaw_k12_health_visit(academic_term_id);
        CREATE INDEX IF NOT EXISTS idx_k12_immunization_student_cvx_dose ON educlaw_k12_immunization(student_id, cvx_code, dose_number);
        CREATE INDEX IF NOT EXISTS idx_k12_immunization_company_date ON educlaw_k12_immunization(company_id, administration_date);
        CREATE INDEX IF NOT EXISTS idx_k12_immunization_cvx ON educlaw_k12_immunization(cvx_code);
        CREATE INDEX IF NOT EXISTS idx_k12_imm_waiver_student_status ON educlaw_k12_immunization_waiver(student_id, waiver_status);
        CREATE INDEX IF NOT EXISTS idx_k12_imm_waiver_company_type_status ON educlaw_k12_immunization_waiver(company_id, waiver_type, waiver_status);
        CREATE INDEX IF NOT EXISTS idx_k12_imm_waiver_expiry_status ON educlaw_k12_immunization_waiver(expiry_date, waiver_status);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_review_student_year ON educlaw_k12_promotion_review(student_id, academic_year_id);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_review_company_grade_status ON educlaw_k12_promotion_review(company_id, grade_level, review_status);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_review_year_recommendation ON educlaw_k12_promotion_review(academic_year_id, teacher_recommendation);
        CREATE INDEX IF NOT EXISTS idx_k12_intervention_student_year ON educlaw_k12_intervention_plan(student_id, academic_year_id);
        CREATE INDEX IF NOT EXISTS idx_k12_intervention_company_status ON educlaw_k12_intervention_plan(company_id, plan_status);
        CREATE INDEX IF NOT EXISTS idx_k12_intervention_review_date_status ON educlaw_k12_intervention_plan(review_date, plan_status);
        CREATE INDEX IF NOT EXISTS idx_k12_intervention_review ON educlaw_k12_intervention_plan(promotion_review_id);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_decision_student_year ON educlaw_k12_promotion_decision(student_id, academic_year_id);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_decision_year_decision ON educlaw_k12_promotion_decision(academic_year_id, decision);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_decision_notified_date ON educlaw_k12_promotion_decision(parent_notified_date);
        CREATE INDEX IF NOT EXISTS idx_k12_promo_decision_review ON educlaw_k12_promotion_decision(promotion_review_id);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_referral_student ON educlaw_k12_sped_referral(student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_referral_company_status ON educlaw_k12_sped_referral(company_id, referral_status);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_referral_deadline_status ON educlaw_k12_sped_referral(evaluation_deadline, referral_status);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_referral_naming_series ON educlaw_k12_sped_referral(naming_series);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_elig_student_eligible ON educlaw_k12_sped_eligibility(student_id, is_eligible);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_elig_iep_deadline ON educlaw_k12_sped_eligibility(iep_deadline, is_eligible);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_elig_company_status ON educlaw_k12_sped_eligibility(company_id, eligibility_status);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_student_status ON educlaw_k12_iep(student_id, iep_status);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_annual_review_status ON educlaw_k12_iep(annual_review_due_date, iep_status);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_triennial_reeval ON educlaw_k12_iep(triennial_reevaluation_due_date);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_company_status ON educlaw_k12_iep(company_id, iep_status);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_naming_series ON educlaw_k12_iep(naming_series);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_parent ON educlaw_k12_iep(parent_iep_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_eligibility ON educlaw_k12_iep(eligibility_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_goal_iep ON educlaw_k12_iep_goal(iep_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_goal_student_met ON educlaw_k12_iep_goal(student_id, is_met);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_goal_provider ON educlaw_k12_iep_goal(responsible_provider);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_progress_goal_period ON educlaw_k12_iep_progress(iep_goal_id, reporting_period);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_progress_student_date ON educlaw_k12_iep_progress(student_id, progress_date);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_progress_goal_rating ON educlaw_k12_iep_progress(iep_goal_id, progress_rating);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_service_iep ON educlaw_k12_iep_service(iep_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_service_student_type ON educlaw_k12_iep_service(student_id, service_type);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_svc_log_service_date ON educlaw_k12_iep_service_log(iep_service_id, session_date);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_svc_log_student_date ON educlaw_k12_iep_service_log(student_id, session_date);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_team_iep ON educlaw_k12_iep_team_member(iep_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_team_iep_type ON educlaw_k12_iep_team_member(iep_id, member_type);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_team_guardian ON educlaw_k12_iep_team_member(guardian_id);
        CREATE INDEX IF NOT EXISTS idx_k12_iep_team_instructor ON educlaw_k12_iep_team_member(instructor_id);
        CREATE INDEX IF NOT EXISTS idx_k12_mdr_student ON educlaw_k12_manifestation_review(student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_mdr_iep ON educlaw_k12_manifestation_review(iep_id);
        CREATE INDEX IF NOT EXISTS idx_k12_mdr_date ON educlaw_k12_manifestation_review(mdr_date);
        CREATE INDEX IF NOT EXISTS idx_k12_mdr_company_determination ON educlaw_k12_manifestation_review(company_id, determination);
        CREATE INDEX IF NOT EXISTS idx_k12_mdr_disc_student ON educlaw_k12_manifestation_review(discipline_student_id);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_eval_referral ON educlaw_k12_sped_evaluation(referral_id);
        CREATE INDEX IF NOT EXISTS idx_k12_sped_eval_student_type ON educlaw_k12_sped_evaluation(student_id, evaluation_type);
        CREATE INDEX IF NOT EXISTS idx_k12_student_med_student_status ON educlaw_k12_student_medication(student_id, medication_status);
        CREATE INDEX IF NOT EXISTS idx_k12_student_med_company_status ON educlaw_k12_student_medication(company_id, medication_status);
        CREATE INDEX IF NOT EXISTS idx_k12_med_log_med_date ON educlaw_k12_medication_log(student_medication_id, log_date);
        CREATE INDEX IF NOT EXISTS idx_k12_med_log_student_date ON educlaw_k12_medication_log(student_id, log_date);
    """)

    conn.commit()
    conn.close()

    print(f"EduClaw schema created: 55 tables")
    print(f"Database: {db_path}")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    create_educlaw_k12_tables(db_path)
