#!/usr/bin/env python3
"""EduClaw State Reporting schema — 15 owned tables on top of the educlaw base.

Generated by ERPForge Schema DSL (generate_schema.py)

Parent: educlaw | Tables: 15 owned | Indexes: 54 owned

New tables (sr_*):
  ed_fi domain             : sr_edfi_config, sr_edfi_descriptor_map,
                             sr_edfi_sync_log, sr_org_mapping
  state_reporting domain   : sr_collection_window, sr_snapshot,
                             sr_snapshot_record
  demographics domain      : sr_student_supplement, sr_el_program,
                             sr_sped_placement, sr_sped_service
  submission_tracking      : sr_submission, sr_submission_error
  data_validation          : sr_validation_rule, sr_validation_result

Discipline tables (educlaw_k12_discipline_incident,
educlaw_k12_discipline_student, educlaw_k12_discipline_action) are owned by
educlaw-k12. State reporting READS them and deliberately does not declare them.

Immutable tables (no updated_at — append-only):
  sr_edfi_sync_log, sr_snapshot_record, sr_sped_service, sr_validation_result

Installing this module also materialises the 32 shared educlaw base tables via
`ensure_educlaw_base_tables`, because a sub-vertical may be installed before its
parent. Those tables are owned by educlaw CORE and are deliberately NOT declared
in this module's metadata — five sub-verticals call the same helper, and each
declaring them would be five claims of ownership on one schema.

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-statereport (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]

ADR-0034 phase 2 bulk-39. This module's own schema is declared as metadata and
provisioned through `erpclaw_lib.seam`, which emits dialect-correct DDL, instead
of a hand-written ``CREATE TABLE`` block opened with ``sqlite3.connect``. The old
shape could not run on PostgreSQL at all. Conversion rules are the pilot's
(`erpclaw-esign`): seam vocabulary only, money and IDs stay TEXT, and
``primary_key=True, nullable=True`` reproduces SQLite's ``id TEXT PRIMARY KEY``
without adding a NOT NULL that never shipped.

The pre-conversion docstring claimed "47 tables (32 parent + 15 new)" and
"Indexes: 141", counting educlaw core's base schema as this module's own. The
counts above are this module's owned schema, which is what it is responsible for.
"""
import importlib.util
import os
import sys

# The shared educlaw base schema is a sibling of this module's directory.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Bootstrap the shared lib only when it is not already reachable — an
# unconditional insert at position 0 overrides a caller that deliberately bound a
# different tree (ADR-0034 phase 2 step 2d).
if importlib.util.find_spec("erpclaw_lib") is None:
    sys.path.insert(0, os.path.join(os.path.expanduser(
        os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "lib"))

from educlaw_base_schema import ensure_educlaw_base_tables  # noqa: E402
from erpclaw_lib.db import get_connection  # noqa: E402
from erpclaw_lib.seam import (  # noqa: E402
    CheckConstraint, Column, ForeignKey, Index, Integer, MetaData, Table, Text,
    UniqueConstraint, provision, reference_table, table_exists, text,
)

DEFAULT_DB_PATH = os.path.join(os.path.expanduser(os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "data.sqlite")
DISPLAY_NAME = "EduClaw State Reporting"

# The pre-conversion probe asked for `company` alone. Transcribed, not widened.
REQUIRED_FOUNDATION = ["company"]

METADATA = MetaData()

# Tables this module points at but does not own — the ERPClaw foundation's
# `company` and `employee`, plus two of educlaw core's base tables. Declared for
# foreign key resolution only and never created here; `ensure_educlaw_base_tables`
# above is what actually creates the educlaw ones. See `seam.reference_table`.
reference_table("company", METADATA)
reference_table("employee", METADATA)
reference_table("educlaw_academic_year", METADATA)
reference_table("educlaw_student", METADATA)

# ---------------------------------------------------------------------------
# 1. sr_edfi_config (owned by ed_fi)
# ---------------------------------------------------------------------------
SR_EDFI_CONFIG = Table(
    "sr_edfi_config", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("profile_name", Text, nullable=False, server_default=text("''")),
    Column("state_code", Text, nullable=False, server_default=text("''")),
    Column("school_year", Integer, nullable=False, server_default=text("0")),
    Column("ods_base_url", Text, nullable=False, server_default=text("''")),
    Column("oauth_token_url", Text, nullable=False, server_default=text("''")),
    Column("oauth_client_id", Text, nullable=False, server_default=text("''")),
    Column("oauth_client_secret_encrypted", Text, nullable=False,
           server_default=text("''")),
    Column("api_version", Text, nullable=False, server_default=text("'7'")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("last_tested_at", Text, nullable=False, server_default=text("''")),
    Column("last_token_at", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "api_version IN ('5','6','7')",
        name="ck_sr_edfi_config_api_version"),
    UniqueConstraint("company_id", "state_code", "school_year",
                     name="uq_sr_edfi_config_company_state_year"),
)

Index("idx_sr_edfi_config_company_state", SR_EDFI_CONFIG.c.company_id,
      SR_EDFI_CONFIG.c.state_code, SR_EDFI_CONFIG.c.is_active)
Index("idx_sr_edfi_config_year", SR_EDFI_CONFIG.c.company_id,
      SR_EDFI_CONFIG.c.school_year)

# ---------------------------------------------------------------------------
# 2. sr_collection_window (owned by state_reporting)
# ---------------------------------------------------------------------------
SR_COLLECTION_WINDOW = Table(
    "sr_collection_window", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("state_code", Text, nullable=False, server_default=text("''")),
    Column("window_type", Text, nullable=False, server_default=text("''")),
    Column("school_year", Integer, nullable=False, server_default=text("0")),
    Column("academic_year_id", Text,
           ForeignKey("educlaw_academic_year.id", ondelete="RESTRICT")),
    Column("open_date", Text, nullable=False, server_default=text("''")),
    Column("close_date", Text, nullable=False, server_default=text("''")),
    Column("snapshot_date", Text, nullable=False, server_default=text("''")),
    Column("status", Text, nullable=False, server_default=text("'upcoming'")),
    Column("required_data_categories", Text, nullable=False,
           server_default=text("'[]'")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("is_federal_required", Integer, nullable=False,
           server_default=text("0")),
    Column("edfi_config_id", Text,
           ForeignKey("sr_edfi_config.id", ondelete="RESTRICT")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "window_type IN ('fall_enrollment','fall_sped','winter_update',"
        "'spring_enrollment','eoy_attendance','eoy_discipline','eoy_grades',"
        "'staffing','crdc','summer_correction')",
        name="ck_sr_collection_window_window_type"),
    CheckConstraint(
        "status IN ('upcoming','open','data_entry','validation','snapshot',"
        "'submitted','certified','closed')",
        name="ck_sr_collection_window_status"),
    UniqueConstraint("company_id", "state_code", "window_type", "school_year",
                     name="uq_sr_collection_window_company_state_type_year"),
)

Index("idx_sr_collection_window_company_status",
      SR_COLLECTION_WINDOW.c.company_id, SR_COLLECTION_WINDOW.c.status)
Index("idx_sr_collection_window_year_state", SR_COLLECTION_WINDOW.c.company_id,
      SR_COLLECTION_WINDOW.c.school_year, SR_COLLECTION_WINDOW.c.state_code)
Index("idx_sr_collection_window_type", SR_COLLECTION_WINDOW.c.company_id,
      SR_COLLECTION_WINDOW.c.window_type, SR_COLLECTION_WINDOW.c.school_year)
Index("idx_sr_collection_window_dates", SR_COLLECTION_WINDOW.c.open_date,
      SR_COLLECTION_WINDOW.c.close_date)

# ---------------------------------------------------------------------------
# 3. sr_edfi_descriptor_map (owned by ed_fi)
# ---------------------------------------------------------------------------
SR_EDFI_DESCRIPTOR_MAP = Table(
    "sr_edfi_descriptor_map", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("config_id", Text,
           ForeignKey("sr_edfi_config.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("descriptor_type", Text, nullable=False, server_default=text("''")),
    Column("internal_code", Text, nullable=False, server_default=text("''")),
    Column("edfi_descriptor_uri", Text, nullable=False,
           server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "descriptor_type IN ('grade_level','race','sex','attendance_event',"
        "'disability','language','exit_type','entry_type','discipline_behavior',"
        "'discipline_action','sped_environment','program_type',"
        "'credential_type','course_level','homeless_residence')",
        name="ck_sr_edfi_descriptor_map_descriptor_type"),
    UniqueConstraint("config_id", "descriptor_type", "internal_code",
                     name="uq_sr_descriptor_config_type_code"),
)

Index("idx_sr_descriptor_config_type", SR_EDFI_DESCRIPTOR_MAP.c.config_id,
      SR_EDFI_DESCRIPTOR_MAP.c.descriptor_type,
      SR_EDFI_DESCRIPTOR_MAP.c.is_active)
Index("idx_sr_descriptor_internal", SR_EDFI_DESCRIPTOR_MAP.c.config_id,
      SR_EDFI_DESCRIPTOR_MAP.c.internal_code)

# ---------------------------------------------------------------------------
# 4. sr_edfi_sync_log (owned by ed_fi)
# ---------------------------------------------------------------------------
SR_EDFI_SYNC_LOG = Table(
    "sr_edfi_sync_log", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("config_id", Text,
           ForeignKey("sr_edfi_config.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("collection_window_id", Text,
           ForeignKey("sr_collection_window.id", ondelete="RESTRICT")),
    Column("resource_type", Text, nullable=False, server_default=text("''")),
    Column("operation", Text, nullable=False, server_default=text("''")),
    Column("internal_id", Text, nullable=False, server_default=text("''")),
    Column("edfi_natural_key", Text, nullable=False, server_default=text("''")),
    Column("http_status", Integer, nullable=False, server_default=text("0")),
    Column("request_payload_hash", Text, nullable=False,
           server_default=text("''")),
    Column("response_body", Text, nullable=False, server_default=text("''")),
    Column("sync_status", Text, nullable=False, server_default=text("'pending'")),
    Column("retry_count", Integer, nullable=False, server_default=text("0")),
    Column("synced_at", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    CheckConstraint(
        "operation IN ('POST','PUT','DELETE','GET')",
        name="ck_sr_edfi_sync_log_operation"),
    CheckConstraint(
        "sync_status IN ('success','error','retry','pending','skipped')",
        name="ck_sr_edfi_sync_log_sync_status"),
)

Index("idx_sr_sync_log_resource_internal", SR_EDFI_SYNC_LOG.c.resource_type,
      SR_EDFI_SYNC_LOG.c.internal_id)
Index("idx_sr_sync_log_status_time", SR_EDFI_SYNC_LOG.c.sync_status,
      SR_EDFI_SYNC_LOG.c.synced_at)
Index("idx_sr_sync_log_config_window", SR_EDFI_SYNC_LOG.c.config_id,
      SR_EDFI_SYNC_LOG.c.collection_window_id)
Index("idx_sr_sync_log_company_status", SR_EDFI_SYNC_LOG.c.company_id,
      SR_EDFI_SYNC_LOG.c.sync_status)

# ---------------------------------------------------------------------------
# 5. sr_el_program (owned by demographics)
# ---------------------------------------------------------------------------
SR_EL_PROGRAM = Table(
    "sr_el_program", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("school_year", Integer, nullable=False, server_default=text("0")),
    Column("program_type", Text, nullable=False, server_default=text("''")),
    Column("entry_date", Text, nullable=False, server_default=text("''")),
    Column("exit_date", Text, nullable=False, server_default=text("''")),
    Column("exit_reason", Text, nullable=False, server_default=text("''")),
    Column("english_proficiency_assessed_date", Text, nullable=False,
           server_default=text("''")),
    Column("proficiency_level", Text, nullable=False, server_default=text("''")),
    Column("proficiency_instrument", Text, nullable=False,
           server_default=text("''")),
    Column("is_parent_waived", Integer, nullable=False,
           server_default=text("0")),
    Column("waiver_date", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "program_type IN ('pull_out','push_in','sheltered_english',"
        "'dual_language','tbe_transitional','tbe_developmental','waiver',"
        "'content_based')",
        name="ck_sr_el_program_program_type"),
    CheckConstraint(
        "exit_reason IN ('reclassified','parent_waiver','transferred',"
        "'graduated','')",
        name="ck_sr_el_program_exit_reason"),
    CheckConstraint(
        "proficiency_instrument IN ('WIDA_ACCESS','ELPAC','TELPAS','LAS_LINKS',"
        "'IPT','OTHER','')",
        name="ck_sr_el_program_proficiency_instrument"),
)

Index("idx_sr_el_program_student_year", SR_EL_PROGRAM.c.student_id,
      SR_EL_PROGRAM.c.school_year)
Index("idx_sr_el_program_company_year", SR_EL_PROGRAM.c.company_id,
      SR_EL_PROGRAM.c.school_year)
Index("idx_sr_el_program_exit", SR_EL_PROGRAM.c.company_id,
      SR_EL_PROGRAM.c.exit_date)

# ---------------------------------------------------------------------------
# 6. sr_org_mapping (owned by ed_fi)
# ---------------------------------------------------------------------------
SR_ORG_MAPPING = Table(
    "sr_org_mapping", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("nces_lea_id", Text, nullable=False, server_default=text("''")),
    Column("nces_school_id", Text, nullable=False, server_default=text("''")),
    Column("state_code", Text, nullable=False, server_default=text("''")),
    Column("state_lea_id", Text, nullable=False, server_default=text("''")),
    Column("state_school_id", Text, nullable=False, server_default=text("''")),
    Column("edfi_lea_id", Text, nullable=False, server_default=text("''")),
    Column("edfi_school_id", Text, nullable=False, server_default=text("''")),
    Column("crdc_school_id", Text, nullable=False, server_default=text("''")),
    Column("is_title_i_school", Integer, nullable=False,
           server_default=text("0")),
    Column("title_i_status", Text, nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "length(state_code)=2 OR state_code=''",
        name="ck_sr_org_mapping_state_code"),
    CheckConstraint(
        "title_i_status IN ('targeted_assistance','schoolwide','not_title_i','')",
        name="ck_sr_org_mapping_title_i_status"),
    UniqueConstraint("company_id", "state_code", "nces_school_id",
                     name="uq_sr_org_mapping_company_state_school"),
)

Index("idx_sr_org_mapping_company_state", SR_ORG_MAPPING.c.company_id,
      SR_ORG_MAPPING.c.state_code)
Index("idx_sr_org_mapping_nces_lea", SR_ORG_MAPPING.c.nces_lea_id)
Index("idx_sr_org_mapping_nces_school", SR_ORG_MAPPING.c.nces_school_id)

# ---------------------------------------------------------------------------
# 7. sr_snapshot (owned by state_reporting)
# ---------------------------------------------------------------------------
SR_SNAPSHOT = Table(
    "sr_snapshot", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("collection_window_id", Text,
           ForeignKey("sr_collection_window.id", ondelete="RESTRICT"),
           nullable=False, unique=True, server_default=text("''")),
    Column("snapshot_taken_at", Text, nullable=False, server_default=text("''")),
    Column("snapshot_taken_by", Text, nullable=False, server_default=text("''")),
    Column("total_students", Integer, nullable=False, server_default=text("0")),
    Column("total_enrollment", Integer, nullable=False,
           server_default=text("0")),
    Column("total_sped", Integer, nullable=False, server_default=text("0")),
    Column("total_el", Integer, nullable=False, server_default=text("0")),
    Column("total_economically_disadvantaged", Integer, nullable=False,
           server_default=text("0")),
    Column("total_homeless", Integer, nullable=False, server_default=text("0")),
    Column("ada_total", Text, nullable=False, server_default=text("''")),
    Column("adm_total", Text, nullable=False, server_default=text("''")),
    Column("chronic_absenteeism_count", Integer, nullable=False,
           server_default=text("0")),
    Column("error_count_at_snapshot", Integer, nullable=False,
           server_default=text("0")),
    Column("snapshot_status", Text, nullable=False,
           server_default=text("'draft'")),
    Column("certified_by", Text, nullable=False, server_default=text("''")),
    Column("certified_at", Text, nullable=False, server_default=text("''")),
    Column("certification_notes", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "snapshot_status IN ('draft','finalized','certified')",
        name="ck_sr_snapshot_snapshot_status"),
)

Index("idx_sr_snapshot_window", SR_SNAPSHOT.c.collection_window_id)
Index("idx_sr_snapshot_company_status", SR_SNAPSHOT.c.company_id,
      SR_SNAPSHOT.c.snapshot_status)

# ---------------------------------------------------------------------------
# 8. sr_snapshot_record (owned by state_reporting)
# ---------------------------------------------------------------------------
SR_SNAPSHOT_RECORD = Table(
    "sr_snapshot_record", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("snapshot_id", Text,
           ForeignKey("sr_snapshot.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT")),
    Column("record_type", Text, nullable=False, server_default=text("''")),
    Column("data_json", Text, nullable=False, server_default=text("'{}'")),
    Column("school_year", Integer, nullable=False, server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    CheckConstraint(
        "record_type IN ('student_enrollment','attendance_summary',"
        "'sped_placement','el_program','discipline_summary','staff_assignment')",
        name="ck_sr_snapshot_record_record_type"),
)

Index("idx_sr_snapshot_record_snapshot_type", SR_SNAPSHOT_RECORD.c.snapshot_id,
      SR_SNAPSHOT_RECORD.c.record_type)
Index("idx_sr_snapshot_record_student", SR_SNAPSHOT_RECORD.c.snapshot_id,
      SR_SNAPSHOT_RECORD.c.student_id)
Index("idx_sr_snapshot_record_company", SR_SNAPSHOT_RECORD.c.company_id,
      SR_SNAPSHOT_RECORD.c.school_year)

# ---------------------------------------------------------------------------
# 9. sr_sped_placement (owned by demographics)
# ---------------------------------------------------------------------------
SR_SPED_PLACEMENT = Table(
    "sr_sped_placement", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("school_year", Integer, nullable=False, server_default=text("0")),
    Column("disability_category", Text, nullable=False,
           server_default=text("''")),
    Column("secondary_disability", Text, nullable=False,
           server_default=text("''")),
    Column("educational_environment", Text, nullable=False,
           server_default=text("''")),
    Column("sped_program_entry_date", Text, nullable=False,
           server_default=text("''")),
    Column("sped_program_exit_date", Text, nullable=False,
           server_default=text("''")),
    Column("sped_exit_reason", Text, nullable=False, server_default=text("''")),
    Column("iep_start_date", Text, nullable=False, server_default=text("''")),
    Column("iep_review_date", Text, nullable=False, server_default=text("''")),
    Column("is_transition_plan_required", Integer, nullable=False,
           server_default=text("0")),
    Column("lre_percentage", Text, nullable=False, server_default=text("''")),
    Column("is_early_childhood", Integer, nullable=False,
           server_default=text("0")),
    Column("early_childhood_environment", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "disability_category IN ('AUT','DB','DD','ED','HI','ID','MD','OHI','OI',"
        "'SLD','SLI','TBI','VI','')",
        name="ck_sr_sped_placement_disability_category"),
    CheckConstraint(
        "educational_environment IN ('RC_80','RC_40_79','RC_LT40','SC','SS',"
        "'RF','HH','')",
        name="ck_sr_sped_placement_educational_environment"),
    CheckConstraint(
        "sped_exit_reason IN ('graduated','dropped_out','reached_max_age',"
        "'transferred','died','not_eligible','')",
        name="ck_sr_sped_placement_sped_exit_reason"),
    CheckConstraint(
        "early_childhood_environment IN ('early_childhood_program','home',"
        "'part_time_ec_part_time_home','')",
        name="ck_sr_sped_placement_early_childhood_environment"),
    UniqueConstraint("student_id", "school_year",
                     name="uq_sr_sped_placement_student_year"),
)

Index("idx_sr_sped_student_year", SR_SPED_PLACEMENT.c.student_id,
      SR_SPED_PLACEMENT.c.school_year)
Index("idx_sr_sped_company_year", SR_SPED_PLACEMENT.c.company_id,
      SR_SPED_PLACEMENT.c.school_year)
Index("idx_sr_sped_disability", SR_SPED_PLACEMENT.c.company_id,
      SR_SPED_PLACEMENT.c.disability_category, SR_SPED_PLACEMENT.c.school_year)
Index("idx_sr_sped_environment", SR_SPED_PLACEMENT.c.company_id,
      SR_SPED_PLACEMENT.c.educational_environment,
      SR_SPED_PLACEMENT.c.school_year)

# ---------------------------------------------------------------------------
# 10. sr_sped_service (owned by demographics)
# ---------------------------------------------------------------------------
SR_SPED_SERVICE = Table(
    "sr_sped_service", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("sped_placement_id", Text,
           ForeignKey("sr_sped_placement.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("service_type", Text, nullable=False, server_default=text("''")),
    Column("provider_type", Text, nullable=False, server_default=text("''")),
    Column("minutes_per_week", Integer, nullable=False,
           server_default=text("0")),
    Column("start_date", Text, nullable=False, server_default=text("''")),
    Column("end_date", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "service_type IN ('speech_language','occupational_therapy',"
        "'physical_therapy','counseling','audiology','orientation_mobility',"
        "'special_transportation','behavior_intervention','vision_services',"
        "'other')",
        name="ck_sr_sped_service_service_type"),
    CheckConstraint(
        "provider_type IN ('school_employed','contracted','')",
        name="ck_sr_sped_service_provider_type"),
)

Index("idx_sr_sped_service_placement", SR_SPED_SERVICE.c.sped_placement_id)
Index("idx_sr_sped_service_student", SR_SPED_SERVICE.c.student_id)
Index("idx_sr_sped_service_type", SR_SPED_SERVICE.c.company_id,
      SR_SPED_SERVICE.c.service_type)

# ---------------------------------------------------------------------------
# 11. sr_student_supplement (owned by demographics)
# ---------------------------------------------------------------------------
SR_STUDENT_SUPPLEMENT = Table(
    "sr_student_supplement", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT"),
           nullable=False, unique=True, server_default=text("''")),
    Column("ssid", Text, nullable=False, server_default=text("''")),
    Column("ssid_state_code", Text, nullable=False, server_default=text("''")),
    Column("ssid_status", Text, nullable=False, server_default=text("'pending'")),
    Column("is_hispanic_latino", Integer, nullable=False,
           server_default=text("0")),
    Column("race_codes", Text, nullable=False, server_default=text("'[]'")),
    Column("race_federal_rollup", Text, nullable=False,
           server_default=text("''")),
    Column("is_el", Integer, nullable=False, server_default=text("0")),
    Column("el_entry_date", Text, nullable=False, server_default=text("''")),
    Column("home_language_code", Text, nullable=False,
           server_default=text("''")),
    Column("native_language_code", Text, nullable=False,
           server_default=text("''")),
    Column("english_proficiency_level", Text, nullable=False,
           server_default=text("''")),
    Column("english_proficiency_instrument", Text, nullable=False,
           server_default=text("''")),
    Column("el_exit_date", Text, nullable=False, server_default=text("''")),
    Column("is_rfep", Integer, nullable=False, server_default=text("0")),
    Column("rfep_date", Text, nullable=False, server_default=text("''")),
    Column("is_sped", Integer, nullable=False, server_default=text("0")),
    Column("is_504", Integer, nullable=False, server_default=text("0")),
    Column("sped_entry_date", Text, nullable=False, server_default=text("''")),
    Column("sped_exit_date", Text, nullable=False, server_default=text("''")),
    Column("is_economically_disadvantaged", Integer, nullable=False,
           server_default=text("0")),
    Column("lunch_program_status", Text, nullable=False,
           server_default=text("''")),
    Column("is_migrant", Integer, nullable=False, server_default=text("0")),
    Column("is_homeless", Integer, nullable=False, server_default=text("0")),
    Column("homeless_primary_nighttime_residence", Text, nullable=False,
           server_default=text("''")),
    Column("is_foster_care", Integer, nullable=False, server_default=text("0")),
    Column("is_military_connected", Integer, nullable=False,
           server_default=text("0")),
    Column("military_connection_type", Text, nullable=False,
           server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "ssid_status IN ('pending','assigned','not_applicable')",
        name="ck_sr_student_supplement_ssid_status"),
    CheckConstraint(
        "race_federal_rollup IN ('WHITE','BLACK_OR_AFRICAN_AMERICAN','ASIAN',"
        "'AMERICAN_INDIAN_OR_ALASKA_NATIVE',"
        "'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER','TWO_OR_MORE_RACES',"
        "'HISPANIC_OR_LATINO','')",
        name="ck_sr_student_supplement_race_federal_rollup"),
    CheckConstraint(
        "english_proficiency_instrument IN ('WIDA_ACCESS','ELPAC','TELPAS',"
        "'LAS_LINKS','IPT','OTHER','')",
        name="ck_sr_student_supplement_english_proficiency_instrument"),
    CheckConstraint(
        "lunch_program_status IN ('free','reduced','paid',"
        "'direct_certification','')",
        name="ck_sr_student_supplement_lunch_program_status"),
    CheckConstraint(
        "homeless_primary_nighttime_residence IN ('sheltered','unsheltered',"
        "'doubled_up','hotel_motel','')",
        name="ck_sr_student_supplement_homeless_residence"),
    CheckConstraint(
        "military_connection_type IN ('active_duty','veteran','national_guard','')",
        name="ck_sr_student_supplement_military_connection_type"),
)

Index("idx_sr_supplement_student", SR_STUDENT_SUPPLEMENT.c.student_id)
Index("idx_sr_supplement_ssid", SR_STUDENT_SUPPLEMENT.c.ssid,
      SR_STUDENT_SUPPLEMENT.c.ssid_state_code)
Index("idx_sr_supplement_company_el", SR_STUDENT_SUPPLEMENT.c.company_id,
      SR_STUDENT_SUPPLEMENT.c.is_el)
Index("idx_sr_supplement_company_sped", SR_STUDENT_SUPPLEMENT.c.company_id,
      SR_STUDENT_SUPPLEMENT.c.is_sped)
Index("idx_sr_supplement_company_econ", SR_STUDENT_SUPPLEMENT.c.company_id,
      SR_STUDENT_SUPPLEMENT.c.is_economically_disadvantaged)
Index("idx_sr_supplement_ssid_status", SR_STUDENT_SUPPLEMENT.c.company_id,
      SR_STUDENT_SUPPLEMENT.c.ssid_status)
Index("idx_sr_supplement_race_rollup", SR_STUDENT_SUPPLEMENT.c.company_id,
      SR_STUDENT_SUPPLEMENT.c.race_federal_rollup)

# ---------------------------------------------------------------------------
# 12. sr_submission (owned by submission_tracking)
# ---------------------------------------------------------------------------
SR_SUBMISSION = Table(
    "sr_submission", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("collection_window_id", Text,
           ForeignKey("sr_collection_window.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("snapshot_id", Text,
           ForeignKey("sr_snapshot.id", ondelete="RESTRICT")),
    Column("submission_type", Text, nullable=False,
           server_default=text("'initial'")),
    Column("submission_method", Text, nullable=False,
           server_default=text("''")),
    Column("submitted_at", Text, nullable=False, server_default=text("''")),
    Column("submitted_by", Text, nullable=False, server_default=text("''")),
    Column("records_submitted", Integer, nullable=False,
           server_default=text("0")),
    Column("records_accepted", Integer, nullable=False,
           server_default=text("0")),
    Column("records_rejected", Integer, nullable=False,
           server_default=text("0")),
    Column("submission_status", Text, nullable=False,
           server_default=text("'pending'")),
    Column("state_confirmation_id", Text, nullable=False,
           server_default=text("''")),
    Column("state_confirmed_at", Text, nullable=False,
           server_default=text("''")),
    Column("amendment_reason", Text, nullable=False, server_default=text("''")),
    # Self-referential: an amendment points at the submission it amends.
    Column("linked_submission_id", Text,
           ForeignKey("sr_submission.id", ondelete="RESTRICT")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "submission_type IN ('initial','amendment','correction')",
        name="ck_sr_submission_submission_type"),
    CheckConstraint(
        "submission_method IN ('edfi_api','flat_file','manual_portal')",
        name="ck_sr_submission_submission_method"),
    CheckConstraint(
        "submission_status IN ('pending','in_progress','completed','failed',"
        "'certified')",
        name="ck_sr_submission_submission_status"),
)

Index("idx_sr_submission_window", SR_SUBMISSION.c.collection_window_id)
Index("idx_sr_submission_company_status", SR_SUBMISSION.c.company_id,
      SR_SUBMISSION.c.submission_status)
Index("idx_sr_submission_series", SR_SUBMISSION.c.naming_series)
Index("idx_sr_submission_linked", SR_SUBMISSION.c.linked_submission_id)

# ---------------------------------------------------------------------------
# 13. sr_submission_error (owned by submission_tracking)
# ---------------------------------------------------------------------------
SR_SUBMISSION_ERROR = Table(
    "sr_submission_error", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("collection_window_id", Text,
           ForeignKey("sr_collection_window.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("submission_id", Text,
           ForeignKey("sr_submission.id", ondelete="RESTRICT")),
    Column("error_source", Text, nullable=False, server_default=text("''")),
    Column("error_level", Text, nullable=False, server_default=text("''")),
    Column("severity", Text, nullable=False, server_default=text("''")),
    Column("error_code", Text, nullable=False, server_default=text("''")),
    Column("error_category", Text, nullable=False, server_default=text("''")),
    Column("error_message", Text, nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT")),
    Column("staff_id", Text, ForeignKey("employee.id", ondelete="RESTRICT")),
    Column("record_type", Text, nullable=False, server_default=text("''")),
    Column("field_name", Text, nullable=False, server_default=text("''")),
    Column("field_value", Text, nullable=False, server_default=text("''")),
    Column("resolution_status", Text, nullable=False,
           server_default=text("'open'")),
    Column("resolution_method", Text, nullable=False,
           server_default=text("''")),
    Column("resolved_by", Text, nullable=False, server_default=text("''")),
    Column("resolved_at", Text, nullable=False, server_default=text("''")),
    Column("resolution_notes", Text, nullable=False, server_default=text("''")),
    Column("assigned_to", Text, nullable=False, server_default=text("''")),
    Column("assigned_at", Text, nullable=False, server_default=text("''")),
    Column("state_ticket_id", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "error_source IN ('edfi_api','state_portal','internal_validation')",
        name="ck_sr_submission_error_error_source"),
    CheckConstraint(
        "error_level IN ('1','2','3')",
        name="ck_sr_submission_error_error_level"),
    CheckConstraint(
        "severity IN ('critical','major','minor','warning')",
        name="ck_sr_submission_error_severity"),
    CheckConstraint(
        "error_category IN ('enrollment','demographics','sped','el',"
        "'attendance','discipline','staff','calendar','other')",
        name="ck_sr_submission_error_error_category"),
    CheckConstraint(
        "resolution_status IN ('open','in_progress','resolved','deferred',"
        "'state_waived')",
        name="ck_sr_submission_error_resolution_status"),
    CheckConstraint(
        "resolution_method IN ('data_corrected','descriptor_mapped',"
        "'state_exception','data_not_available','')",
        name="ck_sr_submission_error_resolution_method"),
)

Index("idx_sr_sub_error_window_severity",
      SR_SUBMISSION_ERROR.c.collection_window_id,
      SR_SUBMISSION_ERROR.c.severity, SR_SUBMISSION_ERROR.c.resolution_status)
Index("idx_sr_sub_error_student", SR_SUBMISSION_ERROR.c.student_id,
      SR_SUBMISSION_ERROR.c.resolution_status)
Index("idx_sr_sub_error_submission", SR_SUBMISSION_ERROR.c.submission_id)
Index("idx_sr_sub_error_company_open", SR_SUBMISSION_ERROR.c.company_id,
      SR_SUBMISSION_ERROR.c.resolution_status)
Index("idx_sr_sub_error_assigned", SR_SUBMISSION_ERROR.c.assigned_to,
      SR_SUBMISSION_ERROR.c.resolution_status)
Index("idx_sr_sub_error_category", SR_SUBMISSION_ERROR.c.company_id,
      SR_SUBMISSION_ERROR.c.error_category, SR_SUBMISSION_ERROR.c.severity)

# ---------------------------------------------------------------------------
# 14. sr_validation_rule (owned by data_validation)
#
# The only table here with no `company_id`: validation rules are catalogue rows,
# not per-company data. Asymmetry preserved from the shipped DDL.
# ---------------------------------------------------------------------------
SR_VALIDATION_RULE = Table(
    "sr_validation_rule", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("rule_code", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("category", Text, nullable=False, server_default=text("''")),
    Column("severity", Text, nullable=False, server_default=text("''")),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("applicable_windows", Text, nullable=False,
           server_default=text("'[]'")),
    Column("applicable_states", Text, nullable=False,
           server_default=text("'[]'")),
    Column("is_federal_rule", Integer, nullable=False, server_default=text("0")),
    Column("sql_query", Text, nullable=False, server_default=text("''")),
    Column("error_message_template", Text, nullable=False,
           server_default=text("''")),
    Column("is_active", Integer, nullable=False, server_default=text("1")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "category IN ('enrollment','demographics','sped','el','attendance',"
        "'discipline','staff','calendar')",
        name="ck_sr_validation_rule_category"),
    CheckConstraint(
        "severity IN ('critical','major','minor','warning')",
        name="ck_sr_validation_rule_severity"),
)

Index("idx_sr_validation_rule_category", SR_VALIDATION_RULE.c.category,
      SR_VALIDATION_RULE.c.severity, SR_VALIDATION_RULE.c.is_active)
Index("idx_sr_validation_rule_code", SR_VALIDATION_RULE.c.rule_code)
Index("idx_sr_validation_rule_federal", SR_VALIDATION_RULE.c.is_federal_rule,
      SR_VALIDATION_RULE.c.is_active)

# ---------------------------------------------------------------------------
# 15. sr_validation_result (owned by data_validation)
# ---------------------------------------------------------------------------
SR_VALIDATION_RESULT = Table(
    "sr_validation_result", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("collection_window_id", Text,
           ForeignKey("sr_collection_window.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("run_at", Text, nullable=False, server_default=text("''")),
    Column("run_by", Text, nullable=False, server_default=text("''")),
    Column("rule_id", Text,
           ForeignKey("sr_validation_rule.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT")),
    Column("staff_id", Text, ForeignKey("employee.id", ondelete="RESTRICT")),
    Column("error_detail", Text, nullable=False, server_default=text("''")),
    Column("is_resolved", Integer, nullable=False, server_default=text("0")),
    Column("resolved_at", Text, nullable=False, server_default=text("''")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
)

Index("idx_sr_validation_result_window",
      SR_VALIDATION_RESULT.c.collection_window_id,
      SR_VALIDATION_RESULT.c.is_resolved)
Index("idx_sr_validation_result_rule", SR_VALIDATION_RESULT.c.rule_id,
      SR_VALIDATION_RESULT.c.collection_window_id)
Index("idx_sr_validation_result_student", SR_VALIDATION_RESULT.c.student_id,
      SR_VALIDATION_RESULT.c.collection_window_id)
Index("idx_sr_validation_result_run",
      SR_VALIDATION_RESULT.c.collection_window_id,
      SR_VALIDATION_RESULT.c.run_at)


def _require_foundation(db_path):
    """Refuse to install onto a database with no ERPClaw foundation.

    Same check and same message as before the conversion; the pre-conversion
    version read `sqlite_master` directly, which is a hard error on PostgreSQL
    rather than a false, so it is asked through the seam instead.
    """
    missing = [t for t in REQUIRED_FOUNDATION if not table_exists(t, db_path)]
    if missing:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)


def create_educlaw_statereport_tables(db_path):
    """Create the state reporting tables and indexes on whichever backend is configured.

    Same contract as before the ADR-0034 conversion: the shared educlaw base
    tables are ensured first, then this module's own fifteen. Idempotent, and the
    returned counts are what was ACTUALLY created rather than what was declared —
    so they count the fifteen owned tables, never educlaw core's 32.
    """
    _require_foundation(db_path)

    # educlaw core's base schema, created here because a sub-vertical can be
    # installed before its parent. Another module's installer is not this
    # conversion's to rewrite, so it keeps running exactly as it does today.
    conn = get_connection(db_path)
    try:
        ensure_educlaw_base_tables(conn)
        conn.commit()
    finally:
        conn.close()

    result = provision(METADATA, db_path)
    return {
        "database": db_path,
        "tables": result["tables"],
        "indexes": result["indexes"],
    }


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    result = create_educlaw_statereport_tables(db_path)
    print(f"{DISPLAY_NAME} schema created in {result['database']}")
    print(f"  Tables: {result['tables']}")
    print(f"  Indexes: {result['indexes']}")
