#!/usr/bin/env python3
"""EduClaw schema — 47 tables (32 parent + 15 new).

Generated by ERPForge Schema DSL (generate_schema.py)
Parent: educlaw | Tables: 47 | Indexes: 141

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Run: python3 init_db.py [db_path]
"""
import os
import sqlite3
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from educlaw_base_schema import ensure_educlaw_base_tables


DEFAULT_DB_PATH = os.path.expanduser("~/.openclaw/erpclaw/data.sqlite")


def create_educlaw_statereport_tables(db_path):
    conn = sqlite3.connect(db_path)
    from erpclaw_lib.db import setup_pragmas
    setup_pragmas(conn)

    # Verify foundation exists
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()]
    if "company" not in tables:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)

    # Ensure parent schema (educlaw base tables) exists
    ensure_educlaw_base_tables(conn)


    conn.executescript("""
        -- ==========================================================
        -- EduClaw Domain Tables
        -- Generated by ERPForge Schema DSL
        -- Tables: 15 | Columns: 253
        -- ==========================================================

        -- NOTE: Discipline tables (educlaw_k12_discipline_incident,
        -- educlaw_k12_discipline_student, educlaw_k12_discipline_action)
        -- are owned by educlaw-k12. State reporting reads them, does not create them.

        -- sr_edfi_config (owned by ed_fi)
        CREATE TABLE IF NOT EXISTS sr_edfi_config (
            id TEXT PRIMARY KEY,
            profile_name TEXT NOT NULL DEFAULT '',
            state_code TEXT NOT NULL DEFAULT '',
            school_year INTEGER NOT NULL DEFAULT 0,
            ods_base_url TEXT NOT NULL DEFAULT '',
            oauth_token_url TEXT NOT NULL DEFAULT '',
            oauth_client_id TEXT NOT NULL DEFAULT '',
            oauth_client_secret_encrypted TEXT NOT NULL DEFAULT '',
            api_version TEXT NOT NULL DEFAULT '7' CHECK(api_version IN ('5','6','7')),
            is_active INTEGER NOT NULL DEFAULT 1,
            last_tested_at TEXT NOT NULL DEFAULT '',
            last_token_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_sr_edfi_config_company_state_year UNIQUE (company_id, state_code, school_year)
        );

        -- sr_collection_window (owned by state_reporting)
        CREATE TABLE IF NOT EXISTS sr_collection_window (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL DEFAULT '',
            state_code TEXT NOT NULL DEFAULT '',
            window_type TEXT NOT NULL DEFAULT '' CHECK(window_type IN ('fall_enrollment','fall_sped','winter_update','spring_enrollment','eoy_attendance','eoy_discipline','eoy_grades','staffing','crdc','summer_correction')),
            school_year INTEGER NOT NULL DEFAULT 0,
            academic_year_id TEXT REFERENCES educlaw_academic_year(id) ON DELETE RESTRICT,
            open_date TEXT NOT NULL DEFAULT '',
            close_date TEXT NOT NULL DEFAULT '',
            snapshot_date TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'upcoming' CHECK(status IN ('upcoming','open','data_entry','validation','snapshot','submitted','certified','closed')),
            required_data_categories TEXT NOT NULL DEFAULT '[]',
            description TEXT NOT NULL DEFAULT '',
            is_federal_required INTEGER NOT NULL DEFAULT 0,
            edfi_config_id TEXT REFERENCES sr_edfi_config(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_sr_collection_window_company_state_type_year UNIQUE (company_id, state_code, window_type, school_year)
        );

        -- sr_edfi_descriptor_map (owned by ed_fi)
        CREATE TABLE IF NOT EXISTS sr_edfi_descriptor_map (
            id TEXT PRIMARY KEY,
            config_id TEXT NOT NULL DEFAULT '' REFERENCES sr_edfi_config(id) ON DELETE RESTRICT,
            descriptor_type TEXT NOT NULL DEFAULT '' CHECK(descriptor_type IN ('grade_level','race','sex','attendance_event','disability','language','exit_type','entry_type','discipline_behavior','discipline_action','sped_environment','program_type','credential_type','course_level','homeless_residence')),
            internal_code TEXT NOT NULL DEFAULT '',
            edfi_descriptor_uri TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_sr_descriptor_config_type_code UNIQUE (config_id, descriptor_type, internal_code)
        );

        -- sr_edfi_sync_log (owned by ed_fi)
        CREATE TABLE IF NOT EXISTS sr_edfi_sync_log (
            id TEXT PRIMARY KEY,
            config_id TEXT NOT NULL DEFAULT '' REFERENCES sr_edfi_config(id) ON DELETE RESTRICT,
            collection_window_id TEXT REFERENCES sr_collection_window(id) ON DELETE RESTRICT,
            resource_type TEXT NOT NULL DEFAULT '',
            operation TEXT NOT NULL DEFAULT '' CHECK(operation IN ('POST','PUT','DELETE','GET')),
            internal_id TEXT NOT NULL DEFAULT '',
            edfi_natural_key TEXT NOT NULL DEFAULT '',
            http_status INTEGER NOT NULL DEFAULT 0,
            request_payload_hash TEXT NOT NULL DEFAULT '',
            response_body TEXT NOT NULL DEFAULT '',
            sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('success','error','retry','pending','skipped')),
            retry_count INTEGER NOT NULL DEFAULT 0,
            synced_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        -- sr_el_program (owned by demographics)
        CREATE TABLE IF NOT EXISTS sr_el_program (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            school_year INTEGER NOT NULL DEFAULT 0,
            program_type TEXT NOT NULL DEFAULT '' CHECK(program_type IN ('pull_out','push_in','sheltered_english','dual_language','tbe_transitional','tbe_developmental','waiver','content_based')),
            entry_date TEXT NOT NULL DEFAULT '',
            exit_date TEXT NOT NULL DEFAULT '',
            exit_reason TEXT NOT NULL DEFAULT '' CHECK(exit_reason IN ('reclassified','parent_waiver','transferred','graduated','')),
            english_proficiency_assessed_date TEXT NOT NULL DEFAULT '',
            proficiency_level TEXT NOT NULL DEFAULT '',
            proficiency_instrument TEXT NOT NULL DEFAULT '' CHECK(proficiency_instrument IN ('WIDA_ACCESS','ELPAC','TELPAS','LAS_LINKS','IPT','OTHER','')),
            is_parent_waived INTEGER NOT NULL DEFAULT 0,
            waiver_date TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_org_mapping (owned by ed_fi)
        CREATE TABLE IF NOT EXISTS sr_org_mapping (
            id TEXT PRIMARY KEY,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            nces_lea_id TEXT NOT NULL DEFAULT '',
            nces_school_id TEXT NOT NULL DEFAULT '',
            state_code TEXT NOT NULL DEFAULT '' CHECK(length(state_code)=2 OR state_code=''),
            state_lea_id TEXT NOT NULL DEFAULT '',
            state_school_id TEXT NOT NULL DEFAULT '',
            edfi_lea_id TEXT NOT NULL DEFAULT '',
            edfi_school_id TEXT NOT NULL DEFAULT '',
            crdc_school_id TEXT NOT NULL DEFAULT '',
            is_title_i_school INTEGER NOT NULL DEFAULT 0,
            title_i_status TEXT NOT NULL DEFAULT '' CHECK(title_i_status IN ('targeted_assistance','schoolwide','not_title_i','')),
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_sr_org_mapping_company_state_school UNIQUE (company_id, state_code, nces_school_id)
        );

        -- sr_snapshot (owned by state_reporting)
        CREATE TABLE IF NOT EXISTS sr_snapshot (
            id TEXT PRIMARY KEY,
            collection_window_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES sr_collection_window(id) ON DELETE RESTRICT,
            snapshot_taken_at TEXT NOT NULL DEFAULT '',
            snapshot_taken_by TEXT NOT NULL DEFAULT '',
            total_students INTEGER NOT NULL DEFAULT 0,
            total_enrollment INTEGER NOT NULL DEFAULT 0,
            total_sped INTEGER NOT NULL DEFAULT 0,
            total_el INTEGER NOT NULL DEFAULT 0,
            total_economically_disadvantaged INTEGER NOT NULL DEFAULT 0,
            total_homeless INTEGER NOT NULL DEFAULT 0,
            ada_total TEXT NOT NULL DEFAULT '',
            adm_total TEXT NOT NULL DEFAULT '',
            chronic_absenteeism_count INTEGER NOT NULL DEFAULT 0,
            error_count_at_snapshot INTEGER NOT NULL DEFAULT 0,
            snapshot_status TEXT NOT NULL DEFAULT 'draft' CHECK(snapshot_status IN ('draft','finalized','certified')),
            certified_by TEXT NOT NULL DEFAULT '',
            certified_at TEXT NOT NULL DEFAULT '',
            certification_notes TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_snapshot_record (owned by state_reporting)
        CREATE TABLE IF NOT EXISTS sr_snapshot_record (
            id TEXT PRIMARY KEY,
            snapshot_id TEXT NOT NULL DEFAULT '' REFERENCES sr_snapshot(id) ON DELETE RESTRICT,
            student_id TEXT REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            record_type TEXT NOT NULL DEFAULT '' CHECK(record_type IN ('student_enrollment','attendance_summary','sped_placement','el_program','discipline_summary','staff_assignment')),
            data_json TEXT NOT NULL DEFAULT '{}',
            school_year INTEGER NOT NULL DEFAULT 0,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        -- sr_sped_placement (owned by demographics)
        CREATE TABLE IF NOT EXISTS sr_sped_placement (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            school_year INTEGER NOT NULL DEFAULT 0,
            disability_category TEXT NOT NULL DEFAULT '' CHECK(disability_category IN ('AUT','DB','DD','ED','HI','ID','MD','OHI','OI','SLD','SLI','TBI','VI','')),
            secondary_disability TEXT NOT NULL DEFAULT '',
            educational_environment TEXT NOT NULL DEFAULT '' CHECK(educational_environment IN ('RC_80','RC_40_79','RC_LT40','SC','SS','RF','HH','')),
            sped_program_entry_date TEXT NOT NULL DEFAULT '',
            sped_program_exit_date TEXT NOT NULL DEFAULT '',
            sped_exit_reason TEXT NOT NULL DEFAULT '' CHECK(sped_exit_reason IN ('graduated','dropped_out','reached_max_age','transferred','died','not_eligible','')),
            iep_start_date TEXT NOT NULL DEFAULT '',
            iep_review_date TEXT NOT NULL DEFAULT '',
            is_transition_plan_required INTEGER NOT NULL DEFAULT 0,
            lre_percentage TEXT NOT NULL DEFAULT '',
            is_early_childhood INTEGER NOT NULL DEFAULT 0,
            early_childhood_environment TEXT NOT NULL DEFAULT '' CHECK(early_childhood_environment IN ('early_childhood_program','home','part_time_ec_part_time_home','')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            CONSTRAINT uq_sr_sped_placement_student_year UNIQUE (student_id, school_year)
        );

        -- sr_sped_service (owned by demographics)
        CREATE TABLE IF NOT EXISTS sr_sped_service (
            id TEXT PRIMARY KEY,
            sped_placement_id TEXT NOT NULL DEFAULT '' REFERENCES sr_sped_placement(id) ON DELETE RESTRICT,
            student_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            service_type TEXT NOT NULL DEFAULT '' CHECK(service_type IN ('speech_language','occupational_therapy','physical_therapy','counseling','audiology','orientation_mobility','special_transportation','behavior_intervention','vision_services','other')),
            provider_type TEXT NOT NULL DEFAULT '' CHECK(provider_type IN ('school_employed','contracted','')),
            minutes_per_week INTEGER NOT NULL DEFAULT 0,
            start_date TEXT NOT NULL DEFAULT '',
            end_date TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_student_supplement (owned by demographics)
        CREATE TABLE IF NOT EXISTS sr_student_supplement (
            id TEXT PRIMARY KEY,
            student_id TEXT NOT NULL UNIQUE DEFAULT '' REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            ssid TEXT NOT NULL DEFAULT '',
            ssid_state_code TEXT NOT NULL DEFAULT '',
            ssid_status TEXT NOT NULL DEFAULT 'pending' CHECK(ssid_status IN ('pending','assigned','not_applicable')),
            is_hispanic_latino INTEGER NOT NULL DEFAULT 0,
            race_codes TEXT NOT NULL DEFAULT '[]',
            race_federal_rollup TEXT NOT NULL DEFAULT '' CHECK(race_federal_rollup IN ('WHITE','BLACK_OR_AFRICAN_AMERICAN','ASIAN','AMERICAN_INDIAN_OR_ALASKA_NATIVE','NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER','TWO_OR_MORE_RACES','HISPANIC_OR_LATINO','')),
            is_el INTEGER NOT NULL DEFAULT 0,
            el_entry_date TEXT NOT NULL DEFAULT '',
            home_language_code TEXT NOT NULL DEFAULT '',
            native_language_code TEXT NOT NULL DEFAULT '',
            english_proficiency_level TEXT NOT NULL DEFAULT '',
            english_proficiency_instrument TEXT NOT NULL DEFAULT '' CHECK(english_proficiency_instrument IN ('WIDA_ACCESS','ELPAC','TELPAS','LAS_LINKS','IPT','OTHER','')),
            el_exit_date TEXT NOT NULL DEFAULT '',
            is_rfep INTEGER NOT NULL DEFAULT 0,
            rfep_date TEXT NOT NULL DEFAULT '',
            is_sped INTEGER NOT NULL DEFAULT 0,
            is_504 INTEGER NOT NULL DEFAULT 0,
            sped_entry_date TEXT NOT NULL DEFAULT '',
            sped_exit_date TEXT NOT NULL DEFAULT '',
            is_economically_disadvantaged INTEGER NOT NULL DEFAULT 0,
            lunch_program_status TEXT NOT NULL DEFAULT '' CHECK(lunch_program_status IN ('free','reduced','paid','direct_certification','')),
            is_migrant INTEGER NOT NULL DEFAULT 0,
            is_homeless INTEGER NOT NULL DEFAULT 0,
            homeless_primary_nighttime_residence TEXT NOT NULL DEFAULT '' CHECK(homeless_primary_nighttime_residence IN ('sheltered','unsheltered','doubled_up','hotel_motel','')),
            is_foster_care INTEGER NOT NULL DEFAULT 0,
            is_military_connected INTEGER NOT NULL DEFAULT 0,
            military_connection_type TEXT NOT NULL DEFAULT '' CHECK(military_connection_type IN ('active_duty','veteran','national_guard','')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_submission (owned by submission_tracking)
        CREATE TABLE IF NOT EXISTS sr_submission (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            collection_window_id TEXT NOT NULL DEFAULT '' REFERENCES sr_collection_window(id) ON DELETE RESTRICT,
            snapshot_id TEXT REFERENCES sr_snapshot(id) ON DELETE RESTRICT,
            submission_type TEXT NOT NULL DEFAULT 'initial' CHECK(submission_type IN ('initial','amendment','correction')),
            submission_method TEXT NOT NULL DEFAULT '' CHECK(submission_method IN ('edfi_api','flat_file','manual_portal')),
            submitted_at TEXT NOT NULL DEFAULT '',
            submitted_by TEXT NOT NULL DEFAULT '',
            records_submitted INTEGER NOT NULL DEFAULT 0,
            records_accepted INTEGER NOT NULL DEFAULT 0,
            records_rejected INTEGER NOT NULL DEFAULT 0,
            submission_status TEXT NOT NULL DEFAULT 'pending' CHECK(submission_status IN ('pending','in_progress','completed','failed','certified')),
            state_confirmation_id TEXT NOT NULL DEFAULT '',
            state_confirmed_at TEXT NOT NULL DEFAULT '',
            amendment_reason TEXT NOT NULL DEFAULT '',
            linked_submission_id TEXT REFERENCES sr_submission(id) ON DELETE RESTRICT,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_submission_error (owned by submission_tracking)
        CREATE TABLE IF NOT EXISTS sr_submission_error (
            id TEXT PRIMARY KEY,
            collection_window_id TEXT NOT NULL DEFAULT '' REFERENCES sr_collection_window(id) ON DELETE RESTRICT,
            submission_id TEXT REFERENCES sr_submission(id) ON DELETE RESTRICT,
            error_source TEXT NOT NULL DEFAULT '' CHECK(error_source IN ('edfi_api','state_portal','internal_validation')),
            error_level TEXT NOT NULL DEFAULT '' CHECK(error_level IN ('1','2','3')),
            severity TEXT NOT NULL DEFAULT '' CHECK(severity IN ('critical','major','minor','warning')),
            error_code TEXT NOT NULL DEFAULT '',
            error_category TEXT NOT NULL DEFAULT '' CHECK(error_category IN ('enrollment','demographics','sped','el','attendance','discipline','staff','calendar','other')),
            error_message TEXT NOT NULL DEFAULT '',
            student_id TEXT REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            staff_id TEXT REFERENCES employee(id) ON DELETE RESTRICT,
            record_type TEXT NOT NULL DEFAULT '',
            field_name TEXT NOT NULL DEFAULT '',
            field_value TEXT NOT NULL DEFAULT '',
            resolution_status TEXT NOT NULL DEFAULT 'open' CHECK(resolution_status IN ('open','in_progress','resolved','deferred','state_waived')),
            resolution_method TEXT NOT NULL DEFAULT '' CHECK(resolution_method IN ('data_corrected','descriptor_mapped','state_exception','data_not_available','')),
            resolved_by TEXT NOT NULL DEFAULT '',
            resolved_at TEXT NOT NULL DEFAULT '',
            resolution_notes TEXT NOT NULL DEFAULT '',
            assigned_to TEXT NOT NULL DEFAULT '',
            assigned_at TEXT NOT NULL DEFAULT '',
            state_ticket_id TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_validation_rule (owned by data_validation)
        CREATE TABLE IF NOT EXISTS sr_validation_rule (
            id TEXT PRIMARY KEY,
            rule_code TEXT NOT NULL UNIQUE DEFAULT '',
            category TEXT NOT NULL DEFAULT '' CHECK(category IN ('enrollment','demographics','sped','el','attendance','discipline','staff','calendar')),
            severity TEXT NOT NULL DEFAULT '' CHECK(severity IN ('critical','major','minor','warning')),
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            applicable_windows TEXT NOT NULL DEFAULT '[]',
            applicable_states TEXT NOT NULL DEFAULT '[]',
            is_federal_rule INTEGER NOT NULL DEFAULT 0,
            sql_query TEXT NOT NULL DEFAULT '',
            error_message_template TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- sr_validation_result (owned by data_validation)
        CREATE TABLE IF NOT EXISTS sr_validation_result (
            id TEXT PRIMARY KEY,
            collection_window_id TEXT NOT NULL DEFAULT '' REFERENCES sr_collection_window(id) ON DELETE RESTRICT,
            run_at TEXT NOT NULL DEFAULT '',
            run_by TEXT NOT NULL DEFAULT '',
            rule_id TEXT NOT NULL DEFAULT '' REFERENCES sr_validation_rule(id) ON DELETE RESTRICT,
            student_id TEXT REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            staff_id TEXT REFERENCES employee(id) ON DELETE RESTRICT,
            error_detail TEXT NOT NULL DEFAULT '',
            is_resolved INTEGER NOT NULL DEFAULT 0,
            resolved_at TEXT NOT NULL DEFAULT '',
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        -- ==========================================================
        -- Indexes
        -- ==========================================================

        -- Discipline indexes are owned by educlaw-k12
        CREATE INDEX IF NOT EXISTS idx_sr_edfi_config_company_state ON sr_edfi_config(company_id, state_code, is_active);
        CREATE INDEX IF NOT EXISTS idx_sr_edfi_config_year ON sr_edfi_config(company_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_collection_window_company_status ON sr_collection_window(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_sr_collection_window_year_state ON sr_collection_window(company_id, school_year, state_code);
        CREATE INDEX IF NOT EXISTS idx_sr_collection_window_type ON sr_collection_window(company_id, window_type, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_collection_window_dates ON sr_collection_window(open_date, close_date);
        CREATE INDEX IF NOT EXISTS idx_sr_descriptor_config_type ON sr_edfi_descriptor_map(config_id, descriptor_type, is_active);
        CREATE INDEX IF NOT EXISTS idx_sr_descriptor_internal ON sr_edfi_descriptor_map(config_id, internal_code);
        CREATE INDEX IF NOT EXISTS idx_sr_sync_log_resource_internal ON sr_edfi_sync_log(resource_type, internal_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sync_log_status_time ON sr_edfi_sync_log(sync_status, synced_at);
        CREATE INDEX IF NOT EXISTS idx_sr_sync_log_config_window ON sr_edfi_sync_log(config_id, collection_window_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sync_log_company_status ON sr_edfi_sync_log(company_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_sr_el_program_student_year ON sr_el_program(student_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_el_program_company_year ON sr_el_program(company_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_el_program_exit ON sr_el_program(company_id, exit_date);
        CREATE INDEX IF NOT EXISTS idx_sr_org_mapping_company_state ON sr_org_mapping(company_id, state_code);
        CREATE INDEX IF NOT EXISTS idx_sr_org_mapping_nces_lea ON sr_org_mapping(nces_lea_id);
        CREATE INDEX IF NOT EXISTS idx_sr_org_mapping_nces_school ON sr_org_mapping(nces_school_id);
        CREATE INDEX IF NOT EXISTS idx_sr_snapshot_window ON sr_snapshot(collection_window_id);
        CREATE INDEX IF NOT EXISTS idx_sr_snapshot_company_status ON sr_snapshot(company_id, snapshot_status);
        CREATE INDEX IF NOT EXISTS idx_sr_snapshot_record_snapshot_type ON sr_snapshot_record(snapshot_id, record_type);
        CREATE INDEX IF NOT EXISTS idx_sr_snapshot_record_student ON sr_snapshot_record(snapshot_id, student_id);
        CREATE INDEX IF NOT EXISTS idx_sr_snapshot_record_company ON sr_snapshot_record(company_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_student_year ON sr_sped_placement(student_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_company_year ON sr_sped_placement(company_id, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_disability ON sr_sped_placement(company_id, disability_category, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_environment ON sr_sped_placement(company_id, educational_environment, school_year);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_service_placement ON sr_sped_service(sped_placement_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_service_student ON sr_sped_service(student_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sped_service_type ON sr_sped_service(company_id, service_type);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_student ON sr_student_supplement(student_id);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_ssid ON sr_student_supplement(ssid, ssid_state_code);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_company_el ON sr_student_supplement(company_id, is_el);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_company_sped ON sr_student_supplement(company_id, is_sped);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_company_econ ON sr_student_supplement(company_id, is_economically_disadvantaged);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_ssid_status ON sr_student_supplement(company_id, ssid_status);
        CREATE INDEX IF NOT EXISTS idx_sr_supplement_race_rollup ON sr_student_supplement(company_id, race_federal_rollup);
        CREATE INDEX IF NOT EXISTS idx_sr_submission_window ON sr_submission(collection_window_id);
        CREATE INDEX IF NOT EXISTS idx_sr_submission_company_status ON sr_submission(company_id, submission_status);
        CREATE INDEX IF NOT EXISTS idx_sr_submission_series ON sr_submission(naming_series);
        CREATE INDEX IF NOT EXISTS idx_sr_submission_linked ON sr_submission(linked_submission_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_window_severity ON sr_submission_error(collection_window_id, severity, resolution_status);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_student ON sr_submission_error(student_id, resolution_status);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_submission ON sr_submission_error(submission_id);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_company_open ON sr_submission_error(company_id, resolution_status);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_assigned ON sr_submission_error(assigned_to, resolution_status);
        CREATE INDEX IF NOT EXISTS idx_sr_sub_error_category ON sr_submission_error(company_id, error_category, severity);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_rule_category ON sr_validation_rule(category, severity, is_active);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_rule_code ON sr_validation_rule(rule_code);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_rule_federal ON sr_validation_rule(is_federal_rule, is_active);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_result_window ON sr_validation_result(collection_window_id, is_resolved);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_result_rule ON sr_validation_result(rule_id, collection_window_id);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_result_student ON sr_validation_result(student_id, collection_window_id);
        CREATE INDEX IF NOT EXISTS idx_sr_validation_result_run ON sr_validation_result(collection_window_id, run_at);
    """)

    conn.commit()
    conn.close()

    print(f"EduClaw schema created: 47 tables")
    print(f"Database: {db_path}")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    create_educlaw_statereport_tables(db_path)
