#!/usr/bin/env python3
"""EduClaw LMS Integration schema — 7 owned tables on top of the educlaw base.

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to add multi-column UNIQUE constraints on mapping tables
(generator limitation: single-column inline UNIQUE only).

Parent: educlaw | Tables: 7 owned | Indexes: 30 owned

New tables (educlaw_lms_*):
  lms_sync domain    : educlaw_lms_connection, educlaw_lms_sync_log,
                       educlaw_lms_course_mapping, educlaw_lms_user_mapping
  assignments domain : educlaw_lms_assignment_mapping
  online_gradebook   : educlaw_lms_grade_sync
  course_materials   : educlaw_lms_course_material

Immutable tables (no updated_at — append-only):
  educlaw_lms_sync_log, educlaw_lms_grade_sync, educlaw_lms_course_mapping

Installing this module also materialises the 32 shared educlaw base tables via
`ensure_educlaw_base_tables`, because a sub-vertical may be installed before its
parent. Those tables are owned by educlaw CORE and are deliberately NOT declared
in this module's metadata — five sub-verticals call the same helper, and each
declaring them would be five claims of ownership on one schema.

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-lms (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]

ADR-0034 phase 2 bulk-39. This module's own schema is declared as metadata and
provisioned through `erpclaw_lib.seam`, which emits dialect-correct DDL, instead
of a hand-written ``CREATE TABLE`` block opened with ``sqlite3.connect``. The old
shape could not run on PostgreSQL at all. Conversion rules are the pilot's
(`erpclaw-esign`): seam vocabulary only, money and IDs stay TEXT, and
``primary_key=True, nullable=True`` reproduces SQLite's ``id TEXT PRIMARY KEY``
without adding a NOT NULL that never shipped.
"""
import importlib.util
import os
import sys

# The shared educlaw base schema is a sibling of this module's directory.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Bootstrap the shared lib only when it is not already reachable — an
# unconditional insert at position 0 overrides a caller that deliberately bound a
# different tree (ADR-0034 phase 2 step 2d).
if importlib.util.find_spec("erpclaw_lib") is None:
    sys.path.insert(0, os.path.join(os.path.expanduser(
        os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "lib"))

from educlaw_base_schema import ensure_educlaw_base_tables  # noqa: E402
from erpclaw_lib.db import get_connection  # noqa: E402
from erpclaw_lib.seam import (  # noqa: E402
    CheckConstraint, Column, ForeignKey, Index, Integer, MetaData, Table, Text,
    UniqueConstraint, provision, reference_table, table_exists, text,
)

DEFAULT_DB_PATH = os.path.join(os.path.expanduser(os.environ.get("ERPCLAW_HOME", "~/.openclaw/erpclaw")), "data.sqlite")
DISPLAY_NAME = "EduClaw LMS Integration"

# The pre-conversion probe asked for `company` alone. Transcribed, not widened.
REQUIRED_FOUNDATION = ["company"]

METADATA = MetaData()

# Tables this module points at but does not own — the ERPClaw foundation's
# `company` and five of educlaw core's base tables. Declared for foreign key
# resolution only and never created here; `ensure_educlaw_base_tables` above is
# what actually creates the educlaw ones. See `seam.reference_table`.
reference_table("company", METADATA)
reference_table("educlaw_academic_term", METADATA)
reference_table("educlaw_assessment", METADATA)
reference_table("educlaw_assessment_result", METADATA)
reference_table("educlaw_section", METADATA)
reference_table("educlaw_student", METADATA)

# ---------------------------------------------------------------------------
# 1. educlaw_lms_connection (owned by lms_sync)
# ---------------------------------------------------------------------------
LMS_CONNECTION = Table(
    "educlaw_lms_connection", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("display_name", Text, nullable=False, server_default=text("''")),
    Column("lms_type", Text, nullable=False, server_default=text("''")),
    Column("endpoint_url", Text, nullable=False, server_default=text("''")),
    Column("client_id", Text, nullable=False, server_default=text("''")),
    Column("client_secret_encrypted", Text, nullable=False,
           server_default=text("''")),
    Column("site_token_encrypted", Text, nullable=False,
           server_default=text("''")),
    Column("google_credentials_encrypted", Text, nullable=False,
           server_default=text("''")),
    Column("lms_site_name", Text, nullable=False, server_default=text("''")),
    Column("lms_version", Text, nullable=False, server_default=text("''")),
    Column("grade_direction", Text, nullable=False,
           server_default=text("'lms_to_sis'")),
    Column("auto_sync_enabled", Integer, nullable=False, server_default=text("0")),
    Column("sync_frequency_hours", Integer, nullable=False,
           server_default=text("0")),
    Column("last_sync_at", Text, nullable=False, server_default=text("''")),
    Column("default_course_prefix", Text, nullable=False,
           server_default=text("''")),
    Column("auto_push_assignments", Integer, nullable=False,
           server_default=text("0")),
    Column("has_dpa_signed", Integer, nullable=False, server_default=text("0")),
    Column("dpa_signed_date", Text, nullable=False, server_default=text("''")),
    Column("is_coppa_verified", Integer, nullable=False, server_default=text("0")),
    Column("coppa_cert_url", Text, nullable=False, server_default=text("''")),
    Column("allowed_data_fields", Text, nullable=False,
           server_default=text("'[]'")),
    Column("status", Text, nullable=False, server_default=text("'draft'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "lms_type IN ('canvas','moodle','google_classroom','oneroster_csv')",
        name="ck_educlaw_lms_connection_lms_type"),
    CheckConstraint(
        "grade_direction IN ('lms_to_sis','sis_to_lms','manual')",
        name="ck_educlaw_lms_connection_grade_direction"),
    CheckConstraint(
        "status IN ('draft','active','inactive','error')",
        name="ck_educlaw_lms_connection_status"),
)

Index("idx_lms_connection_company_type_status", LMS_CONNECTION.c.company_id,
      LMS_CONNECTION.c.lms_type, LMS_CONNECTION.c.status)
Index("idx_lms_connection_naming_series", LMS_CONNECTION.c.naming_series)
Index("idx_lms_connection_company_status", LMS_CONNECTION.c.company_id,
      LMS_CONNECTION.c.status)

# ---------------------------------------------------------------------------
# 2. educlaw_lms_assignment_mapping (owned by assignments)
# ---------------------------------------------------------------------------
LMS_ASSIGNMENT_MAPPING = Table(
    "educlaw_lms_assignment_mapping", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("assessment_id", Text,
           ForeignKey("educlaw_assessment.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("lms_assignment_id", Text, nullable=False, server_default=text("''")),
    Column("lms_assignment_url", Text, nullable=False, server_default=text("''")),
    Column("lms_grade_scheme", Text, nullable=False, server_default=text("''")),
    Column("push_direction", Text, nullable=False,
           server_default=text("'sis_to_lms'")),
    Column("is_published_in_lms", Integer, nullable=False,
           server_default=text("0")),
    Column("sync_status", Text, nullable=False, server_default=text("'synced'")),
    Column("last_synced_at", Text, nullable=False, server_default=text("''")),
    Column("sync_error", Text, nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "push_direction IN ('sis_to_lms','lms_to_sis')",
        name="ck_educlaw_lms_assignment_mapping_push_direction"),
    CheckConstraint(
        "sync_status IN ('synced','pending','error')",
        name="ck_educlaw_lms_assignment_mapping_sync_status"),
    UniqueConstraint("lms_connection_id", "assessment_id"),
    UniqueConstraint("lms_assignment_id", "lms_connection_id"),
)

Index("idx_lms_assign_map_conn_assess",
      LMS_ASSIGNMENT_MAPPING.c.lms_connection_id,
      LMS_ASSIGNMENT_MAPPING.c.assessment_id)
Index("idx_lms_assign_map_lms_assign_conn",
      LMS_ASSIGNMENT_MAPPING.c.lms_assignment_id,
      LMS_ASSIGNMENT_MAPPING.c.lms_connection_id)
Index("idx_lms_assign_map_sync_status",
      LMS_ASSIGNMENT_MAPPING.c.lms_connection_id,
      LMS_ASSIGNMENT_MAPPING.c.sync_status)
Index("idx_lms_assign_map_assessment", LMS_ASSIGNMENT_MAPPING.c.assessment_id)

# ---------------------------------------------------------------------------
# 3. educlaw_lms_course_mapping (owned by lms_sync)
# ---------------------------------------------------------------------------
LMS_COURSE_MAPPING = Table(
    "educlaw_lms_course_mapping", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("section_id", Text,
           ForeignKey("educlaw_section.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("lms_course_id", Text, nullable=False, server_default=text("''")),
    Column("lms_course_url", Text, nullable=False, server_default=text("''")),
    Column("lms_term_id", Text, nullable=False, server_default=text("''")),
    Column("sync_status", Text, nullable=False, server_default=text("'pending'")),
    Column("last_synced_at", Text, nullable=False, server_default=text("''")),
    Column("sync_error", Text, nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "sync_status IN ('pending','synced','error','closed')",
        name="ck_educlaw_lms_course_mapping_sync_status"),
    UniqueConstraint("lms_connection_id", "section_id"),
    UniqueConstraint("lms_course_id", "lms_connection_id"),
)

Index("idx_lms_course_map_conn_section", LMS_COURSE_MAPPING.c.lms_connection_id,
      LMS_COURSE_MAPPING.c.section_id)
Index("idx_lms_course_map_lms_course_conn", LMS_COURSE_MAPPING.c.lms_course_id,
      LMS_COURSE_MAPPING.c.lms_connection_id)
Index("idx_lms_course_map_conn_status", LMS_COURSE_MAPPING.c.lms_connection_id,
      LMS_COURSE_MAPPING.c.sync_status)

# ---------------------------------------------------------------------------
# 4. educlaw_lms_course_material (owned by course_materials)
# ---------------------------------------------------------------------------
LMS_COURSE_MATERIAL = Table(
    "educlaw_lms_course_material", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("section_id", Text,
           ForeignKey("educlaw_section.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("assessment_id", Text,
           ForeignKey("educlaw_assessment.id", ondelete="RESTRICT")),
    Column("name", Text, nullable=False, server_default=text("''")),
    Column("description", Text, nullable=False, server_default=text("''")),
    Column("material_type", Text, nullable=False, server_default=text("''")),
    Column("access_type", Text, nullable=False, server_default=text("''")),
    Column("external_url", Text, nullable=False, server_default=text("''")),
    Column("file_path", Text, nullable=False, server_default=text("''")),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT")),
    Column("lms_file_id", Text, nullable=False, server_default=text("''")),
    Column("lms_download_url", Text, nullable=False, server_default=text("''")),
    Column("is_visible_to_students", Integer, nullable=False,
           server_default=text("1")),
    Column("available_from", Text, nullable=False, server_default=text("''")),
    Column("available_until", Text, nullable=False, server_default=text("''")),
    Column("sort_order", Integer, nullable=False, server_default=text("0")),
    Column("status", Text, nullable=False, server_default=text("'active'")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("updated_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "material_type IN ('syllabus','reading','video_link',"
        "'assignment_guide','rubric','other')",
        name="ck_educlaw_lms_course_material_material_type"),
    CheckConstraint(
        "access_type IN ('url','file_attachment','lms_linked')",
        name="ck_educlaw_lms_course_material_access_type"),
    CheckConstraint(
        "status IN ('active','archived')",
        name="ck_educlaw_lms_course_material_status"),
)

Index("idx_lms_material_section_order", LMS_COURSE_MATERIAL.c.section_id,
      LMS_COURSE_MATERIAL.c.sort_order)
Index("idx_lms_material_section_type", LMS_COURSE_MATERIAL.c.section_id,
      LMS_COURSE_MATERIAL.c.material_type)
Index("idx_lms_material_assessment", LMS_COURSE_MATERIAL.c.assessment_id)
Index("idx_lms_material_company_status", LMS_COURSE_MATERIAL.c.company_id,
      LMS_COURSE_MATERIAL.c.status)
Index("idx_lms_material_lms_conn", LMS_COURSE_MATERIAL.c.lms_connection_id)

# ---------------------------------------------------------------------------
# 5. educlaw_lms_sync_log (owned by lms_sync)
# ---------------------------------------------------------------------------
LMS_SYNC_LOG = Table(
    "educlaw_lms_sync_log", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("naming_series", Text, nullable=False, unique=True,
           server_default=text("''")),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("sync_type", Text, nullable=False, server_default=text("''")),
    Column("academic_term_id", Text,
           ForeignKey("educlaw_academic_term.id", ondelete="RESTRICT")),
    Column("section_id", Text,
           ForeignKey("educlaw_section.id", ondelete="RESTRICT")),
    Column("triggered_by", Text, nullable=False, server_default=text("''")),
    Column("status", Text, nullable=False, server_default=text("'pending'")),
    Column("sections_synced", Integer, nullable=False, server_default=text("0")),
    Column("students_synced", Integer, nullable=False, server_default=text("0")),
    Column("grades_pulled", Integer, nullable=False, server_default=text("0")),
    Column("grades_applied", Integer, nullable=False, server_default=text("0")),
    Column("conflicts_flagged", Integer, nullable=False, server_default=text("0")),
    Column("errors_count", Integer, nullable=False, server_default=text("0")),
    Column("error_summary", Text, nullable=False, server_default=text("'[]'")),
    Column("started_at", Text, nullable=False, server_default=text("''")),
    Column("completed_at", Text, nullable=False, server_default=text("''")),
    Column("duration_seconds", Integer, nullable=False, server_default=text("0")),
    Column("company_id", Text, ForeignKey("company.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "sync_type IN ('roster_push','grade_pull','assignment_push',"
        "'full_sync','oneroster_export')",
        name="ck_educlaw_lms_sync_log_sync_type"),
    CheckConstraint(
        "status IN ('pending','running','completed','completed_with_errors',"
        "'failed')",
        name="ck_educlaw_lms_sync_log_status"),
)

Index("idx_lms_sync_log_conn_status", LMS_SYNC_LOG.c.lms_connection_id,
      LMS_SYNC_LOG.c.status)
Index("idx_lms_sync_log_term_type", LMS_SYNC_LOG.c.academic_term_id,
      LMS_SYNC_LOG.c.sync_type)
Index("idx_lms_sync_log_company_created", LMS_SYNC_LOG.c.company_id,
      LMS_SYNC_LOG.c.created_at)
Index("idx_lms_sync_log_naming_series", LMS_SYNC_LOG.c.naming_series)
Index("idx_lms_sync_log_section", LMS_SYNC_LOG.c.section_id)

# ---------------------------------------------------------------------------
# 6. educlaw_lms_grade_sync (owned by online_gradebook)
# ---------------------------------------------------------------------------
LMS_GRADE_SYNC = Table(
    "educlaw_lms_grade_sync", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("sync_log_id", Text,
           ForeignKey("educlaw_lms_sync_log.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("lms_assignment_id", Text, nullable=False, server_default=text("''")),
    Column("lms_user_id", Text, nullable=False, server_default=text("''")),
    Column("assessment_id", Text,
           ForeignKey("educlaw_assessment.id", ondelete="RESTRICT")),
    Column("student_id", Text,
           ForeignKey("educlaw_student.id", ondelete="RESTRICT")),
    Column("assessment_result_id", Text,
           ForeignKey("educlaw_assessment_result.id", ondelete="RESTRICT")),
    Column("lms_score", Text, nullable=False, server_default=text("''")),
    Column("lms_grade", Text, nullable=False, server_default=text("''")),
    Column("lms_submitted_at", Text, nullable=False, server_default=text("''")),
    Column("lms_graded_at", Text, nullable=False, server_default=text("''")),
    Column("is_late", Integer, nullable=False, server_default=text("0")),
    Column("is_missing", Integer, nullable=False, server_default=text("0")),
    Column("lms_comments", Text, nullable=False, server_default=text("''")),
    Column("sis_score", Text, nullable=False, server_default=text("''")),
    Column("is_conflict", Integer, nullable=False, server_default=text("0")),
    Column("conflict_type", Text, nullable=False, server_default=text("''")),
    Column("sync_status", Text, nullable=False, server_default=text("'pulled'")),
    Column("resolved_by", Text, nullable=False, server_default=text("''")),
    Column("resolved_at", Text, nullable=False, server_default=text("''")),
    Column("resolution", Text, nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "conflict_type IN ('','score_mismatch','submitted_grade_locked',"
        "'student_not_found','assignment_not_found')",
        name="ck_educlaw_lms_grade_sync_conflict_type"),
    CheckConstraint(
        "sync_status IN ('pulled','applied','conflict','skipped','error')",
        name="ck_educlaw_lms_grade_sync_sync_status"),
    CheckConstraint(
        "resolution IN ('','lms_wins','sis_wins','manual')",
        name="ck_educlaw_lms_grade_sync_resolution"),
)

Index("idx_lms_grade_sync_conn_assess_student",
      LMS_GRADE_SYNC.c.lms_connection_id, LMS_GRADE_SYNC.c.assessment_id,
      LMS_GRADE_SYNC.c.student_id)
Index("idx_lms_grade_sync_status_conflict", LMS_GRADE_SYNC.c.sync_status,
      LMS_GRADE_SYNC.c.is_conflict)
Index("idx_lms_grade_sync_assess_student_log", LMS_GRADE_SYNC.c.assessment_id,
      LMS_GRADE_SYNC.c.student_id, LMS_GRADE_SYNC.c.sync_log_id)
Index("idx_lms_grade_sync_student_status", LMS_GRADE_SYNC.c.student_id,
      LMS_GRADE_SYNC.c.sync_status)
Index("idx_lms_grade_sync_log", LMS_GRADE_SYNC.c.sync_log_id)
Index("idx_lms_grade_sync_conn_status", LMS_GRADE_SYNC.c.lms_connection_id,
      LMS_GRADE_SYNC.c.sync_status)

# ---------------------------------------------------------------------------
# 7. educlaw_lms_user_mapping (owned by lms_sync)
# ---------------------------------------------------------------------------
LMS_USER_MAPPING = Table(
    "educlaw_lms_user_mapping", METADATA,
    Column("id", Text, primary_key=True, nullable=True),
    Column("lms_connection_id", Text,
           ForeignKey("educlaw_lms_connection.id", ondelete="RESTRICT"),
           nullable=False, server_default=text("''")),
    Column("sis_user_type", Text, nullable=False, server_default=text("''")),
    Column("sis_user_id", Text, nullable=False, server_default=text("''")),
    Column("lms_user_id", Text, nullable=False, server_default=text("''")),
    Column("lms_username", Text, nullable=False, server_default=text("''")),
    Column("lms_login_email", Text, nullable=False, server_default=text("''")),
    Column("is_coppa_restricted", Integer, nullable=False,
           server_default=text("0")),
    Column("is_directory_restricted", Integer, nullable=False,
           server_default=text("0")),
    Column("sync_status", Text, nullable=False, server_default=text("'synced'")),
    Column("last_synced_at", Text, nullable=False, server_default=text("''")),
    Column("sync_error", Text, nullable=False, server_default=text("''")),
    Column("created_at", Text, nullable=False,
           server_default=text("CURRENT_TIMESTAMP")),
    Column("created_by", Text, nullable=False, server_default=text("''")),
    CheckConstraint(
        "sis_user_type IN ('student','instructor')",
        name="ck_educlaw_lms_user_mapping_sis_user_type"),
    CheckConstraint(
        "sync_status IN ('synced','pending','error','invited')",
        name="ck_educlaw_lms_user_mapping_sync_status"),
    UniqueConstraint("lms_connection_id", "sis_user_type", "sis_user_id"),
    UniqueConstraint("lms_user_id", "lms_connection_id"),
)

Index("idx_lms_user_map_conn_type_user", LMS_USER_MAPPING.c.lms_connection_id,
      LMS_USER_MAPPING.c.sis_user_type, LMS_USER_MAPPING.c.sis_user_id)
Index("idx_lms_user_map_lms_user_conn", LMS_USER_MAPPING.c.lms_user_id,
      LMS_USER_MAPPING.c.lms_connection_id)
Index("idx_lms_user_map_sync_status", LMS_USER_MAPPING.c.lms_connection_id,
      LMS_USER_MAPPING.c.sync_status)
Index("idx_lms_user_map_sis_user", LMS_USER_MAPPING.c.sis_user_id,
      LMS_USER_MAPPING.c.sis_user_type)


def _require_foundation(db_path):
    """Refuse to install onto a database with no ERPClaw foundation.

    Same check and same message as before the conversion; the pre-conversion
    version read `sqlite_master` directly, which is a hard error on PostgreSQL
    rather than a false, so it is asked through the seam instead.
    """
    missing = [t for t in REQUIRED_FOUNDATION if not table_exists(t, db_path)]
    if missing:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)


def create_educlaw_lms_tables(db_path):
    """Create the LMS tables and indexes on whichever backend is configured.

    Same contract as before the ADR-0034 conversion: the shared educlaw base
    tables are ensured first, then this module's own seven. Idempotent, and the
    returned counts are what was ACTUALLY created rather than what was declared —
    so they count the seven owned tables, never educlaw core's 32.
    """
    _require_foundation(db_path)

    # educlaw core's base schema, created here because a sub-vertical can be
    # installed before its parent. Another module's installer is not this
    # conversion's to rewrite, so it keeps running exactly as it does today.
    conn = get_connection(db_path)
    try:
        ensure_educlaw_base_tables(conn)
        conn.commit()
    finally:
        conn.close()

    result = provision(METADATA, db_path)
    return {
        "database": db_path,
        "tables": result["tables"],
        "indexes": result["indexes"],
    }


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    result = create_educlaw_lms_tables(db_path)
    print(f"{DISPLAY_NAME} schema created in {result['database']}")
    print(f"  Tables: {result['tables']}")
    print(f"  Indexes: {result['indexes']}")
