#!/usr/bin/env python3
"""EduClaw LMS Integration schema — 39 tables (32 parent + 7 new).

Generated by ERPForge Schema DSL (generate_schema.py)
Post-processed to add multi-column UNIQUE constraints on mapping tables
(generator limitation: single-column inline UNIQUE only).

Parent: educlaw | Tables: 39 | Indexes: 118 | New tables: 7

New tables (educlaw_lms_*):
  lms_sync domain    : educlaw_lms_connection, educlaw_lms_sync_log,
                       educlaw_lms_course_mapping, educlaw_lms_user_mapping
  assignments domain : educlaw_lms_assignment_mapping
  online_gradebook   : educlaw_lms_grade_sync
  course_materials   : educlaw_lms_course_material

Immutable tables (no updated_at — append-only):
  educlaw_lms_sync_log, educlaw_lms_grade_sync, educlaw_lms_course_mapping

Prerequisite: ERPClaw init_db.py must have run first (creates foundation tables).
Owning skill: educlaw-lms (sub-vertical of educlaw)
Run: python3 init_db.py [db_path]
"""
import os
import sqlite3
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from educlaw_base_schema import ensure_educlaw_base_tables


DEFAULT_DB_PATH = os.path.expanduser("~/.openclaw/erpclaw/data.sqlite")


def create_educlaw_lms_tables(db_path):
    conn = sqlite3.connect(db_path)
    from erpclaw_lib.db import setup_pragmas
    setup_pragmas(conn)

    # Verify foundation exists
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()]
    if "company" not in tables:
        print("ERROR: Foundation tables not found. Run erpclaw-setup first.")
        sys.exit(1)

    # Ensure parent schema (educlaw base tables) exists
    ensure_educlaw_base_tables(conn)


    conn.executescript("""
        -- ==========================================================
        -- EduClaw Domain Tables
        -- Generated by ERPForge Schema DSL
        -- Tables: 7 | Columns: 131
        -- ==========================================================

        -- educlaw_lms_connection (owned by lms_sync)
        CREATE TABLE IF NOT EXISTS educlaw_lms_connection (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            display_name TEXT NOT NULL DEFAULT '',
            lms_type TEXT NOT NULL DEFAULT '' CHECK(lms_type IN ('canvas','moodle','google_classroom','oneroster_csv')),
            endpoint_url TEXT NOT NULL DEFAULT '',
            client_id TEXT NOT NULL DEFAULT '',
            client_secret_encrypted TEXT NOT NULL DEFAULT '',
            site_token_encrypted TEXT NOT NULL DEFAULT '',
            google_credentials_encrypted TEXT NOT NULL DEFAULT '',
            lms_site_name TEXT NOT NULL DEFAULT '',
            lms_version TEXT NOT NULL DEFAULT '',
            grade_direction TEXT NOT NULL DEFAULT 'lms_to_sis' CHECK(grade_direction IN ('lms_to_sis','sis_to_lms','manual')),
            auto_sync_enabled INTEGER NOT NULL DEFAULT 0,
            sync_frequency_hours INTEGER NOT NULL DEFAULT 0,
            last_sync_at TEXT NOT NULL DEFAULT '',
            default_course_prefix TEXT NOT NULL DEFAULT '',
            auto_push_assignments INTEGER NOT NULL DEFAULT 0,
            has_dpa_signed INTEGER NOT NULL DEFAULT 0,
            dpa_signed_date TEXT NOT NULL DEFAULT '',
            is_coppa_verified INTEGER NOT NULL DEFAULT 0,
            coppa_cert_url TEXT NOT NULL DEFAULT '',
            allowed_data_fields TEXT NOT NULL DEFAULT '[]',
            status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','inactive','error')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_lms_assignment_mapping (owned by assignments)
        CREATE TABLE IF NOT EXISTS educlaw_lms_assignment_mapping (
            id TEXT PRIMARY KEY,
            lms_connection_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            assessment_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_assessment(id) ON DELETE RESTRICT,
            lms_assignment_id TEXT NOT NULL DEFAULT '',
            lms_assignment_url TEXT NOT NULL DEFAULT '',
            lms_grade_scheme TEXT NOT NULL DEFAULT '',
            push_direction TEXT NOT NULL DEFAULT 'sis_to_lms' CHECK(push_direction IN ('sis_to_lms','lms_to_sis')),
            is_published_in_lms INTEGER NOT NULL DEFAULT 0,
            sync_status TEXT NOT NULL DEFAULT 'synced' CHECK(sync_status IN ('synced','pending','error')),
            last_synced_at TEXT NOT NULL DEFAULT '',
            sync_error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(lms_connection_id, assessment_id),
            UNIQUE(lms_assignment_id, lms_connection_id)
        );

        -- educlaw_lms_course_mapping (owned by lms_sync)
        CREATE TABLE IF NOT EXISTS educlaw_lms_course_mapping (
            id TEXT PRIMARY KEY,
            lms_connection_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            section_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            lms_course_id TEXT NOT NULL DEFAULT '',
            lms_course_url TEXT NOT NULL DEFAULT '',
            lms_term_id TEXT NOT NULL DEFAULT '',
            sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending','synced','error','closed')),
            last_synced_at TEXT NOT NULL DEFAULT '',
            sync_error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(lms_connection_id, section_id),
            UNIQUE(lms_course_id, lms_connection_id)
        );

        -- educlaw_lms_course_material (owned by course_materials)
        CREATE TABLE IF NOT EXISTS educlaw_lms_course_material (
            id TEXT PRIMARY KEY,
            section_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            assessment_id TEXT REFERENCES educlaw_assessment(id) ON DELETE RESTRICT,
            name TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            material_type TEXT NOT NULL DEFAULT '' CHECK(material_type IN ('syllabus','reading','video_link','assignment_guide','rubric','other')),
            access_type TEXT NOT NULL DEFAULT '' CHECK(access_type IN ('url','file_attachment','lms_linked')),
            external_url TEXT NOT NULL DEFAULT '',
            file_path TEXT NOT NULL DEFAULT '',
            lms_connection_id TEXT REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            lms_file_id TEXT NOT NULL DEFAULT '',
            lms_download_url TEXT NOT NULL DEFAULT '',
            is_visible_to_students INTEGER NOT NULL DEFAULT 1,
            available_from TEXT NOT NULL DEFAULT '',
            available_until TEXT NOT NULL DEFAULT '',
            sort_order INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')),
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_lms_sync_log (owned by lms_sync)
        CREATE TABLE IF NOT EXISTS educlaw_lms_sync_log (
            id TEXT PRIMARY KEY,
            naming_series TEXT NOT NULL UNIQUE DEFAULT '',
            lms_connection_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            sync_type TEXT NOT NULL DEFAULT '' CHECK(sync_type IN ('roster_push','grade_pull','assignment_push','full_sync','oneroster_export')),
            academic_term_id TEXT REFERENCES educlaw_academic_term(id) ON DELETE RESTRICT,
            section_id TEXT REFERENCES educlaw_section(id) ON DELETE RESTRICT,
            triggered_by TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','completed','completed_with_errors','failed')),
            sections_synced INTEGER NOT NULL DEFAULT 0,
            students_synced INTEGER NOT NULL DEFAULT 0,
            grades_pulled INTEGER NOT NULL DEFAULT 0,
            grades_applied INTEGER NOT NULL DEFAULT 0,
            conflicts_flagged INTEGER NOT NULL DEFAULT 0,
            errors_count INTEGER NOT NULL DEFAULT 0,
            error_summary TEXT NOT NULL DEFAULT '[]',
            started_at TEXT NOT NULL DEFAULT '',
            completed_at TEXT NOT NULL DEFAULT '',
            duration_seconds INTEGER NOT NULL DEFAULT 0,
            company_id TEXT NOT NULL DEFAULT '' REFERENCES company(id) ON DELETE RESTRICT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_lms_grade_sync (owned by online_gradebook)
        CREATE TABLE IF NOT EXISTS educlaw_lms_grade_sync (
            id TEXT PRIMARY KEY,
            lms_connection_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            sync_log_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_sync_log(id) ON DELETE RESTRICT,
            lms_assignment_id TEXT NOT NULL DEFAULT '',
            lms_user_id TEXT NOT NULL DEFAULT '',
            assessment_id TEXT REFERENCES educlaw_assessment(id) ON DELETE RESTRICT,
            student_id TEXT REFERENCES educlaw_student(id) ON DELETE RESTRICT,
            assessment_result_id TEXT REFERENCES educlaw_assessment_result(id) ON DELETE RESTRICT,
            lms_score TEXT NOT NULL DEFAULT '',
            lms_grade TEXT NOT NULL DEFAULT '',
            lms_submitted_at TEXT NOT NULL DEFAULT '',
            lms_graded_at TEXT NOT NULL DEFAULT '',
            is_late INTEGER NOT NULL DEFAULT 0,
            is_missing INTEGER NOT NULL DEFAULT 0,
            lms_comments TEXT NOT NULL DEFAULT '',
            sis_score TEXT NOT NULL DEFAULT '',
            is_conflict INTEGER NOT NULL DEFAULT 0,
            conflict_type TEXT NOT NULL DEFAULT '' CHECK(conflict_type IN ('','score_mismatch','submitted_grade_locked','student_not_found','assignment_not_found')),
            sync_status TEXT NOT NULL DEFAULT 'pulled' CHECK(sync_status IN ('pulled','applied','conflict','skipped','error')),
            resolved_by TEXT NOT NULL DEFAULT '',
            resolved_at TEXT NOT NULL DEFAULT '',
            resolution TEXT NOT NULL DEFAULT '' CHECK(resolution IN ('','lms_wins','sis_wins','manual')),
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT ''
        );

        -- educlaw_lms_user_mapping (owned by lms_sync)
        CREATE TABLE IF NOT EXISTS educlaw_lms_user_mapping (
            id TEXT PRIMARY KEY,
            lms_connection_id TEXT NOT NULL DEFAULT '' REFERENCES educlaw_lms_connection(id) ON DELETE RESTRICT,
            sis_user_type TEXT NOT NULL DEFAULT '' CHECK(sis_user_type IN ('student','instructor')),
            sis_user_id TEXT NOT NULL DEFAULT '',
            lms_user_id TEXT NOT NULL DEFAULT '',
            lms_username TEXT NOT NULL DEFAULT '',
            lms_login_email TEXT NOT NULL DEFAULT '',
            is_coppa_restricted INTEGER NOT NULL DEFAULT 0,
            is_directory_restricted INTEGER NOT NULL DEFAULT 0,
            sync_status TEXT NOT NULL DEFAULT 'synced' CHECK(sync_status IN ('synced','pending','error','invited')),
            last_synced_at TEXT NOT NULL DEFAULT '',
            sync_error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT '',
            UNIQUE(lms_connection_id, sis_user_type, sis_user_id),
            UNIQUE(lms_user_id, lms_connection_id)
        );

        -- ==========================================================
        -- Indexes
        -- ==========================================================

        CREATE INDEX IF NOT EXISTS idx_lms_connection_company_type_status ON educlaw_lms_connection(company_id, lms_type, status);
        CREATE INDEX IF NOT EXISTS idx_lms_connection_naming_series ON educlaw_lms_connection(naming_series);
        CREATE INDEX IF NOT EXISTS idx_lms_connection_company_status ON educlaw_lms_connection(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_lms_assign_map_conn_assess ON educlaw_lms_assignment_mapping(lms_connection_id, assessment_id);
        CREATE INDEX IF NOT EXISTS idx_lms_assign_map_lms_assign_conn ON educlaw_lms_assignment_mapping(lms_assignment_id, lms_connection_id);
        CREATE INDEX IF NOT EXISTS idx_lms_assign_map_sync_status ON educlaw_lms_assignment_mapping(lms_connection_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_lms_assign_map_assessment ON educlaw_lms_assignment_mapping(assessment_id);
        CREATE INDEX IF NOT EXISTS idx_lms_course_map_conn_section ON educlaw_lms_course_mapping(lms_connection_id, section_id);
        CREATE INDEX IF NOT EXISTS idx_lms_course_map_lms_course_conn ON educlaw_lms_course_mapping(lms_course_id, lms_connection_id);
        CREATE INDEX IF NOT EXISTS idx_lms_course_map_conn_status ON educlaw_lms_course_mapping(lms_connection_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_lms_material_section_order ON educlaw_lms_course_material(section_id, sort_order);
        CREATE INDEX IF NOT EXISTS idx_lms_material_section_type ON educlaw_lms_course_material(section_id, material_type);
        CREATE INDEX IF NOT EXISTS idx_lms_material_assessment ON educlaw_lms_course_material(assessment_id);
        CREATE INDEX IF NOT EXISTS idx_lms_material_company_status ON educlaw_lms_course_material(company_id, status);
        CREATE INDEX IF NOT EXISTS idx_lms_material_lms_conn ON educlaw_lms_course_material(lms_connection_id);
        CREATE INDEX IF NOT EXISTS idx_lms_sync_log_conn_status ON educlaw_lms_sync_log(lms_connection_id, status);
        CREATE INDEX IF NOT EXISTS idx_lms_sync_log_term_type ON educlaw_lms_sync_log(academic_term_id, sync_type);
        CREATE INDEX IF NOT EXISTS idx_lms_sync_log_company_created ON educlaw_lms_sync_log(company_id, created_at);
        CREATE INDEX IF NOT EXISTS idx_lms_sync_log_naming_series ON educlaw_lms_sync_log(naming_series);
        CREATE INDEX IF NOT EXISTS idx_lms_sync_log_section ON educlaw_lms_sync_log(section_id);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_conn_assess_student ON educlaw_lms_grade_sync(lms_connection_id, assessment_id, student_id);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_status_conflict ON educlaw_lms_grade_sync(sync_status, is_conflict);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_assess_student_log ON educlaw_lms_grade_sync(assessment_id, student_id, sync_log_id);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_student_status ON educlaw_lms_grade_sync(student_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_log ON educlaw_lms_grade_sync(sync_log_id);
        CREATE INDEX IF NOT EXISTS idx_lms_grade_sync_conn_status ON educlaw_lms_grade_sync(lms_connection_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_lms_user_map_conn_type_user ON educlaw_lms_user_mapping(lms_connection_id, sis_user_type, sis_user_id);
        CREATE INDEX IF NOT EXISTS idx_lms_user_map_lms_user_conn ON educlaw_lms_user_mapping(lms_user_id, lms_connection_id);
        CREATE INDEX IF NOT EXISTS idx_lms_user_map_sync_status ON educlaw_lms_user_mapping(lms_connection_id, sync_status);
        CREATE INDEX IF NOT EXISTS idx_lms_user_map_sis_user ON educlaw_lms_user_mapping(sis_user_id, sis_user_type);
    """)

    conn.commit()
    conn.close()

    print(f"EduClaw LMS Integration schema created: 39 tables (32 parent + 7 new)")
    print(f"Database: {db_path}")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB_PATH
    parent_dir = os.path.dirname(db_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)
    create_educlaw_lms_tables(db_path)
